--reverting
UPDATE `creature_template` SET `ScriptName`='npc_frostworn_general' WHERE `entry`=36723;
UPDATE `creature_template` SET `ScriptName`='npc_raging_ghoul' WHERE `entry`=36940;
UPDATE `creature_template` SET `ScriptName`='npc_risen_witch_doctor' WHERE `entry`=36941;
UPDATE `creature_template` SET `ScriptName`='npc_spiritual_reflection' WHERE `entry`=37068;
UPDATE `creature_template` SET `ScriptName`='npc_jaina_or_sylvanas_hor' WHERE `entry` IN (37221,37223);
UPDATE `creature_template` SET `ScriptName`='boss_falric' WHERE `entry`=38112;
UPDATE `creature_template` SET `ScriptName`='boss_marwyn' WHERE `entry`=38113;
UPDATE `creature_template` SET `ScriptName`='npc_phantom_mage' WHERE `entry`=38172;
UPDATE `creature_template` SET `ScriptName`='npc_spectral_footman' WHERE `entry`=38173;
UPDATE `creature_template` SET `ScriptName`='npc_ghostly_priest' WHERE `entry`=38175;
UPDATE `creature_template` SET `ScriptName`='npc_tortured_rifleman' WHERE `entry`=38176;
UPDATE `creature_template` SET `ScriptName`='npc_shadowy_mercenary' WHERE `entry`=38177;
UPDATE `creature_template` SET `ScriptName`='npc_phantom_hallucination' WHERE `entry`=38567;
UPDATE `creature_template` SET `Scriptname`='npc_jaina_or_sylvanas_escape_hor' WHERE `entry` IN (36955,37554);
UPDATE `creature_template` SET `Scriptname`='' WHERE `entry`=36954;
UPDATE `areatrigger_scripts` SET `ScriptName`='at_hor_waves_restarter' WHERE `entry`=5697;
UPDATE `areatrigger_scripts` SET `ScriptName`='at_shadow_throne' WHERE `entry`=5605;
UPDATE `areatrigger_scripts` SET `ScriptName`='at_hor_intro_start' WHERE `entry`=5632;
UPDATE `instance_template` SET `script`='instance_halls_of_reflection' WHERE `map`=668;
DELETE FROM `gameobject_template` WHERE `entry` = 500001;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=72830;
UPDATE `creature_template` SET `Scriptname`='npc_abon' WHERE `entry`=37069;
UPDATE `creature_template` SET `Scriptname`='npc_risen_witch_doctor' WHERE `entry`=36941;
UPDATE `creature_template` SET `Scriptname`='npc_raging_gnoul' WHERE `entry`=36940;
DELETE FROM `script_waypoint` WHERE `entry` IN(36955,37554,37226);
DELETE FROM `gameobject` WHERE `map` = 668 AND (`guid` BETWEEN 400100 AND 400109);
DELETE FROM `areatrigger_scripts` WHERE `entry`=5740;
