-- 
UPDATE `gossip_menu_option` SET `OptionText`="Officer's Lounge", `OptionBroadcastTextID`=9749 WHERE `MenuID`=435 AND `OptionID`=10;
UPDATE `gossip_menu_option` SET `OptionText`="Officer's Lounge", `OptionBroadcastTextID`=9756 WHERE `MenuID`=1951 AND `OptionID`=9;
UPDATE `gossip_menu_option` SET `OptionText`="Zeppelin Master", `OptionBroadcastTextID`=5518 WHERE `MenuID`=1951 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Zeppelin Master", `OptionBroadcastTextID`=5518 WHERE `MenuID`=721 AND `OptionID`=12;
UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=7633 AND `OptionID`=7;
UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=1951 AND `OptionID`=7;
UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=7777 AND `OptionID`=7;
UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=721 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=721 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=1951 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=10043 AND `OptionID`=10;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=7777 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=10265 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=7633 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=2352 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8282 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8357 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8419 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=2121 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=2352 AND `OptionID`=3;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=8185 AND `OptionID`=1;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=435 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=10043 AND `OptionID`=7;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=3506 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=7633 AND `OptionID`=3;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=2121 AND `OptionID`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=3533 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=10265 AND `OptionID`=3;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=721 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=3580 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=7777 AND `OptionID`=3;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=8129 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=1951 AND `OptionID`=2;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8357 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8419 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8282 AND `OptionID`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=1951 AND `OptionID`=10;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=721 AND `OptionID`=8;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=2352 AND `OptionID`=8;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=435 AND `OptionID`=11;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=2121 AND `OptionID`=9;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=10265 AND `OptionID`=8;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=721 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=2352 AND `OptionID`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=435 AND `OptionID`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=1951 AND `OptionID`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=7633 AND `OptionID`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=2121 AND `OptionID`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=7777 AND `OptionID`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=10043 AND `OptionID`=1;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=10265 AND `OptionID`=0;
DELETE FROM `npc_text`  WHERE `ID` IN (30000,30001);
UPDATE `gossip_menu_option` SET `OptionText`="Teach me the ways of the spirits.", `OptionBroadcastTextID`=7658 WHERE `MenuID`=5123 AND `OptionID`=0;
