--
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID0` = b.`ID`  SET a.`lang0`= b.`LanguageID`, a.`text0_0` = b.`Text`, a.`text0_1` = b.`Text1`, a.`EmoteDelay0_0` = b.`EmoteDelay1`, a.`Emote0_0` = b.`EmoteID1`, a.`EmoteDelay0_1` = b.`EmoteDelay2`, a.`Emote0_1` = b.`EmoteID2`, a.`EmoteDelay0_2` = b.`EmoteDelay3`, a.`Emote0_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID1` = b.`ID`  SET a.`lang1`= b.`LanguageID`, a.`text1_0` = b.`Text`, a.`text1_1` = b.`Text1`, a.`EmoteDelay1_0` = b.`EmoteDelay1`, a.`Emote1_0` = b.`EmoteID1`, a.`EmoteDelay1_1` = b.`EmoteDelay2`, a.`Emote1_1` = b.`EmoteID2`, a.`EmoteDelay1_2` = b.`EmoteDelay3`, a.`Emote1_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID2` = b.`ID`  SET a.`lang2`= b.`LanguageID`, a.`text2_0` = b.`Text`, a.`text2_1` = b.`Text1`, a.`EmoteDelay2_0` = b.`EmoteDelay1`, a.`Emote2_0` = b.`EmoteID1`, a.`EmoteDelay2_1` = b.`EmoteDelay2`, a.`Emote2_1` = b.`EmoteID2`, a.`EmoteDelay2_2` = b.`EmoteDelay3`, a.`Emote2_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID3` = b.`ID`  SET a.`lang3`= b.`LanguageID`, a.`text3_0` = b.`Text`, a.`text3_1` = b.`Text1`, a.`EmoteDelay3_0` = b.`EmoteDelay1`, a.`Emote3_0` = b.`EmoteID1`, a.`EmoteDelay3_1` = b.`EmoteDelay2`, a.`Emote3_1` = b.`EmoteID2`, a.`EmoteDelay3_2` = b.`EmoteDelay3`, a.`Emote3_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID4` = b.`ID`  SET a.`lang4`= b.`LanguageID`, a.`text4_0` = b.`Text`, a.`text4_1` = b.`Text1`, a.`EmoteDelay4_0` = b.`EmoteDelay1`, a.`Emote4_0` = b.`EmoteID1`, a.`EmoteDelay4_1` = b.`EmoteDelay2`, a.`Emote4_1` = b.`EmoteID2`, a.`EmoteDelay4_2` = b.`EmoteDelay3`, a.`Emote4_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID5` = b.`ID`  SET a.`lang5`= b.`LanguageID`, a.`text5_0` = b.`Text`, a.`text5_1` = b.`Text1`, a.`EmoteDelay5_0` = b.`EmoteDelay1`, a.`Emote5_0` = b.`EmoteID1`, a.`EmoteDelay5_1` = b.`EmoteDelay2`, a.`Emote5_1` = b.`EmoteID2`, a.`EmoteDelay5_2` = b.`EmoteDelay3`, a.`Emote5_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID6` = b.`ID`  SET a.`lang6`= b.`LanguageID`, a.`text6_0` = b.`Text`, a.`text6_1` = b.`Text1`, a.`EmoteDelay6_0` = b.`EmoteDelay1`, a.`Emote6_0` = b.`EmoteID1`, a.`EmoteDelay6_1` = b.`EmoteDelay2`, a.`Emote6_1` = b.`EmoteID2`, a.`EmoteDelay6_2` = b.`EmoteDelay3`, a.`Emote6_2` = b.`EmoteID3`;
UPDATE `npc_text` AS a INNER JOIN `broadcast_text` AS b ON a.`BroadcastTextID7` = b.`ID`  SET a.`lang7`= b.`LanguageID`, a.`text7_0` = b.`Text`, a.`text7_1` = b.`Text1`, a.`EmoteDelay7_0` = b.`EmoteDelay1`, a.`Emote7_0` = b.`EmoteID1`, a.`EmoteDelay7_1` = b.`EmoteDelay2`, a.`Emote7_1` = b.`EmoteID2`, a.`EmoteDelay7_2` = b.`EmoteDelay3`, a.`Emote7_2` = b.`EmoteID3`;
