// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/client/v1/club_member.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "api/client/v1/club_member.pb.h"

#include <utility>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {
namespace club {
namespace v1 {
namespace client {

namespace {

const ::google::protobuf::Descriptor* Member_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Member_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberResult_reflection_ = NULL;
const ::google::protobuf::Descriptor* RemoveMemberOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RemoveMemberOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberRemovedAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberRemovedAssignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberVoiceOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberVoiceOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberVoiceState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberVoiceState_reflection_ = NULL;
const ::google::protobuf::Descriptor* CreateMemberOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CreateMemberOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberDescription_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberDescription_reflection_ = NULL;
const ::google::protobuf::Descriptor* RoleOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RoleOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* RoleAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RoleAssignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberAttributeAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberAttributeAssignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscriberStateOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscriberStateOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscriberStateAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscriberStateAssignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberStateOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberStateOptions_reflection_ = NULL;
const ::google::protobuf::Descriptor* MemberStateAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MemberStateAssignment_reflection_ = NULL;

}  // namespace

void protobuf_AssignDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto() {
  protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "api/client/v1/club_member.proto");
  GOOGLE_CHECK(file != NULL);
  Member_descriptor_ = file->message_type(0);
  static const int Member_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, battle_tag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, join_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, presence_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, moderator_mute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, whisper_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, note_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, active_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, voice_),
  };
  Member_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Member_descriptor_,
      Member::default_instance_,
      Member_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Member));
  MemberResult_descriptor_ = file->message_type(1);
  static const int MemberResult_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberResult, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberResult, status_),
  };
  MemberResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberResult_descriptor_,
      MemberResult::default_instance_,
      MemberResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberResult));
  RemoveMemberOptions_descriptor_ = file->message_type(2);
  static const int RemoveMemberOptions_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RemoveMemberOptions, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RemoveMemberOptions, reason_),
  };
  RemoveMemberOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RemoveMemberOptions_descriptor_,
      RemoveMemberOptions::default_instance_,
      RemoveMemberOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RemoveMemberOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RemoveMemberOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RemoveMemberOptions));
  MemberRemovedAssignment_descriptor_ = file->message_type(3);
  static const int MemberRemovedAssignment_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberRemovedAssignment, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberRemovedAssignment, reason_),
  };
  MemberRemovedAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberRemovedAssignment_descriptor_,
      MemberRemovedAssignment::default_instance_,
      MemberRemovedAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberRemovedAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberRemovedAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberRemovedAssignment));
  MemberVoiceOptions_descriptor_ = file->message_type(4);
  static const int MemberVoiceOptions_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, stream_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, joined_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, microphone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, active_),
  };
  MemberVoiceOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberVoiceOptions_descriptor_,
      MemberVoiceOptions::default_instance_,
      MemberVoiceOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberVoiceOptions));
  MemberVoiceState_descriptor_ = file->message_type(5);
  static const int MemberVoiceState_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, stream_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, joined_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, microphone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, active_),
  };
  MemberVoiceState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberVoiceState_descriptor_,
      MemberVoiceState::default_instance_,
      MemberVoiceState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberVoiceState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberVoiceState));
  CreateMemberOptions_descriptor_ = file->message_type(6);
  static const int CreateMemberOptions_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMemberOptions, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMemberOptions, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMemberOptions, join_club_source_),
  };
  CreateMemberOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CreateMemberOptions_descriptor_,
      CreateMemberOptions::default_instance_,
      CreateMemberOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMemberOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMemberOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CreateMemberOptions));
  MemberDescription_descriptor_ = file->message_type(7);
  static const int MemberDescription_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberDescription, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberDescription, battle_tag_),
  };
  MemberDescription_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberDescription_descriptor_,
      MemberDescription::default_instance_,
      MemberDescription_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberDescription, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberDescription, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberDescription));
  RoleOptions_descriptor_ = file->message_type(8);
  static const int RoleOptions_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleOptions, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleOptions, role_),
  };
  RoleOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RoleOptions_descriptor_,
      RoleOptions::default_instance_,
      RoleOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RoleOptions));
  RoleAssignment_descriptor_ = file->message_type(9);
  static const int RoleAssignment_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleAssignment, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleAssignment, role_),
  };
  RoleAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RoleAssignment_descriptor_,
      RoleAssignment::default_instance_,
      RoleAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RoleAssignment));
  MemberAttributeAssignment_descriptor_ = file->message_type(10);
  static const int MemberAttributeAssignment_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberAttributeAssignment, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberAttributeAssignment, attribute_),
  };
  MemberAttributeAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberAttributeAssignment_descriptor_,
      MemberAttributeAssignment::default_instance_,
      MemberAttributeAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberAttributeAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberAttributeAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberAttributeAssignment));
  SubscriberStateOptions_descriptor_ = file->message_type(11);
  static const int SubscriberStateOptions_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateOptions, voice_),
  };
  SubscriberStateOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SubscriberStateOptions_descriptor_,
      SubscriberStateOptions::default_instance_,
      SubscriberStateOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SubscriberStateOptions));
  SubscriberStateAssignment_descriptor_ = file->message_type(12);
  static const int SubscriberStateAssignment_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateAssignment, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateAssignment, active_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateAssignment, voice_),
  };
  SubscriberStateAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SubscriberStateAssignment_descriptor_,
      SubscriberStateAssignment::default_instance_,
      SubscriberStateAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscriberStateAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SubscriberStateAssignment));
  MemberStateOptions_descriptor_ = file->message_type(13);
  static const int MemberStateOptions_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, presence_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, moderator_mute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, whisper_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, note_),
  };
  MemberStateOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberStateOptions_descriptor_,
      MemberStateOptions::default_instance_,
      MemberStateOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberStateOptions));
  MemberStateAssignment_descriptor_ = file->message_type(14);
  static const int MemberStateAssignment_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, member_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, presence_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, moderator_mute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, whisper_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, note_),
  };
  MemberStateAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MemberStateAssignment_descriptor_,
      MemberStateAssignment::default_instance_,
      MemberStateAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MemberStateAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MemberStateAssignment));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Member_descriptor_, &Member::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberResult_descriptor_, &MemberResult::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RemoveMemberOptions_descriptor_, &RemoveMemberOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberRemovedAssignment_descriptor_, &MemberRemovedAssignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberVoiceOptions_descriptor_, &MemberVoiceOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberVoiceState_descriptor_, &MemberVoiceState::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CreateMemberOptions_descriptor_, &CreateMemberOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberDescription_descriptor_, &MemberDescription::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RoleOptions_descriptor_, &RoleOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RoleAssignment_descriptor_, &RoleAssignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberAttributeAssignment_descriptor_, &MemberAttributeAssignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SubscriberStateOptions_descriptor_, &SubscriberStateOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SubscriberStateAssignment_descriptor_, &SubscriberStateAssignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberStateOptions_descriptor_, &MemberStateOptions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MemberStateAssignment_descriptor_, &MemberStateAssignment::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_api_2fclient_2fv1_2fclub_5fmember_2eproto() {
  delete Member::default_instance_;
  delete Member_reflection_;
  delete MemberResult::default_instance_;
  delete MemberResult_reflection_;
  delete RemoveMemberOptions::default_instance_;
  delete RemoveMemberOptions_reflection_;
  delete MemberRemovedAssignment::default_instance_;
  delete MemberRemovedAssignment_reflection_;
  delete MemberVoiceOptions::default_instance_;
  delete MemberVoiceOptions_reflection_;
  delete MemberVoiceState::default_instance_;
  delete MemberVoiceState_reflection_;
  delete CreateMemberOptions::default_instance_;
  delete CreateMemberOptions_reflection_;
  delete MemberDescription::default_instance_;
  delete MemberDescription_reflection_;
  delete RoleOptions::default_instance_;
  delete RoleOptions_reflection_;
  delete RoleAssignment::default_instance_;
  delete RoleAssignment_reflection_;
  delete MemberAttributeAssignment::default_instance_;
  delete MemberAttributeAssignment_reflection_;
  delete SubscriberStateOptions::default_instance_;
  delete SubscriberStateOptions_reflection_;
  delete SubscriberStateAssignment::default_instance_;
  delete SubscriberStateAssignment_reflection_;
  delete MemberStateOptions::default_instance_;
  delete MemberStateOptions_reflection_;
  delete MemberStateAssignment::default_instance_;
  delete MemberStateAssignment_reflection_;
}

void protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::bgs::protocol::club::v1::protobuf_AddDesc_api_2fcommon_2fv1_2fclub_5fmember_5fid_2eproto();
  ::bgs::protocol::v2::protobuf_AddDesc_api_2fcommon_2fv2_2fattribute_5ftypes_2eproto();
  ::bgs::protocol::club::v1::client::protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fenum_2eproto();
  ::bgs::protocol::protobuf_AddDesc_rpc_5ftypes_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037api/client/v1/club_member.proto\022\033bgs.p"
    "rotocol.club.v1.client\032\"api/common/v1/cl"
    "ub_member_id.proto\032#api/common/v2/attrib"
    "ute_types.proto\032\035api/client/v1/club_enum"
    ".proto\032\017rpc_types.proto\"\236\003\n\006Member\022*\n\002id"
    "\030\001 \001(\0132\036.bgs.protocol.club.v1.MemberId\022\032"
    "\n\nbattle_tag\030\002 \001(\tB\006\202\371+\002\010\001\022\020\n\004role\030\003 \003(\r"
    "B\002\020\001\022-\n\tattribute\030\004 \003(\0132\032.bgs.protocol.v"
    "2.Attribute\022\021\n\tjoin_time\030\005 \001(\004\022B\n\016presen"
    "ce_level\030\006 \001(\0162*.bgs.protocol.club.v1.cl"
    "ient.PresenceLevel\022\026\n\016moderator_mute\030\007 \001"
    "(\010\022@\n\rwhisper_level\030\010 \001(\0162).bgs.protocol"
    ".club.v1.client.WhisperLevel\022\014\n\004note\030\t \001"
    "(\t\022\016\n\006active\0302 \001(\010\022<\n\005voice\0303 \001(\0132-.bgs."
    "protocol.club.v1.client.MemberVoiceState"
    "\"Q\n\014MemberResult\0221\n\tmember_id\030\001 \001(\0132\036.bg"
    "s.protocol.club.v1.MemberId\022\016\n\006status\030\002 "
    "\001(\r\"\201\001\n\023RemoveMemberOptions\022*\n\002id\030\001 \001(\0132"
    "\036.bgs.protocol.club.v1.MemberId\022>\n\006reaso"
    "n\030\002 \001(\0162..bgs.protocol.club.v1.client.Cl"
    "ubRemovedReason\"\205\001\n\027MemberRemovedAssignm"
    "ent\022*\n\002id\030\001 \001(\0132\036.bgs.protocol.club.v1.M"
    "emberId\022>\n\006reason\030\002 \001(\0162..bgs.protocol.c"
    "lub.v1.client.ClubRemovedReason\"\216\001\n\022Memb"
    "erVoiceOptions\022\021\n\tstream_id\030\001 \001(\004\022\016\n\006joi"
    "ned\030\002 \001(\010\022E\n\nmicrophone\030\003 \001(\01621.bgs.prot"
    "ocol.club.v1.client.VoiceMicrophoneState"
    "\022\016\n\006active\030\004 \001(\010\"\230\001\n\020MemberVoiceState\022\n\n"
    "\002id\030\001 \001(\t\022\021\n\tstream_id\030\002 \001(\004\022\016\n\006joined\030\003"
    " \001(\010\022E\n\nmicrophone\030\004 \001(\01621.bgs.protocol."
    "club.v1.client.VoiceMicrophoneState\022\016\n\006a"
    "ctive\030\005 \001(\010\"\240\001\n\023CreateMemberOptions\022*\n\002i"
    "d\030\001 \001(\0132\036.bgs.protocol.club.v1.MemberId\022"
    "-\n\tattribute\030\002 \003(\0132\032.bgs.protocol.v2.Att"
    "ribute\022.\n\020join_club_source\030\003 \001(\rB\024\202\371+\020*\016"
    "JoinClubSource\"[\n\021MemberDescription\022*\n\002i"
    "d\030\001 \001(\0132\036.bgs.protocol.club.v1.MemberId\022"
    "\032\n\nbattle_tag\030\002 \001(\tB\006\202\371+\002\010\001\"^\n\013RoleOptio"
    "ns\0221\n\tmember_id\030\001 \001(\0132\036.bgs.protocol.clu"
    "b.v1.MemberId\022\034\n\004role\030\002 \003(\rB\016\020\001\212\371+\010*\006\n\004\010"
    "\001\020\001\"U\n\016RoleAssignment\0221\n\tmember_id\030\001 \001(\013"
    "2\036.bgs.protocol.club.v1.MemberId\022\020\n\004role"
    "\030\002 \003(\rB\002\020\001\"}\n\031MemberAttributeAssignment\022"
    "1\n\tmember_id\030\001 \001(\0132\036.bgs.protocol.club.v"
    "1.MemberId\022-\n\tattribute\030\002 \003(\0132\032.bgs.prot"
    "ocol.v2.Attribute\"X\n\026SubscriberStateOpti"
    "ons\022>\n\005voice\030\001 \001(\0132/.bgs.protocol.club.v"
    "1.client.MemberVoiceOptions\"\234\001\n\031Subscrib"
    "erStateAssignment\0221\n\tmember_id\030\001 \001(\0132\036.b"
    "gs.protocol.club.v1.MemberId\022\016\n\006active\030\002"
    " \001(\010\022<\n\005voice\030\003 \001(\0132-.bgs.protocol.club."
    "v1.client.MemberVoiceState\"\357\001\n\022MemberSta"
    "teOptions\022-\n\tattribute\030\001 \003(\0132\032.bgs.proto"
    "col.v2.Attribute\022B\n\016presence_level\030\002 \001(\016"
    "2*.bgs.protocol.club.v1.client.PresenceL"
    "evel\022\026\n\016moderator_mute\030\003 \001(\010\022@\n\rwhisper_"
    "level\030\004 \001(\0162).bgs.protocol.club.v1.clien"
    "t.WhisperLevel\022\014\n\004note\030\005 \001(\t\"\245\002\n\025MemberS"
    "tateAssignment\0221\n\tmember_id\030\001 \001(\0132\036.bgs."
    "protocol.club.v1.MemberId\022-\n\tattribute\030\002"
    " \003(\0132\032.bgs.protocol.v2.Attribute\022B\n\016pres"
    "ence_level\030\003 \001(\0162*.bgs.protocol.club.v1."
    "client.PresenceLevel\022\026\n\016moderator_mute\030\004"
    " \001(\010\022@\n\rwhisper_level\030\005 \001(\0162).bgs.protoc"
    "ol.club.v1.client.WhisperLevel\022\014\n\004note\030\006"
    " \001(\tB\002H\002P\000", 2610);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "api/client/v1/club_member.proto", &protobuf_RegisterTypes);
  Member::default_instance_ = new Member();
  MemberResult::default_instance_ = new MemberResult();
  RemoveMemberOptions::default_instance_ = new RemoveMemberOptions();
  MemberRemovedAssignment::default_instance_ = new MemberRemovedAssignment();
  MemberVoiceOptions::default_instance_ = new MemberVoiceOptions();
  MemberVoiceState::default_instance_ = new MemberVoiceState();
  CreateMemberOptions::default_instance_ = new CreateMemberOptions();
  MemberDescription::default_instance_ = new MemberDescription();
  RoleOptions::default_instance_ = new RoleOptions();
  RoleAssignment::default_instance_ = new RoleAssignment();
  MemberAttributeAssignment::default_instance_ = new MemberAttributeAssignment();
  SubscriberStateOptions::default_instance_ = new SubscriberStateOptions();
  SubscriberStateAssignment::default_instance_ = new SubscriberStateAssignment();
  MemberStateOptions::default_instance_ = new MemberStateOptions();
  MemberStateAssignment::default_instance_ = new MemberStateAssignment();
  Member::default_instance_->InitAsDefaultInstance();
  MemberResult::default_instance_->InitAsDefaultInstance();
  RemoveMemberOptions::default_instance_->InitAsDefaultInstance();
  MemberRemovedAssignment::default_instance_->InitAsDefaultInstance();
  MemberVoiceOptions::default_instance_->InitAsDefaultInstance();
  MemberVoiceState::default_instance_->InitAsDefaultInstance();
  CreateMemberOptions::default_instance_->InitAsDefaultInstance();
  MemberDescription::default_instance_->InitAsDefaultInstance();
  RoleOptions::default_instance_->InitAsDefaultInstance();
  RoleAssignment::default_instance_->InitAsDefaultInstance();
  MemberAttributeAssignment::default_instance_->InitAsDefaultInstance();
  SubscriberStateOptions::default_instance_->InitAsDefaultInstance();
  SubscriberStateAssignment::default_instance_->InitAsDefaultInstance();
  MemberStateOptions::default_instance_->InitAsDefaultInstance();
  MemberStateAssignment::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_api_2fclient_2fv1_2fclub_5fmember_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_api_2fclient_2fv1_2fclub_5fmember_2eproto {
  StaticDescriptorInitializer_api_2fclient_2fv1_2fclub_5fmember_2eproto() {
    protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  }
} static_descriptor_initializer_api_2fclient_2fv1_2fclub_5fmember_2eproto_;
// ===================================================================

#ifndef _MSC_VER
const int Member::kIdFieldNumber;
const int Member::kBattleTagFieldNumber;
const int Member::kRoleFieldNumber;
const int Member::kAttributeFieldNumber;
const int Member::kJoinTimeFieldNumber;
const int Member::kPresenceLevelFieldNumber;
const int Member::kModeratorMuteFieldNumber;
const int Member::kWhisperLevelFieldNumber;
const int Member::kNoteFieldNumber;
const int Member::kActiveFieldNumber;
const int Member::kVoiceFieldNumber;
#endif  // !_MSC_VER

Member::Member()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.Member)
}

void Member::InitAsDefaultInstance() {
  id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
  voice_ = const_cast< ::bgs::protocol::club::v1::client::MemberVoiceState*>(&::bgs::protocol::club::v1::client::MemberVoiceState::default_instance());
}

Member::Member(const Member& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.Member)
}

void Member::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = NULL;
  battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  join_time_ = GOOGLE_ULONGLONG(0);
  presence_level_ = 0;
  moderator_mute_ = false;
  whisper_level_ = 0;
  note_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  active_ = false;
  voice_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Member::~Member() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.Member)
  SharedDtor();
}

void Member::SharedDtor() {
  if (battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete battle_tag_;
  }
  if (note_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete note_;
  }
  if (this != default_instance_) {
    delete id_;
    delete voice_;
  }
}

void Member::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Member::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Member_descriptor_;
}

const Member& Member::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

Member* Member::default_instance_ = NULL;

Member* Member::New() const {
  return new Member;
}

void Member::Swap(Member* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata Member::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Member_descriptor_;
  metadata.reflection = Member_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberResult::kMemberIdFieldNumber;
const int MemberResult::kStatusFieldNumber;
#endif  // !_MSC_VER

MemberResult::MemberResult()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberResult)
}

void MemberResult::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

MemberResult::MemberResult(const MemberResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberResult)
}

void MemberResult::SharedCtor() {
  _cached_size_ = 0;
  member_id_ = NULL;
  status_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberResult::~MemberResult() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberResult)
  SharedDtor();
}

void MemberResult::SharedDtor() {
  if (this != default_instance_) {
    delete member_id_;
  }
}

void MemberResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberResult_descriptor_;
}

const MemberResult& MemberResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberResult* MemberResult::default_instance_ = NULL;

MemberResult* MemberResult::New() const {
  return new MemberResult;
}

void MemberResult::Swap(MemberResult* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberResult_descriptor_;
  metadata.reflection = MemberResult_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int RemoveMemberOptions::kIdFieldNumber;
const int RemoveMemberOptions::kReasonFieldNumber;
#endif  // !_MSC_VER

RemoveMemberOptions::RemoveMemberOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.RemoveMemberOptions)
}

void RemoveMemberOptions::InitAsDefaultInstance() {
  id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

RemoveMemberOptions::RemoveMemberOptions(const RemoveMemberOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.RemoveMemberOptions)
}

void RemoveMemberOptions::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  reason_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RemoveMemberOptions::~RemoveMemberOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.RemoveMemberOptions)
  SharedDtor();
}

void RemoveMemberOptions::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
  }
}

void RemoveMemberOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RemoveMemberOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RemoveMemberOptions_descriptor_;
}

const RemoveMemberOptions& RemoveMemberOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

RemoveMemberOptions* RemoveMemberOptions::default_instance_ = NULL;

RemoveMemberOptions* RemoveMemberOptions::New() const {
  return new RemoveMemberOptions;
}

void RemoveMemberOptions::Swap(RemoveMemberOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RemoveMemberOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RemoveMemberOptions_descriptor_;
  metadata.reflection = RemoveMemberOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberRemovedAssignment::kIdFieldNumber;
const int MemberRemovedAssignment::kReasonFieldNumber;
#endif  // !_MSC_VER

MemberRemovedAssignment::MemberRemovedAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberRemovedAssignment)
}

void MemberRemovedAssignment::InitAsDefaultInstance() {
  id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

MemberRemovedAssignment::MemberRemovedAssignment(const MemberRemovedAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberRemovedAssignment)
}

void MemberRemovedAssignment::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  reason_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberRemovedAssignment::~MemberRemovedAssignment() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberRemovedAssignment)
  SharedDtor();
}

void MemberRemovedAssignment::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
  }
}

void MemberRemovedAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberRemovedAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberRemovedAssignment_descriptor_;
}

const MemberRemovedAssignment& MemberRemovedAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberRemovedAssignment* MemberRemovedAssignment::default_instance_ = NULL;

MemberRemovedAssignment* MemberRemovedAssignment::New() const {
  return new MemberRemovedAssignment;
}

void MemberRemovedAssignment::Swap(MemberRemovedAssignment* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberRemovedAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberRemovedAssignment_descriptor_;
  metadata.reflection = MemberRemovedAssignment_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberVoiceOptions::kStreamIdFieldNumber;
const int MemberVoiceOptions::kJoinedFieldNumber;
const int MemberVoiceOptions::kMicrophoneFieldNumber;
const int MemberVoiceOptions::kActiveFieldNumber;
#endif  // !_MSC_VER

MemberVoiceOptions::MemberVoiceOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberVoiceOptions)
}

void MemberVoiceOptions::InitAsDefaultInstance() {
}

MemberVoiceOptions::MemberVoiceOptions(const MemberVoiceOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberVoiceOptions)
}

void MemberVoiceOptions::SharedCtor() {
  _cached_size_ = 0;
  stream_id_ = GOOGLE_ULONGLONG(0);
  joined_ = false;
  microphone_ = 0;
  active_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberVoiceOptions::~MemberVoiceOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberVoiceOptions)
  SharedDtor();
}

void MemberVoiceOptions::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MemberVoiceOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberVoiceOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberVoiceOptions_descriptor_;
}

const MemberVoiceOptions& MemberVoiceOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberVoiceOptions* MemberVoiceOptions::default_instance_ = NULL;

MemberVoiceOptions* MemberVoiceOptions::New() const {
  return new MemberVoiceOptions;
}

void MemberVoiceOptions::Swap(MemberVoiceOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberVoiceOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberVoiceOptions_descriptor_;
  metadata.reflection = MemberVoiceOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberVoiceState::kIdFieldNumber;
const int MemberVoiceState::kStreamIdFieldNumber;
const int MemberVoiceState::kJoinedFieldNumber;
const int MemberVoiceState::kMicrophoneFieldNumber;
const int MemberVoiceState::kActiveFieldNumber;
#endif  // !_MSC_VER

MemberVoiceState::MemberVoiceState()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberVoiceState)
}

void MemberVoiceState::InitAsDefaultInstance() {
}

MemberVoiceState::MemberVoiceState(const MemberVoiceState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberVoiceState)
}

void MemberVoiceState::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stream_id_ = GOOGLE_ULONGLONG(0);
  joined_ = false;
  microphone_ = 0;
  active_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberVoiceState::~MemberVoiceState() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberVoiceState)
  SharedDtor();
}

void MemberVoiceState::SharedDtor() {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete id_;
  }
  if (this != default_instance_) {
  }
}

void MemberVoiceState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberVoiceState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberVoiceState_descriptor_;
}

const MemberVoiceState& MemberVoiceState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberVoiceState* MemberVoiceState::default_instance_ = NULL;

MemberVoiceState* MemberVoiceState::New() const {
  return new MemberVoiceState;
}

void MemberVoiceState::Swap(MemberVoiceState* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberVoiceState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberVoiceState_descriptor_;
  metadata.reflection = MemberVoiceState_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int CreateMemberOptions::kIdFieldNumber;
const int CreateMemberOptions::kAttributeFieldNumber;
const int CreateMemberOptions::kJoinClubSourceFieldNumber;
#endif  // !_MSC_VER

CreateMemberOptions::CreateMemberOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.CreateMemberOptions)
}

void CreateMemberOptions::InitAsDefaultInstance() {
  id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

CreateMemberOptions::CreateMemberOptions(const CreateMemberOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.CreateMemberOptions)
}

void CreateMemberOptions::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  join_club_source_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CreateMemberOptions::~CreateMemberOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.CreateMemberOptions)
  SharedDtor();
}

void CreateMemberOptions::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
  }
}

void CreateMemberOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CreateMemberOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CreateMemberOptions_descriptor_;
}

const CreateMemberOptions& CreateMemberOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

CreateMemberOptions* CreateMemberOptions::default_instance_ = NULL;

CreateMemberOptions* CreateMemberOptions::New() const {
  return new CreateMemberOptions;
}

void CreateMemberOptions::Swap(CreateMemberOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata CreateMemberOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CreateMemberOptions_descriptor_;
  metadata.reflection = CreateMemberOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberDescription::kIdFieldNumber;
const int MemberDescription::kBattleTagFieldNumber;
#endif  // !_MSC_VER

MemberDescription::MemberDescription()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberDescription)
}

void MemberDescription::InitAsDefaultInstance() {
  id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

MemberDescription::MemberDescription(const MemberDescription& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberDescription)
}

void MemberDescription::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = NULL;
  battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberDescription::~MemberDescription() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberDescription)
  SharedDtor();
}

void MemberDescription::SharedDtor() {
  if (battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete battle_tag_;
  }
  if (this != default_instance_) {
    delete id_;
  }
}

void MemberDescription::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberDescription::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberDescription_descriptor_;
}

const MemberDescription& MemberDescription::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberDescription* MemberDescription::default_instance_ = NULL;

MemberDescription* MemberDescription::New() const {
  return new MemberDescription;
}

void MemberDescription::Swap(MemberDescription* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberDescription::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberDescription_descriptor_;
  metadata.reflection = MemberDescription_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int RoleOptions::kMemberIdFieldNumber;
const int RoleOptions::kRoleFieldNumber;
#endif  // !_MSC_VER

RoleOptions::RoleOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.RoleOptions)
}

void RoleOptions::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

RoleOptions::RoleOptions(const RoleOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.RoleOptions)
}

void RoleOptions::SharedCtor() {
  _cached_size_ = 0;
  member_id_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RoleOptions::~RoleOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.RoleOptions)
  SharedDtor();
}

void RoleOptions::SharedDtor() {
  if (this != default_instance_) {
    delete member_id_;
  }
}

void RoleOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoleOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoleOptions_descriptor_;
}

const RoleOptions& RoleOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

RoleOptions* RoleOptions::default_instance_ = NULL;

RoleOptions* RoleOptions::New() const {
  return new RoleOptions;
}

void RoleOptions::Swap(RoleOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RoleOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RoleOptions_descriptor_;
  metadata.reflection = RoleOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int RoleAssignment::kMemberIdFieldNumber;
const int RoleAssignment::kRoleFieldNumber;
#endif  // !_MSC_VER

RoleAssignment::RoleAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.RoleAssignment)
}

void RoleAssignment::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

RoleAssignment::RoleAssignment(const RoleAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.RoleAssignment)
}

void RoleAssignment::SharedCtor() {
  _cached_size_ = 0;
  member_id_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RoleAssignment::~RoleAssignment() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.RoleAssignment)
  SharedDtor();
}

void RoleAssignment::SharedDtor() {
  if (this != default_instance_) {
    delete member_id_;
  }
}

void RoleAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoleAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoleAssignment_descriptor_;
}

const RoleAssignment& RoleAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

RoleAssignment* RoleAssignment::default_instance_ = NULL;

RoleAssignment* RoleAssignment::New() const {
  return new RoleAssignment;
}

void RoleAssignment::Swap(RoleAssignment* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RoleAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RoleAssignment_descriptor_;
  metadata.reflection = RoleAssignment_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberAttributeAssignment::kMemberIdFieldNumber;
const int MemberAttributeAssignment::kAttributeFieldNumber;
#endif  // !_MSC_VER

MemberAttributeAssignment::MemberAttributeAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberAttributeAssignment)
}

void MemberAttributeAssignment::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

MemberAttributeAssignment::MemberAttributeAssignment(const MemberAttributeAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberAttributeAssignment)
}

void MemberAttributeAssignment::SharedCtor() {
  _cached_size_ = 0;
  member_id_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberAttributeAssignment::~MemberAttributeAssignment() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberAttributeAssignment)
  SharedDtor();
}

void MemberAttributeAssignment::SharedDtor() {
  if (this != default_instance_) {
    delete member_id_;
  }
}

void MemberAttributeAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberAttributeAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberAttributeAssignment_descriptor_;
}

const MemberAttributeAssignment& MemberAttributeAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberAttributeAssignment* MemberAttributeAssignment::default_instance_ = NULL;

MemberAttributeAssignment* MemberAttributeAssignment::New() const {
  return new MemberAttributeAssignment;
}

void MemberAttributeAssignment::Swap(MemberAttributeAssignment* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberAttributeAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberAttributeAssignment_descriptor_;
  metadata.reflection = MemberAttributeAssignment_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int SubscriberStateOptions::kVoiceFieldNumber;
#endif  // !_MSC_VER

SubscriberStateOptions::SubscriberStateOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.SubscriberStateOptions)
}

void SubscriberStateOptions::InitAsDefaultInstance() {
  voice_ = const_cast< ::bgs::protocol::club::v1::client::MemberVoiceOptions*>(&::bgs::protocol::club::v1::client::MemberVoiceOptions::default_instance());
}

SubscriberStateOptions::SubscriberStateOptions(const SubscriberStateOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.SubscriberStateOptions)
}

void SubscriberStateOptions::SharedCtor() {
  _cached_size_ = 0;
  voice_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SubscriberStateOptions::~SubscriberStateOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.SubscriberStateOptions)
  SharedDtor();
}

void SubscriberStateOptions::SharedDtor() {
  if (this != default_instance_) {
    delete voice_;
  }
}

void SubscriberStateOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscriberStateOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscriberStateOptions_descriptor_;
}

const SubscriberStateOptions& SubscriberStateOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

SubscriberStateOptions* SubscriberStateOptions::default_instance_ = NULL;

SubscriberStateOptions* SubscriberStateOptions::New() const {
  return new SubscriberStateOptions;
}

void SubscriberStateOptions::Swap(SubscriberStateOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata SubscriberStateOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscriberStateOptions_descriptor_;
  metadata.reflection = SubscriberStateOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int SubscriberStateAssignment::kMemberIdFieldNumber;
const int SubscriberStateAssignment::kActiveFieldNumber;
const int SubscriberStateAssignment::kVoiceFieldNumber;
#endif  // !_MSC_VER

SubscriberStateAssignment::SubscriberStateAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.SubscriberStateAssignment)
}

void SubscriberStateAssignment::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
  voice_ = const_cast< ::bgs::protocol::club::v1::client::MemberVoiceState*>(&::bgs::protocol::club::v1::client::MemberVoiceState::default_instance());
}

SubscriberStateAssignment::SubscriberStateAssignment(const SubscriberStateAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.SubscriberStateAssignment)
}

void SubscriberStateAssignment::SharedCtor() {
  _cached_size_ = 0;
  member_id_ = NULL;
  active_ = false;
  voice_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SubscriberStateAssignment::~SubscriberStateAssignment() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.SubscriberStateAssignment)
  SharedDtor();
}

void SubscriberStateAssignment::SharedDtor() {
  if (this != default_instance_) {
    delete member_id_;
    delete voice_;
  }
}

void SubscriberStateAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscriberStateAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscriberStateAssignment_descriptor_;
}

const SubscriberStateAssignment& SubscriberStateAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

SubscriberStateAssignment* SubscriberStateAssignment::default_instance_ = NULL;

SubscriberStateAssignment* SubscriberStateAssignment::New() const {
  return new SubscriberStateAssignment;
}

void SubscriberStateAssignment::Swap(SubscriberStateAssignment* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata SubscriberStateAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscriberStateAssignment_descriptor_;
  metadata.reflection = SubscriberStateAssignment_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberStateOptions::kAttributeFieldNumber;
const int MemberStateOptions::kPresenceLevelFieldNumber;
const int MemberStateOptions::kModeratorMuteFieldNumber;
const int MemberStateOptions::kWhisperLevelFieldNumber;
const int MemberStateOptions::kNoteFieldNumber;
#endif  // !_MSC_VER

MemberStateOptions::MemberStateOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberStateOptions)
}

void MemberStateOptions::InitAsDefaultInstance() {
}

MemberStateOptions::MemberStateOptions(const MemberStateOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberStateOptions)
}

void MemberStateOptions::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  presence_level_ = 0;
  moderator_mute_ = false;
  whisper_level_ = 0;
  note_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberStateOptions::~MemberStateOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberStateOptions)
  SharedDtor();
}

void MemberStateOptions::SharedDtor() {
  if (note_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete note_;
  }
  if (this != default_instance_) {
  }
}

void MemberStateOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberStateOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberStateOptions_descriptor_;
}

const MemberStateOptions& MemberStateOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberStateOptions* MemberStateOptions::default_instance_ = NULL;

MemberStateOptions* MemberStateOptions::New() const {
  return new MemberStateOptions;
}

void MemberStateOptions::Swap(MemberStateOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberStateOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberStateOptions_descriptor_;
  metadata.reflection = MemberStateOptions_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int MemberStateAssignment::kMemberIdFieldNumber;
const int MemberStateAssignment::kAttributeFieldNumber;
const int MemberStateAssignment::kPresenceLevelFieldNumber;
const int MemberStateAssignment::kModeratorMuteFieldNumber;
const int MemberStateAssignment::kWhisperLevelFieldNumber;
const int MemberStateAssignment::kNoteFieldNumber;
#endif  // !_MSC_VER

MemberStateAssignment::MemberStateAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.club.v1.client.MemberStateAssignment)
}

void MemberStateAssignment::InitAsDefaultInstance() {
  member_id_ = const_cast< ::bgs::protocol::club::v1::MemberId*>(&::bgs::protocol::club::v1::MemberId::default_instance());
}

MemberStateAssignment::MemberStateAssignment(const MemberStateAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.club.v1.client.MemberStateAssignment)
}

void MemberStateAssignment::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  member_id_ = NULL;
  presence_level_ = 0;
  moderator_mute_ = false;
  whisper_level_ = 0;
  note_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MemberStateAssignment::~MemberStateAssignment() {
  // @@protoc_insertion_point(destructor:bgs.protocol.club.v1.client.MemberStateAssignment)
  SharedDtor();
}

void MemberStateAssignment::SharedDtor() {
  if (note_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete note_;
  }
  if (this != default_instance_) {
    delete member_id_;
  }
}

void MemberStateAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MemberStateAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MemberStateAssignment_descriptor_;
}

const MemberStateAssignment& MemberStateAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_api_2fclient_2fv1_2fclub_5fmember_2eproto();
  return *default_instance_;
}

MemberStateAssignment* MemberStateAssignment::default_instance_ = NULL;

MemberStateAssignment* MemberStateAssignment::New() const {
  return new MemberStateAssignment;
}

void MemberStateAssignment::Swap(MemberStateAssignment* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata MemberStateAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MemberStateAssignment_descriptor_;
  metadata.reflection = MemberStateAssignment_reflection_;
  return metadata;
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace v1
}  // namespace club
}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)
