DELETE FROM `spell_script_names` WHERE `spell_id` = '144359';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144370';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144774';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144379';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144788';
DELETE FROM `spell_script_names` WHERE `spell_id` = '147198';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144911';
DELETE FROM `spell_script_names` WHERE `spell_id` = '146818';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144836';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144574';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144636';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144683';
DELETE FROM `spell_script_names` WHERE `spell_id` = '144684';
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144359','spell_sha_of_pride_gift_of_titans');
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144370','spell_last_word');
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144774','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144379','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144788','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '147198','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144911','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '146818','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144836','spell_generic_modifier_pride'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144574','spell_corrupted_prison'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144636','spell_corrupted_prison'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144683','spell_corrupted_prison'); 
INSERT INTO `spell_script_names`(`spell_id`,`ScriptName`) VALUES ( '144684','spell_corrupted_prison'); 
UPDATE `areatrigger_data` SET `Radius`='3.5',`RadiusTarget`='3.5' WHERE `entry`='1110'; 