<?php
/*
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (0, 20, 2, "I wish to unlearn my specialization", 20, 16); -- default gossip
-- Others npc with gossip trainer
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3921, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4557, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4556, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (2304, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4525, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4526, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4527, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9691, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7368, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7260, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6647, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4558, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9692, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9693, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (2384, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (63, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (64, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4484, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4485, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4486, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4517, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4518, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4519, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4520, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4537, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4538, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4539, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4552, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4651, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4654, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4660, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4661, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4685, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4686, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6648, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7264, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9990, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7366, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4535, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (1503, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (1522, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (2381, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (2383, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4503, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4504, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4505, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4566, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4567, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4603, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4604, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4609, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4610, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4641, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4643, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4655, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4656, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4667, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4681, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4682, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6628, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7437, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7566, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4642, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4469, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4470, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4471, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4662, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4463, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4464, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3642, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (8111, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (523, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (655, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (656, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4091, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4475, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4481, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4482, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4509, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4511, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4546, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4547, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4548, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4568, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4569, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4570, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4578, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4579, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4581, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4645, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4649, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4650, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4653, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4683, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4684, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4696, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4697, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7263, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (1403, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3924, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3925, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3926, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4507, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4508, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4571, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4605, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4606, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4607, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4687, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4688, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7567, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4646, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4677, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4678, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3643, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3644, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3645, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4466, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4467, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4468, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4521, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4522, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4523, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4531, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4532, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4533, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4543, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4544, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4545, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4559, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4572, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4573, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4574, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4665, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4666, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4679, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4680, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4691, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4692, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4801, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6649, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7265, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7349, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7438, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (85, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (141, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (381, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (410, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (411, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (436, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3984, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4502, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4512, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4513, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4540, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4541, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4542, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4561, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4562, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4575, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4576, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4577, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4658, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4659, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4676, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4690, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (5061, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6650, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4008, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4009, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4010, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4011, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4012, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4017, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4023, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4101, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4472, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4473, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4474, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4506, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4524, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4549, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4550, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4551, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4647, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4648, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4657, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4675, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4693, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (4695, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (6652, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (7262, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11767, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9580, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12527, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12521, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9794, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9793, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (9792, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11154, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12540, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12539, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11829, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12233, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (3923, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11877, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11169, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (11266, 20, 2, "I wish to unlearn my specialization", 20, 16);
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (12516, 20, 2, "I wish to unlearn my specialization", 20, 16);
*/

// Mysql Connect
$connect = mysql_connect("host", "user", "passwd") or die (mysql_error());
mysql_select_db("505_world", $connect);


// Convert creature spawns data
$gossipInfo = mysql_query("SELECT menu_id FROM gossip_menu_option WHERE option_text = \"I wish to unlearn my talents.\"");

if(!$gossipInfo)
	die("Gossip empty");
	
while($row = mysql_fetch_assoc($gossipInfo))
{
	$id = $row['menu_id'];
	$request = "INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES (";
	$request.= $id;
	$request.=", 20, 2, \"I wish to unlearn my specialization\", 20, 16);";
	echo $request."<br>";
	mysql_query($request);
}
?>