#!/bin/bash
# /etc/init.d/tc-bnet

### BEGIN INIT INFO
# Provides: tc-bnet
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Trinity BattleNet server
# Description: Starts the Trinity BattleNet server
### END INIT INFO

#CONSTS
SERVER_ROOT=/root/of/server/bin

#COLORS
NC='\033[0m'
YELLOW='\33[0;33m'
LIGHT_YELLOW='\33[1;33m'
GREEN='\33[0;32m'
LIGHT_GREEN='\33[1;32m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'


function finally(){
	tput cnorm
	printf "${NC}\n"
	exit $?
}

function waitService(){
	tput sc
	printf "${LIGHT_GREEN}Starting $2 ($1) ${NC}"
	pidof $1 >/dev/null
	PID1=$?
	POINTS="."
	bADD=false
	while [ $PID1 -eq 1 ]; do
		pidof $1 >/dev/null
		PID1=$?
		sleep 0.1
		
		case "$POINTS" in
		  ".") 
			POINTS=".."
			tput cub 1
			if [ $bADD = true ]; then
				bADD=false
			else
				bADD=true
			fi
		  ;;
		  "..") 
			if [ $bADD = true ]; then
				POINTS="..."
			else
				POINTS="."
			fi
			tput cub 2
		  ;;
		  "...") 
			POINTS=".."
			tput cub 3
			if [ $bADD = true ]; then
				bADD=false
			else
				bADD=true
			fi
		  ;;
		esac
		tput el
		printf "${YELLOW}$POINTS${NC}"
	done
	tput rc
	tput el
	printf "${LIGHT_GREEN}$2 started !${NC}\n"	
}

function start_service(){
	SERVICE_EXE=$1
	SERVICE_NAME=$2
	pidof $SERVICE_EXE >/dev/null
	PID1=$?
	if [ $PID1 -eq 1 ]
	then
		screen -A -dmS $3 $SERVER_ROOT/$SERVICE_EXE		
		waitService $SERVICE_EXE $SERVICE_NAME
	else
		printf "${LIGHT_RED}$SERVICE_NAME is already running !${NC}\n"
	fi
}

function stop_service(){
	SERVICE_EXE=$1
	SERVICE_NAME=$2

	pidof $SERVICE_EXE >/dev/null
	PID1=$?
	if [ $PID1 -eq 0 ]
	then
		tput sc
		printf "${LIGHT_GREEN}Stopping $SERVICE_NAME...${NC}"
		PID=$(pidof $SERVICE_EXE);
		if ! kill -n 4 $PID >/dev/null 2>&1; then
			tput rc
			tput el
			printf "${LIGHT_RED}Unable to stop $SERVICE_NAME (pid : $PID)${NC}\n" >&2
		else
			tput rc
			tput el
			printf "${LIGHT_GREEN}$SERVICE_NAME stopped !${NC}\n"	
		fi
	else
	  printf "${LIGHT_RED}$SERVICE_NAME is not running !${NC}\n"
	fi
}

trap finally SIGINT
trap finally SIGTERM

cd $SERVER_ROOT

tput civis

case "$1" in
  start)
	start_service "bnetserver" "BattleNet Server" "bnet"
	;;
  stop)
	stop_service "bnetserver" "BattleNet Server"
    ;;
  restart)
	stop_service "bnetserver" "BattleNet Server"
	start_service "bnetserver" "BattleNet Server" "bnet"
	;;
  show)
	printf "${LIGHT_RED}CTRL+A, CTRL+D to quit whitout stopping Server${NC}\n"
	printf "${LIGHT_GREEN}Press any key to continue...${NC}\n"
	read -n1 -r
    screen -r "bnet"
	;;
         
  *)
	printf "Usage: $GREEN$0 $LIGHT_GREEN{start|stop|restart|show}$NC\n"
    exit 1
esac

tput cnorm
