custom: ["https://kdocs.cn/l/chBq7Z1jTdU8", "https://kdocs.cn/l/cspwUBM7pkBg"]
#github: [octocat, surftocat]
#patreon: octocat
#tidelift: npm/octo-package
#custom: ["https://www.paypal.me/octocat", octocat.com]







# These are supported funding model platforms

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#custom:["https://kdocs.cn/l/cspwUBM7pkBg","https://kdocs.cn/l/cspwUBM7pkBg"]
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
