-- quest 787 "The New Horde" completion text
-- UPDATE `quest_offer_reward` SET `RewardText`= "Another one of Eitrigg's recruits, hm?$B$BA sorry state of affairs we find ourselves in if this is the best the Horde can produce.  No matter.  By the time we think you're ready to leave the Valley, you'll be a proud warrior of the Horde." WHERE `ID`=787;
