DELETE FROM `script_texts` WHERE `npc_entry` IN (27316,27577);
INSERT INTO `script_texts` (`npc_entry`,`entry`,`content_default`,`content_loc1`,`content_loc2` ,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES
(27316,-1800041, 'Let''s you and I have a chat about some things,Godfrey.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800040, 'Return to Halford with the information the good mayor was kind enough to submit,$N,I will finish here and squeeze whatever else this wretch might know about Thel''zan. Now,I will show Godfrey the rarely shown "option three." ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800039, 'You let us worry about how we kill the bastard,Godfrey. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800036, 'What? There is a mausoleum beneath the old village? What fools we are to not have noticed. We will find and strike down your master now,Godfrey. We will end this nightmare. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800033, 'RUBBISH! Godfrey do you take me for a fool? Do not spew your Scourge propaganda at a man of the Light,heathen! Speak now or I will have the peasants craft a holy water bath and dip you into it like a dog with fleas! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800031, 'I thought you would see the Light,Godfrey... Now speak quickly,fiend. What does it say? ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800030, 'The power of the Lich King pales in comparison to the glory of the Light! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800029, 'LIGHT TAKE YOU,BEAST! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800027, 'LET THE LIGHT IN,GODFREY GODDARD! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800026, 'May the power of Light compel you! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800024, 'LET THE LIGHT IN,GODFREY GODDARD! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800023, 'Let the sermon begin.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800022, 'I say a prayer for you now,lost soul. May the Light take you gracefully. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800021, 'Then it is option two. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800016, 'Good,I have your attention,then,Godfrey? ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800015, 'GODFREY! Hear me,fiend! Hear me,for I am the Light,here to deliver you from evil! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800014, 'Stand back,$N,the beast might lash out and harm you. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27316,-1800017, 'We can do this in one of two ways,Godfrey. First,I will simply ask you to tell me what the unholy markings etched upon the pages of this tome mean. What say you? ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800038, 'You cannot stop Thel''zan! He bears the dark gift,bestowed upon him by the Lich King himself! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800037, 'How? Humans truly are stupid,yes? Thel''zan the Duskbringer! Thel''zan the Lich! He who is born of human flesh and bone,sacrificed all power,protected by the Lich King! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800035, 'Humans... Beneath the earth of Wintergarde Village you built a mausoleum! Why do you think Naxxramas attacked that spot? Thel''zan hides deep in your own crypt and sends a thousand-thousand corpses at you! Perish you will... ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800034, 'NOOOO!!! I tell you! I tell you everything! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800032, 'It tells of the coming apocalypse. How this world will burn and be reborn from death. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800028, 'Never felt hurt like this! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800025, 'IT BURNSSSSS! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800020, 'The book is your salvation,yes... but nothing will you know. NOTHING I SAY! NOTHING! ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800019, 'What can you do to me that Kel''Thuzad has not? That the Lich King will not? ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL),
(27577,-1800018, 'Tell you nothing,preacher. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL);
