-- 
-- UPDATE `gossip_menu_option` SET `OptionText`="Officer's Lounge", `OptionBroadcastTextID`=9749 WHERE `MenuID`=435 AND `OptionIndex`=10;
-- UPDATE `gossip_menu_option` SET `OptionText`="Officer's Lounge", `OptionBroadcastTextID`=9756 WHERE `MenuID`=1951 AND `OptionIndex`=9;
-- UPDATE `gossip_menu_option` SET `OptionText`="Zeppelin Master", `OptionBroadcastTextID`=5518 WHERE `MenuID`=1951 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Zeppelin Master", `OptionBroadcastTextID`=5518 WHERE `MenuID`=721 AND `OptionIndex`=12;
-- UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=7633 AND `OptionIndex`=7;
-- UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=1951 AND `OptionIndex`=7;
-- UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=7777 AND `OptionIndex`=7;
-- UPDATE `gossip_menu_option` SET `OptionText`="Weapon Master", `OptionBroadcastTextID`=7253 WHERE `MenuID`=721 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=721 AND `OptionIndex`=4;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=1951 AND `OptionIndex`=4;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=10043 AND `OptionIndex`=10;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=7777 AND `OptionIndex`=5;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=10265 AND `OptionIndex`=5;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=7633 AND `OptionIndex`=5;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=2352 AND `OptionIndex`=5;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8282 AND `OptionIndex`=4;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8357 AND `OptionIndex`=4;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=8419 AND `OptionIndex`=4;
-- UPDATE `gossip_menu_option` SET `OptionText`="Mailbox", `OptionBroadcastTextID`=4895 WHERE `MenuID`=2121 AND `OptionIndex`=6;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=2352 AND `OptionIndex`=3;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=8185 AND `OptionIndex`=1;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=435 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=10043 AND `OptionIndex`=7;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=3506 AND `OptionIndex`=2;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=7633 AND `OptionIndex`=3;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=2121 AND `OptionIndex`=4;
UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=3533 AND `OptionIndex`=2;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=10265 AND `OptionIndex`=3;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=721 AND `OptionIndex`=2;
UPDATE `gossip_menu_option` SET `OptionText`="The Guild Master & Vendor.", `OptionBroadcastTextID`=7072 WHERE `MenuID`=3580 AND `OptionIndex`=2;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=7777 AND `OptionIndex`=3;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=8129 AND `OptionIndex`=2;
-- UPDATE `gossip_menu_option` SET `OptionText`="Guild Master & Vendor", `OptionBroadcastTextID`=3428 WHERE `MenuID`=1951 AND `OptionIndex`=2;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8357 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8419 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=8282 AND `OptionIndex`=6;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=1951 AND `OptionIndex`=10;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=721 AND `OptionIndex`=8;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=2352 AND `OptionIndex`=7;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=435 AND `OptionIndex`=11;
UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=2121 AND `OptionIndex`=8;
-- UPDATE `gossip_menu_option` SET `OptionText`="Battlemaster", `OptionBroadcastTextID`=10359 WHERE `MenuID`=10265 AND `OptionIndex`=8;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=721 AND `OptionIndex`=5;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=2352 AND `OptionIndex`=0;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=435 AND `OptionIndex`=0;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=1951 AND `OptionIndex`=5;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=7633 AND `OptionIndex`=0;
UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=2121 AND `OptionIndex`=0;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=7777 AND `OptionIndex`=0;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=10043 AND `OptionIndex`=1;
-- UPDATE `gossip_menu_option` SET `OptionText`="Auction House", `OptionBroadcastTextID`=5316 WHERE `MenuID`=10265 AND `OptionIndex`=0;
DELETE FROM `npc_text`  WHERE `ID` IN (30000,30001);
UPDATE `gossip_menu_option` SET `OptionText`="Teach me the ways of the spirits.", `OptionBroadcastTextID`=7658 WHERE `MenuID`=5123 AND `OptionIndex`=0;
