-- DB update 2021_01_27_00 -> 2021_01_27_01
DROP PROCEDURE IF EXISTS `updateDb`;
DELIMITER //
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
SELECT COUNT(*) INTO @COLEXISTS
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'version_db_world' AND COLUMN_NAME = '2021_01_27_00';
IF @COLEXISTS = 0 THEN LEAVE proc; END IF;
START TRANSACTION;
ALTER TABLE version_db_world CHANGE COLUMN 2021_01_27_00 2021_01_27_01 bit;
SELECT sql_rev INTO OK FROM version_db_world WHERE sql_rev = '1609673885679254500'; IF OK <> 'FALSE' THEN LEAVE proc; END IF;
--
-- START UPDATING QUERIES
--

INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1609673885679254500');

DELETE FROM `quest_request_items_locale` WHERE `ID` IN (779, 795, 4104, 4106, 4107, 4109, 4111, 4112, 5063, 5067, 5068, 5218, 5221, 5224, 5227, 5406, 5508, 5509, 5510, 5883, 5886, 5888, 5891, 7791, 7796, 7801, 7806, 7812, 7814, 7817, 7819, 7822, 7825, 7826, 7827, 7831, 7832, 7834, 7835, 7837, 8080, 8154, 8155, 8156, 8297, 8420, 8522, 8523, 8996, 9082, 9083, 9084, 9114, 9115, 9116, 9178, 9179, 9181, 9182, 9183, 9184, 9185, 9186, 9187, 9188, 9190, 9191, 9194, 9195, 9196, 9197, 9198, 9200, 9201, 9202, 9203, 9204, 9205, 9206, 9208, 9209, 9210, 9330, 9331, 9332, 9935, 9936, 9939, 9940, 9967, 9970, 9972, 9977, 10182, 10283, 10305, 10306, 10307, 10358, 10363, 10472, 10473, 10474, 10475, 11031, 11032, 11033, 11034, 11103, 11104, 11105, 11106, 11933, 13697, 13719, 13721, 13722, 13748, 13754, 13759, 13852, 13856, 13857, 13858, 13859, 13860, 24849, 24851, 25055, 25092, 25180, 25181) AND `locale` = 'deDE';
INSERT INTO `quest_request_items_locale` (`ID`, `locale`, `CompletionText`, `VerifiedBuild`) VALUES
(779, 'deDE', 'Hier liegt das Siegel der Erde, mit drei eingelassenen Nischen für den Amethystrunenstein, den Opalrunenstein und den Diamantrunenstein.', 18019),
(795, 'deDE', 'Hier liegt das Siegel der Erde, mit drei eingelassenen Nischen für den Amethystrunenstein, den Opalrunenstein und den Diamantrunenstein.', 18019),
(4104, 'deDE', 'Wenn Ihr im Besitz eines cenarischen Leuchtfeuers seid, während Ihr im Teufelswald Bergbau betreibt, könnt Ihr das besudelte Vitriol sehen, von dem eine Ader Rohmetall verderbt wird. Ich weiß, wie man dieses Vitriol läutert und zu einem Reagenz verarbeitet, aus dem cenarische Pflanzensalbe hergestellt wird. Diese Salbe verwendet Ihr dann an Pflanzen, die Ihr draußen in der Wildnis findet und die gerettet werden müssen.$B$BWenn Ihr verderbtes Vitriol gesammelt habt, werde ich Euch etwas cenarische Pflanzensalbe geben, die ich bereits vorbereitet habe.', 18019),
(4106, 'deDE', 'Mit einem cenarischen Leuchtfeuer können gut ausgebildete Kürschner die Flecken besudelter Haut auf den im Teufelswald erbeuteten Fellen erkennen. Ich wandle diese scheinbar nutzlosen Flecken in eine dicke Paste um, mit der die cenarische Pflanzensalbe aktiviert wird. Wenn Ihr hier im Teufelswald Eure Beute häutet, dann solltet Ihr unbedingt immer ein Leuchtfeuer bei Euch haben.$B$BSobald Ihr besudelte Flecken gesammelt habt, bringt sie mir. Ich gebe Euch etwas cenarische Pflanzensalbe dafür, die ich bereits hergestellt habe.', 18019),
(4107, 'deDE', 'Die Macht eines entzauberten magischen Gegenstandes ist in der von ihm geschaffenen Essenz spürbar. Ich habe einen Weg gefunden, um die rohe Essenz, die von Verzauberern verwendet wird, in ein geeignetes Reagenz für die cenarische Pflanzensalbe umzuwandeln. Dazu braucht Ihr kein cenarisches Leuchtfeuer; jeder angemessen entzauberte Gegenstand, der geringe Netheressenzen abgibt, ist dafür geeignet.$B$BIch brauche nur eine einzige geringe Netheressenz; im Austausch dafür werde ich Euch cenarische Pflanzensalben geben. Die Essenz ist hochwirksam - ganz wenig davon genügt, um viel zu erreichen.', 18019),
(4109, 'deDE', 'Wenn Ihr im Besitz eines cenarischen Leuchtfeuers seid, während Ihr im Teufelswald Bergbau betreibt, könnt Ihr das besudelte Vitriol sehen, von dem eine Ader Rohmetall verderbt wird. Ich weiß, wie man dieses Vitriol läutert und zu einem Reagenz verarbeitet, aus dem cenarische Pflanzensalbe hergestellt wird. Diese Salbe verwendet Ihr dann an Pflanzen, die Ihr draußen in der Wildnis findet und die gerettet werden müssen.$B$BWenn Ihr verderbtes Vitriol gesammelt habt, werde ich Euch etwas cenarische Pflanzensalbe geben, die ich bereits vorbereitet habe.', 18019),
(4111, 'deDE', 'Mit einem cenarischen Leuchtfeuer können gut ausgebildete Kürschner die Flecken besudelter Haut auf den im Teufelswald erbeuteten Fellen erkennen. Ich wandle diese scheinbar nutzlosen Flecken in eine dicke Paste um, mit der die cenarische Pflanzensalbe aktiviert wird. Wenn Ihr hier im Teufelswald Eure Beute häutet, dann solltet Ihr unbedingt immer ein Leuchtfeuer bei Euch haben.$B$BSobald Ihr besudelte Flecken gesammelt habt, bringt sie mir. Ich gebe Euch etwas cenarische Pflanzensalbe dafür, die ich bereits hergestellt habe.', 18019),
(4112, 'deDE', 'Die Macht eines entzauberten magischen Gegenstandes ist in der von ihm geschaffenen Essenz spürbar. Ich habe einen Weg gefunden, um die rohe Essenz, die von Verzauberern verwendet wird, in ein geeignetes Reagenz für die cenarische Pflanzensalbe umzuwandeln. Dazu braucht Ihr kein cenarisches Leuchtfeuer; jeder angemessen entzauberte Gegenstand, der geringe Netheressenzen abgibt, ist dafür geeignet.$B$BIch brauche nur eine einzige geringe Netheressenz; im Austausch dafür werde ich Euch cenarische Pflanzensalben geben. Die Essenz ist hochwirksam - ganz wenig davon genügt, um viel zu erreichen.', 18019),
(5063, 'deDE', 'Bevor Ihr nicht alles habt was ich brauche verschwendet Ihr meine Zeit.', 18019),
(5067, 'deDE', 'Bevor Ihr nicht alles habt was ich brauche verschwendet Ihr meine Zeit.', 18019),
(5068, 'deDE', 'Bevor Ihr nicht alles habt was ich brauche verschwendet Ihr meine Zeit.', 18019),
(5218, 'deDE', 'Der Seuchenkessel der Geißel steht vor Euch und speit große Mengen Toxin in die Luft. Eine kleine, unauffällige Zugangsklappe befindet sich in der großen Plattform des Kessels.$B$BDa Ihr den Kessellord bereits besiegt und seinen Schlüssel an Euch genommen habt, könnt Ihr die geeigneten Reagenzien in den Kessel geben, um ein Gegenmittel gegen die Seuche zu schaffen.', 18019),
(5221, 'deDE', 'Der Seuchenkessel der Geißel steht vor Euch und speit große Mengen Toxin in die Luft. Eine kleine, unauffällige Zugangsklappe befindet sich in der großen Plattform des Kessels.$B$BDa Ihr den Kessellord bereits besiegt und seinen Schlüssel an Euch genommen habt, könnt Ihr die geeigneten Reagenzien in den Kessel geben, um ein Gegenmittel gegen die Seuche zu schaffen.', 18019),
(5224, 'deDE', 'Der Seuchenkessel der Geißel steht vor Euch und speit große Mengen Toxin in die Luft. Eine kleine, unauffällige Zugangsklappe befindet sich in der großen Plattform des Kessels.$B$BDa Ihr den Kessellord bereits besiegt und seinen Schlüssel an Euch genommen habt, könnt Ihr die geeigneten Reagenzien in den Kessel geben, um ein Gegenmittel gegen die Seuche zu schaffen.', 18019),
(5227, 'deDE', 'Der Seuchenkessel der Geißel steht vor Euch und speit große Mengen Toxin in die Luft. Eine kleine, unauffällige Zugangsklappe befindet sich in der großen Plattform des Kessels.$B$BDa Ihr den Kessellord bereits besiegt und seinen Schlüssel an Euch genommen habt, könnt Ihr die geeigneten Reagenzien in den Kessel geben, um ein Gegenmittel gegen die Seuche zu schaffen.', 18019),
(5406, 'deDE', 'Der Geißelstein des Verderbers ist die Insignie der Oberanführer der Geißel. Ein mächtiges Wesen, das eine Autoritätsposition über der Geißel innehat, wird immer einen besitzen. Eine solch bösartige Kreatur zu erschlagen, würde die Sache der Argentumdämmerung und alle guten Sachen sicherlich voranbringen!$B$BIm Namen der Argentumdämmerung werde ich Euch eine Ehrenmarke im Tausch für jeweils eine dieser Insignien geben. Seid vorsichtig, wenn Ihr diese Insignien holt, $N ... mit solch mächtigen Wesen ist nicht zu spaßen.', 18019),
(5508, 'deDE', 'Der Geißelstein des Verderbers ist die Insignie der Oberanführer der Geißel. Ein mächtiges Wesen, das eine Autoritätsposition über der Geißel innehat, wird immer einen besitzen. Eine solch bösartige Kreatur zu erschlagen, würde die Sache der Argentumdämmerung und alle guten Sachen sicherlich voranbringen!$B$BIm Namen der Argentumdämmerung werde ich Euch eine Ehrenmarke im Tausch für jeweils eine dieser Insignien geben. Seid vorsichtig, wenn Ihr diese Insignien holt, $N ... mit solch mächtigen Wesen ist nicht zu spaßen.', 18019),
(5509, 'deDE', 'Der Geißelstein des Eindringlings ist die Insignie der Elitetruppen der Geißel. Man findet sie manchmal bei den stärkeren Truppen, die in den Pestländern stationiert sind. Das Erschlagen einer solchen Kreatur ist wahrlich eine Herausforderung, aber eine, die jemand, der sich den Sieg über das Böse auf die Fahne geschrieben hat, mit Freude erfüllen sollte.$B$BDie Argentumdämmerung bietet derzeit eine Ehrenmarke im Tausch für zehn dieser Insignien. Bringt sie mir und ich werde sicherstellen, dass Ihr Eure gerechte Belohnung erhaltet.', 18019),
(5510, 'deDE', 'Der Geißelstein des Dieners ist die Insignie des Fußvolkes der Geißel. Man findet sie manchmal bei den schwächeren Truppen, die in den Pestländern stationiert sind, obwohl der Begriff ''schwächere'' natürlich relativ betrachtet werden muss. Die Geißel sollte, ganz gleich wo sie sich befindet, niemals unterschätzt werden.$B$BDie Argentumdämmerung bietet derzeit eine Ehrenmarke im Tausch für zwanzig dieser Insignien - ein Tausch, den ich freudig ausführe, vorausgesetzt, Ihr habt genug Geißelsteine!', 18019),
(5883, 'deDE', 'Wenn Ihr im Besitz eines cenarischen Leuchtfeuers seid, während Ihr im Teufelswald Bergbau betreibt, könnt Ihr das besudelte Vitriol sehen, von dem eine Ader Rohmetall verderbt wird. Ich weiß, wie man dieses Vitriol läutert und zu einem Reagenz verarbeitet, aus dem cenarische Pflanzensalbe hergestellt wird. Diese Salbe verwendet Ihr dann an Pflanzen, die Ihr draußen in der Wildnis findet und die gerettet werden müssen.$B$BWenn Ihr verderbtes Vitriol gesammelt habt, werde ich Euch etwas cenarische Pflanzensalbe geben, die ich bereits vorbereitet habe.', 18019),
(5886, 'deDE', 'Die Macht eines entzauberten magischen Gegenstandes ist in der von ihm geschaffenen Essenz spürbar. Ich habe einen Weg gefunden, um die rohe Essenz, die von Verzauberern verwendet wird, in ein geeignetes Reagenz für die cenarische Pflanzensalbe umzuwandeln. Dazu braucht Ihr kein cenarisches Leuchtfeuer; jeder angemessen entzauberte Gegenstand, der geringe Netheressenzen abgibt, ist dafür geeignet.$B$BIch brauche nur eine einzige geringe Netheressenz; im Austausch dafür werde ich Euch cenarische Pflanzensalben geben. Die Essenz ist hochwirksam - ganz wenig davon genügt, um viel zu erreichen.', 18019),
(5888, 'deDE', 'Wenn Ihr im Besitz eines cenarischen Leuchtfeuers seid, während Ihr im Teufelswald Bergbau betreibt, könnt Ihr das besudelte Vitriol sehen, von dem eine Ader Rohmetall verderbt wird. Ich weiß, wie man dieses Vitriol läutert und zu einem Reagenz verarbeitet, aus dem cenarische Pflanzensalbe hergestellt wird. Diese Salbe verwendet Ihr dann an Pflanzen, die Ihr draußen in der Wildnis findet und die gerettet werden müssen.$B$BWenn Ihr verderbtes Vitriol gesammelt habt, werde ich Euch etwas cenarische Pflanzensalbe geben, die ich bereits vorbereitet habe.', 18019),
(5891, 'deDE', 'Die Macht eines entzauberten magischen Gegenstandes ist in der von ihm geschaffenen Essenz spürbar. Ich habe einen Weg gefunden, um die rohe Essenz, die von Verzauberern verwendet wird, in ein geeignetes Reagenz für die cenarische Pflanzensalbe umzuwandeln. Dazu braucht Ihr kein cenarisches Leuchtfeuer; jeder angemessen entzauberte Gegenstand, der geringe Netheressenzen abgibt, ist dafür geeignet.$B$BIch brauche nur eine einzige geringe Netheressenz; im Austausch dafür werde ich Euch cenarische Pflanzensalben geben. Die Essenz ist hochwirksam - ganz wenig davon genügt, um viel zu erreichen.', 18019),
(7791, 'deDE', 'Wenn Ihr die 60 Stücke Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7796, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7801, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7806, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7812, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7814, 'deDE', 'Eine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern! Wenn Ihr die 60 Stücke Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7817, 'deDE', 'Wenn Ihr die 60 Stücke Magiestoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7819, 'deDE', 'Seid gegrüßt, $N! Wir benötigen auch weiterhin noch Runenstoff. Zusätzliche Mittel sind daher jederzeit willkommen, solltet Ihr welche entbehren können. Liefert Ihr uns eine weitere Spende von 20 Stück Runenstoff, so werde ich dafür sorgen, dass Ihr die gebührende Anerkennung für Eure anhaltenden Bemühungen gegenüber Unterstadt erhaltet.$B$BWann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7822, 'deDE', 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Donnerfels nicht unbeachtet bleiben würde!$B$BWenn Ihr die 60 Stücke Magiestoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7825, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7826, 'deDE', 'Wenn Ihr die 60 Stücke Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7827, 'deDE', 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzen zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern! Wenn Ihr die 60 Stücke Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7831, 'deDE', 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Orgrimmar nicht unbeachtet bleiben würde!$B$BWenn Ihr die 60 Stücke Magiestoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7832, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(7834, 'deDE', 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzen zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern! Wenn Ihr die 60 Stücke Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7835, 'deDE', 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit bei den Trollen der Dunkelspeere nicht unbeachtet bleiben würde!$B$BWenn Ihr die 60 Stücke Magiestoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.', 18019),
(7837, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(8080, 'deDE', 'Habt ihr die Rohstoffkiste, $N? Der Bund von Arathor kann ohne sie keine anständige Schlacht bestreiten…', 18019),
(8154, 'deDE', 'Habt ihr die Rohstoffkiste, $N? Der Bund von Arathor kann ohne sie keine anständige Schlacht bestreiten…', 18019),
(8155, 'deDE', 'Habt ihr die Rohstoffkiste, $N? Der Bund von Arathor kann ohne sie keine anständige Schlacht bestreiten…', 18019),
(8156, 'deDE', 'Habt ihr die Rohstoffkiste, $N? Der Bund von Arathor kann ohne sie keine anständige Schlacht bestreiten…', 18019),
(8297, 'deDE', 'Habt ihr die Rohstoffkiste, $N? Der Bund von Arathor kann ohne sie keine anständige Schlacht bestreiten…', 18019),
(8420, 'deDE', 'Habt Ihr meinen Teufelsstoff?', 18019),
(8522, 'deDE', 'Die Tage verstreichen und wir machen noch immer weiter. $C, habt Ihr die Runenstoffverbände?', 18019),
(8523, 'deDE', 'Wir treffen also erneut aufeinander, um wichtige Angelegenheiten zu besprechen, $C. Ich möchte Euch noch einmal für Eure bisherigen Bemühungen danken; nicht jeder ist so selbstlos wie Ihr. Es gibt jedoch noch mehr zu tun.$B$B$N, Würdet Ihr noch einmal Runenstoffverbände für mich sammeln gehen und sie dann zu mir bringen?', 18019),
(8996, 'deDE', '$N, Ihr seid lebendig zurückgekehrt! Dann ist ja wenigstens einer von uns noch am leben.$B$BIhr müsst mir unbedingt die ganze Geschichte erzählen!', 18019),
(9082, 'deDE', 'Wie soll ich irgendetwas ohne die von mir benötigten Gegenstände erledigen?', 18019),
(9083, 'deDE', 'Wie soll ich irgendetwas ohne die von mir benötigten Gegenstände erledigen?', 18019),
(9084, 'deDE', 'Wie soll ich irgendetwas ohne die von mir benötigten Gegenstände erledigen?', 18019),
(9114, 'deDE', 'Habt Ihr mir die Reagenzien gebracht, Kind?', 18019),
(9115, 'deDE', 'Habt Ihr mir die Reagenzien gebracht, Kind?', 18019),
(9116, 'deDE', 'Habt Ihr mir die Reagenzien gebracht, Kind?', 18019),
(9178, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9179, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9181, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9182, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9183, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9184, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9185, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9186, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9187, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9188, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9190, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9191, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9194, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9195, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9196, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9197, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9198, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9200, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9201, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9202, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9203, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9204, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9205, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9206, 'deDE', 'Einen Arbeitsauftrag ausführen, $C?', 18019),
(9208, 'deDE', 'Habt Ihr das Arkanum?', 18019),
(9209, 'deDE', 'Habt Ihr das Arkanum?', 18019),
(9210, 'deDE', 'Habt Ihr das Arkanum?', 18019),
(9330, 'deDE', 'Ihr glüht ja förmlich, $R. Was habt Ihr da?', 18019),
(9331, 'deDE', 'Ihr glüht ja förmlich, $R. Was habt Ihr da?', 18019),
(9332, 'deDE', 'Ihr glüht ja förmlich, $R. Was habt Ihr da?', 18019),
(9935, 'deDE', 'Seid Ihr hier um Eure Belohnung einzufordern?', 18019),
(9936, 'deDE', 'Seid Ihr hier um Eure Belohnung einzufordern?', 18019),
(9939, 'deDE', 'Seid Ihr hier um Eure Belohnung einzufordern?', 18019),
(9940, 'deDE', 'Seid Ihr hier um Eure Belohnung einzufordern?', 18019),
(9967, 'deDE', 'Der Kampf ist vorbei wenn Ihr oder Euer Gegner tot am Boden liegt.', 18019),
(9970, 'deDE', 'Der Kampf ist vorbei wenn Ihr oder Euer Gegner tot am Boden liegt.', 18019),
(9972, 'deDE', 'Der Kampf ist vorbei wenn Ihr oder Euer Gegner tot am Boden liegt.', 18019),
(9977, 'deDE', 'Der Kampf ist vorbei wenn Ihr oder Euer Gegner tot am Boden liegt.', 18019),
(10182, 'deDE', 'Was habt Ihr gefunden, $N?', 18019),
(10283, 'deDE', 'Wer seid Ihr?', 18019),
(10305, 'deDE', 'Was habt Ihr gefunden, $N?', 18019),
(10306, 'deDE', 'Was habt Ihr gefunden, $N?', 18019),
(10307, 'deDE', 'Was habt Ihr gefunden, $N?', 18019),
(10358, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(10363, 'deDE', 'Wann auch immer Ihr die erforderte Menge abgeben könnt, ich werde sie jederzeit entgegennehmen.', 18019),
(10472, 'deDE', 'Möge die Zeit immer mit Euch sein, $N.', 18019),
(10473, 'deDE', 'Möge die Zeit immer mit Euch sein, $N.', 18019),
(10474, 'deDE', 'Möge die Zeit immer mit Euch sein, $N.', 18019),
(10475, 'deDE', 'Möge die Zeit immer mit Euch sein, $N.', 18019),
(11031, 'deDE', 'Ihr habt Euch gegen Eure bisherige Wahl entschieden? Ich nehme an ich kann Euch helfen es rückgängig zu machen. Letztendlich ist Dalaran Eure Loyalität wichtiger als die Art und Weise wie Ihr sie zeigen wollt. Es wird nicht billig werden. Und natürlich brauche ich Euren alten Ring zurück.', 18019),
(11032, 'deDE', 'Ihr habt Euch gegen Eure bisherige Wahl entschieden? Ich nehme an ich kann Euch helfen es rückgängig zu machen. Letztendlich ist Dalaran Eure Loyalität wichtiger als die Art und Weise wie Ihr sie zeigen wollt. Es wird nicht billig werden. Und natürlich brauche ich Euren alten Ring zurück.', 18019),
(11033, 'deDE', 'Ihr habt Euch gegen Eure bisherige Wahl entschieden? Ich nehme an ich kann Euch helfen es rückgängig zu machen. Letztendlich ist Dalaran Eure Loyalität wichtiger als die Art und Weise wie Ihr sie zeigen wollt. Es wird nicht billig werden. Und natürlich brauche ich Euren alten Ring zurück.', 18019),
(11034, 'deDE', 'Ihr habt Euch gegen Eure bisherige Wahl entschieden? Ich nehme an ich kann Euch helfen es rückgängig zu machen. Letztendlich ist Dalaran Eure Loyalität wichtiger als die Art und Weise wie Ihr sie zeigen wollt. Es wird nicht billig werden. Und natürlich brauche ich Euren alten Ring zurück.', 18019),
(11103, 'deDE', 'Man kann die Kräfte Eures Ringes neu formen, doch wird es nicht einfach, Eure Auswahl rückgängig zu machen. Seid Ihr sicher, dass Ihr seine momentane Form durch eine andere ersetzen möchtet?', 18019),
(11104, 'deDE', 'Man kann die Kräfte Eures Ringes neu formen, doch wird es nicht einfach, Eure Auswahl rückgängig zu machen. Seid Ihr sicher, dass Ihr seine momentane Form durch eine andere ersetzen möchtet?', 18019),
(11105, 'deDE', 'Man kann die Kräfte Eures Ringes neu formen, doch wird es nicht einfach, Eure Auswahl rückgängig zu machen. Seid Ihr sicher, dass Ihr seine momentane Form durch eine andere ersetzen möchtet?', 18019),
(11106, 'deDE', 'Man kann die Kräfte Eures Ringes neu formen, doch wird es nicht einfach, Eure Auswahl rückgängig zu machen. Seid Ihr sicher, dass Ihr seine momentane Form durch eine andere ersetzen möchtet?', 18019),
(11933, 'deDE', 'Ihr glüht ja förmlich, $R. Was habt Ihr da?', 18019),
(13697, 'deDE', 'Seid Ihr bereit zu zeigen, wie gut Ihr die Fähigkeiten des Recken beherrscht?', 18019),
(13719, 'deDE', 'Seid Ihr bereit zu zeigen, wie gut Ihr die Fähigkeiten des Recken beherrscht?', 18019),
(13721, 'deDE', 'Seid Ihr bereit zu zeigen, wie gut Ihr die Fähigkeiten des Recken beherrscht?', 18019),
(13722, 'deDE', 'Seid Ihr bereit zu zeigen, wie gut Ihr die Fähigkeiten des Recken beherrscht?', 18019),
(13748, 'deDE', 'Habt Ihr die Klinge ergattert?', 18019),
(13754, 'deDE', 'Habt Ihr die Klinge ergattert?', 18019),
(13759, 'deDE', 'Habt Ihr die Klinge ergattert?', 18019),
(13852, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(13856, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(13857, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(13858, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(13859, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(13860, 'deDE', 'Habt Ihr an der Seite der Kreuzfahrer im Hof der Knochen gedient?', 18019),
(24849, 'deDE', 'Wer seid Ihr?', 18019),
(24851, 'deDE', 'Wer seid Ihr?', 18019),
(25055, 'deDE', 'Habt Ihr die Elemente schon gebändigt?', 18019),
(25092, 'deDE', 'Habt Ihr die Elemente schon gebändigt?', 18019),
(25180, 'deDE', 'Habt Ihr Euch mit dem Kurier getroffen?', 18019),
(25181, 'deDE', 'Habt Ihr Euch mit dem Kurier getroffen?', 18019);

--
-- END UPDATING QUERIES
--
COMMIT;
END //
DELIMITER ;
CALL updateDb();
DROP PROCEDURE IF EXISTS `updateDb`;
