UPDATE `creature_template` SET `ScriptName`='boss_kintara' WHERE (`entry`='162059');
UPDATE `areatrigger_template` SET `ScriptName`='at_ionized_plasma' WHERE (`Id`='23887');
UPDATE `creature_template` SET `ScriptName`='npc_azules' WHERE (`entry`='163077');
UPDATE `areatrigger_template` SET `ScriptName`='at_attenuated_barrage' WHERE (`Id`='23839');
UPDATE `creature_template` SET `ScriptName`='boss_ventunax' WHERE (`entry`='162058');
UPDATE `creature_template` SET `ScriptName`='npc_shadowhirl' WHERE (`entry`='166136');
UPDATE `areatrigger_template` SET `ScriptName`='at_dark_bolt' WHERE (`Id`='23813');
UPDATE `creature_template` SET `ScriptName`='npc_shadowhirl' WHERE (`entry`='166152');
UPDATE `creature_template` SET `minlevel`='60', `maxlevel`='61' WHERE (`entry`='166136');
UPDATE `creature_template` SET `minlevel`='60', `maxlevel`='61' WHERE (`entry`='166152');
UPDATE `creature_template` SET `HealthModifier`='100' WHERE (`entry`='166136');
UPDATE `creature_template` SET `HealthModifier`='100' WHERE (`entry`='166152');
UPDATE `creature_template` SET `flags_extra`='1073741824' WHERE (`entry`='166136');
UPDATE `creature_template` SET `flags_extra`='1073741824' WHERE (`entry`='166152');
UPDATE `creature_template` SET `ScriptName`='boss_oryphrion' WHERE (`entry`='162060');
UPDATE `creature_template` SET `ScriptName`='npc_coalesced_anima' WHERE (`entry`='165807');
UPDATE `areatrigger_template` SET `ScriptName`='at_anima_field' WHERE (`Id`='23858');
UPDATE `creature_template` SET `ScriptName`='boss_devos' WHERE (`entry`='162061');
UPDATE `areatrigger_template` SET `ScriptName`='at_lingering_doubt' WHERE (`Id`='23641');
UPDATE `creature_template` SET `ScriptName`='boss_doctor_ickus' WHERE (`entry`='164967');
UPDATE `creature_template` SET `unit_flags`='768', `flags_extra`='128' WHERE (`entry`='173930');
UPDATE `creature_template` SET `unit_flags`='768', `flags_extra`='128' WHERE (`entry`='165532');
UPDATE `creature_template` SET `ScriptName`='boss_domina_venomblade' WHERE (`entry`='164266');
UPDATE `creature_template` SET `ScriptName`='boss_margrave_stradama' WHERE (`entry`='164267');
UPDATE `creature_template` SET `ScriptName`='npc_winged_champion' WHERE (`entry`='168185');
