ALTER TABLE `rbac_permissions` ADD COLUMN `help` LONGTEXT NULL COMMENT 'Permission help' AFTER `name`; 

UPDATE `rbac_permissions` SET `help` = 'Syntax: .rbac account list [$account]\n\nView permissions of selected player or given account\nNote: Only those that affect current realm' WHERE `id` = '202';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .rbac account grant [$account] #id [#realmId]\n\nGrant a permission to selected player or given account.\n\n#reamID may be -1 for all realms.' WHERE `id` = '203';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .rbac account deny [$account] #id [#realmId]\n\nDeny a permission to selected player or given account.\n\n#reamID may be -1 for all realms.' WHERE `id` = '204';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .rbac account revoke [$account] #id\n\nRemove a permission from an account\n\nNote: Removes the permission from granted or denied permissions' WHERE `id` = '205';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .rbac list [$id]\n\nView list of all permissions. If $id is given will show only info for that permission.' WHERE `id` = '206';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account\r\n\r\nDisplay the access level of your account and the email adress if you possess the necessary permissions.' WHERE `id` = '217';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account addon #addon\nSet expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.' WHERE `id` = '218';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account create $account $password\r\n\r\nCreate account and set password to it.' WHERE `id` = '219';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account delete $account\r\n\r\nDelete account with all characters.' WHERE `id` = '220';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account lock country [on|off]\nAllow login from account only from current used Country or remove this requirement.' WHERE `id` = '222';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account lock ip [on|off]\nAllow login from account only from current used IP or remove this requirement.' WHERE `id` = '223';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account onlinelist\r\n\r\nShow list of online accounts.' WHERE `id` = '224';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account password $old_password $new_password $new_password [$email]\r\n\r\nChange your account password. You may need to check the actual security mode to see if email input is necessary.' WHERE `id` = '225';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set $subcommand\nType .account set to see the list of possible subcommands or .help account set $subcommand to see info on subcommands' WHERE `id` = '226';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set addon [$account] #addon\r\n\r\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.' WHERE `id` = '227';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set gmlevel [$account] #level [#realmid]\r\n\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level on the realm #realmID.\r\n\r\n#level may range from 0 to 3.\r\n\r\n#reamID may be -1 for all realms.' WHERE `id` = '228';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set password $account $password $password\r\n\r\nSet password for account.' WHERE `id` = '229';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .achievement $subcommand\nType .achievement to see the list of possible subcommands or .help achievement $subcommand to see info on subcommands' WHERE `id` = '230';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .achievement add $achievement\nAdd an achievement to the targeted player.\n$achievement: can be either achievement id or achievement link' WHERE `id` = '231';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena captain #TeamID $name\n\nA command to set new captain to the team $name must be in the team' WHERE `id` = '233';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena create $name \"arena name\" #type\n\nA command to create a new Arena-team in game. #type  = [2/3/5]' WHERE `id` = '234';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena disband #TeamID\n\nA command to disband Arena-team in game.' WHERE `id` = '235';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena info #TeamID\n\nA command that show info about arena team' WHERE `id` = '236';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena lookup $name\n\nA command that give a list of arenateam with the given $name' WHERE `id` = '237';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .arena rename \"oldname\" \"newname\"\n\nA command to rename Arena-team name.' WHERE `id` = '238';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ban $subcommand\nType .ban to see the list of possible subcommands or .help ban $subcommand to see info on subcommands' WHERE `id` = '239';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".' WHERE `id` = '240';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ban character $Name $bantime $reason\nBan character and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".' WHERE `id` = '241';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".' WHERE `id` = '242';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ban playeraccount $Name $bantime $reason\nBan account and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".' WHERE `id` = '243';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .baninfo $subcommand\nType .baninfo to see the list of possible subcommands or .help baninfo $subcommand to see info on subcommands' WHERE `id` = '244';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban.' WHERE `id` = '245';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban.' WHERE `id` = '246';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban.' WHERE `id` = '247';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .banlist $subcommand\nType .banlist to see the list of possible subcommands or .help banlist $subcommand to see info on subcommands' WHERE `id` = '248';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.' WHERE `id` = '249';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required.' WHERE `id` = '250';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.' WHERE `id` = '251';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unban $subcommand\nType .unban to see the list of possible subcommands or .help unban $subcommand to see info on subcommands' WHERE `id` = '252';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unban account $Name\r\nUnban accounts for account name pattern.' WHERE `id` = '253';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unban character $Name\r\nUnban accounts for character name pattern.' WHERE `id` = '254';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unban ip $Ip\r\nUnban accounts for IP pattern.' WHERE `id` = '255';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bf start #battleid' WHERE `id` = '258';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bf stop #battleid' WHERE `id` = '259';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bf switch #battleid' WHERE `id` = '260';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bf timer #battleid #timer' WHERE `id` = '261';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bf enable #battleid' WHERE `id` = '262';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account email $oldemail $currentpassword $newemail $newemailconfirmation\r\n\r\n Change your account email. You may need to check the actual security mode to see if email input is necessary for password change' WHERE `id` = '263';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set sec email $accountname $email $emailconfirmation\r\n\r\nSet the email for entered player account.' WHERE `id` = '265';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .account set sec regmail $account $regmail $regmailconfirmation\r\n\r\nSets the regmail for entered player account.' WHERE `id` = '266';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast #spellid [triggered]\r\n  Cast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.' WHERE `id` = '267';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast back #spellid [triggered]\r\n  Selected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.' WHERE `id` = '268';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast dist #spellid [#dist [triggered]]\r\n  You will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.' WHERE `id` = '269';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.' WHERE `id` = '270';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast target #spellid [triggered]\r\n  Selected target will cast #spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag.' WHERE `id` = '271';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cast dest #spellid #x #y #z [triggered]\r\n  Selected target will cast #spellid at provided destination. If \'trigered\' or part provided then spell casted with triggered flag.' WHERE `id` = '272';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character customize [$name]\r\n\r\nMark selected in game or by $name in command character for customize at next login.' WHERE `id` = '274';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character changefaction $name\r\n\r\nChange character faction.' WHERE `id` = '275';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character changerace $name\r\n\r\nChange character race.' WHERE `id` = '276';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character deleted list [#guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if #guid is supplied, only the character with that GUID will be selected.' WHERE `id` = '279';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character deleted restore #guid|$name [$newname] [#new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If #newaccount is set, the character will be restored to specific account character list. This works only with one character!' WHERE `id` = '280';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character level [$playername] [#level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.' WHERE `id` = '283';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character rename [$name] [$newName] \n\nMark selected in game or by $name in command character for rename at next login.\n\nIf $newName then the player will be forced rename.' WHERE `id` = '284';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character reputation [$player_name]\r\n\r\nShow reputation information for selected player or player find by $player_name.' WHERE `id` = '285';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .character titles [$player_name]\r\n\r\nShow known titles list for selected player or player find by $player_name.' WHERE `id` = '286';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.' WHERE `id` = '287';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pdump $subcommand\nType .pdump to see the list of possible subcommands or .help pdump $subcommand to see info on subcommands' WHERE `id` = '288';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid.' WHERE `id` = '289';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename.' WHERE `id` = '290';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat $subcommand\r\nType .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands' WHERE `id` = '291';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat casttime [on/off]\r\nEnables or disables your character\'s spell cast times.' WHERE `id` = '292';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat cooldown [on/off]\r\nEnables or disables your character\'s spell cooldowns.' WHERE `id` = '293';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat explore #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.' WHERE `id` = '294';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat god [on/off]\r\nEnables or disables your character\'s ability to take damage.' WHERE `id` = '295';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat power [on/off]\r\nEnables or disables your character\'s spell cost (e.g mana).' WHERE `id` = '296';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat status \n\nShows the cheats you currently have enabled.' WHERE `id` = '297';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat taxi on/off\r\nTemporary grant access or remove to all taxi routes for the selected character.\r\n If no character is selected, hide or reveal all routes to you.Visited taxi nodes sill accessible after removing access.' WHERE `id` = '298';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cheat waterwalk on/off\r\nSet on/off waterwalk state for selected player or self if no player selected.' WHERE `id` = '299';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug $subcommand\nType .debug to see the list of possible subcommands or .help debug $subcommand to see info on subcommands' WHERE `id` = '300';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug areatriggers\nToggle debug mode for areatriggers. In debug mode GM will be notified if reaching an areatrigger' WHERE `id` = '302';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug arena\r\n\r\nToggle debug mode for arenas. In debug mode GM can start arena with single player.' WHERE `id` = '303';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.' WHERE `id` = '304';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug Mod32Value #field #value\r\n\r\nAdd #value to field #field of your character.' WHERE `id` = '313';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug moveflags [$newMoveFlags [$newMoveFlags2]]\r\nNo params given will output the current moveflags of the target' WHERE `id` = '314';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug play cinematic #cinematicid\r\n\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.\r\n' WHERE `id` = '316';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug play movie #movieid\r\n\r\nPlay movie #movieid for you.' WHERE `id` = '317';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug play sound #soundid\r\n\r\nPlay sound with #soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...' WHERE `id` = '318';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wpgps\n\nOutput current position to sql developer log as partial SQL query to be used in pathing' WHERE `id` = '340';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .deserter bg add $time \n\n Adds the bg deserter debuff to your target with $time duration.' WHERE `id` = '343';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .deserter bg remove \n\n Removes the bg deserter debuff from your target.' WHERE `id` = '344';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .deserter instance add $time \n\n Adds the instance deserter debuff to your target with $time duration.' WHERE `id` = '346';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .deserter instance remove \n\n Removes the instance deserter debuff from your target.' WHERE `id` = '347';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add achievement_criteria $entry $flag $comment' WHERE `id` = '350';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add battleground $entry $flag $comment' WHERE `id` = '351';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add map $entry $flag $comment' WHERE `id` = '352';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add mmap $entry $flag $comment' WHERE `id` = '353';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add outdoorpvp $entry $flag $comment' WHERE `id` = '354';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add quest $entry $flag $comment' WHERE `id` = '355';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add spell $entry $flag $comment' WHERE `id` = '356';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable add vmap $entry $flag $comment' WHERE `id` = '357';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove achievement_criteria $entry' WHERE `id` = '359';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove battleground $entry' WHERE `id` = '360';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove map $entry' WHERE `id` = '361';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove mmap $entry' WHERE `id` = '362';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove outdoorpvp $entry' WHERE `id` = '363';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove quest $entry' WHERE `id` = '364';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove spell $entry' WHERE `id` = '365';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .disable remove vmap $entry' WHERE `id` = '366';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .event #event_id\r\nShow details about event with #event_id.' WHERE `id` = '367';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .event activelist\r\nShow list of currently active events.' WHERE `id` = '368';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).' WHERE `id` = '369';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).' WHERE `id` = '370';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided.' WHERE `id` = '371';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided.' WHERE `id` = '372';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm fly [on/off]\r\nEnable/disable gm fly mode.' WHERE `id` = '373';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters.' WHERE `id` = '374';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels.' WHERE `id` = '375';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gm visible on/off\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.' WHERE `id` = '376';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go $subcommand\nType .go to see the list of possible subcommands or .help go $subcommand to see info on subcommands' WHERE `id` = '377';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.' WHERE `id` = '378';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.' WHERE `id` = '379';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).' WHERE `id` = '380';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid' WHERE `id` = '381';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go taxinode #taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart' WHERE `id` = '382';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.' WHERE `id` = '383';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go trigger #trigger_id\r\n\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.' WHERE `id` = '384';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go xyz #x #y [#z [#mapid [#orientation]]]\r\n\r\nTeleport player to point with (#x,#y,#z) coordinates at map #mapid with orientation #orientation. If z is not provided, ground/water level will be used. If mapid is not provided, the current map will be used. If #orientation is not provided, the current orientation will be used.' WHERE `id` = '385';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart' WHERE `id` = '386';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject $subcommand\nType .gobject to see the list of possible subcommands or .help gobject $subcommand to see info on subcommands' WHERE `id` = '387';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject activate #guid\r\n\r\nActivates an object like a door or a button.' WHERE `id` = '388';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject add #id <spawntimeSecs>\r\n\r\nAdd a game object from game object templates to the world at your current location using the #id.\r\nspawntimesecs sets the spawntime, it is optional.\r\n\r\nNote: this is a copy of .gameobject.' WHERE `id` = '389';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject add temp #id\r\n\r\nAdds a temporary gameobject that is not saved to DB.' WHERE `id` = '390';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.' WHERE `id` = '391';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject info [$object_entry]\r \r Query Gameobject information for selected gameobject or given entry.' WHERE `id` = '392';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).' WHERE `id` = '393';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject near  [#distance]\r\n\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.' WHERE `id` = '394';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject set phase #guid #phasemask\r\n\r\nGameobject with DB guid #guid phasemask changed to #phasemask with related world vision update for players. Gameobject state saved to DB and persistent.' WHERE `id` = '396';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.' WHERE `id` = '398';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gobject turn #goguid \r\n\r\nSet for gameobject #goguid orientation same as current character orientation.' WHERE `id` = '399';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .debug transport [start/stop]\r\n\r\n Allows to stop a transport at its nearest wait point and start movement of a stopped one. Not all transports can be started or stopped.' WHERE `id` = '400';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild $subcommand\nType .guild to see the list of possible subcommands or .help guild $subcommand to see info on subcommands' WHERE `id` = '401';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild create [$GuildLeaderName] \"$GuildName\"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes.' WHERE `id` = '402';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild delete \"$GuildName\"\r\n\r\nDelete guild $GuildName. Guild name must in quotes.' WHERE `id` = '403';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild invite [$CharacterName] \"$GuildName\"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes.' WHERE `id` = '404';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild.' WHERE `id` = '405';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild rank [$CharacterName] #Rank\r\n\r\nSet for player $CharacterName (or selected) rank #Rank in a guild.' WHERE `id` = '406';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guild rename \"$GuildName\" \"$NewGuildName\" \n\n Rename a guild named $GuildName with $NewGuildName. Guild name and new guild name must in quotes.' WHERE `id` = '407';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .honor $subcommand\nType .honor to see the list of possible subcommands or .help honor $subcommand to see info on subcommands' WHERE `id` = '408';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained today) to the selected player.' WHERE `id` = '409';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .honor add kill\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)' WHERE `id` = '410';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .honor update\r\n\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.' WHERE `id` = '411';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .instance $subcommand\nType .instance to see the list of possible subcommands or .help instance $subcommand to see info on subcommands' WHERE `id` = '412';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .instance listbinds\r\n  Lists the binds of the selected player.' WHERE `id` = '413';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .instance unbind <mapid|all> [difficulty]\r\n  Clear all/some of player\'s binds' WHERE `id` = '414';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .instance stats\r\n  Shows statistics about instances.' WHERE `id` = '415';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB.' WHERE `id` = '416';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn #spell [all]\r\n\r\nSelected character learn a spell of id #spell. If \'all\' provided then all ranks learned.' WHERE `id` = '417';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all my class\r\n\r\nLearn all spells and talents available for his class.' WHERE `id` = '420';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all my pettalents\r\n\r\nLearn all talents for your pet available for his creature type (only for hunter pets).' WHERE `id` = '421';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all my spells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.' WHERE `id` = '422';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all my talents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class.' WHERE `id` = '423';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all gm\r\n\r\nLearn all default spells for Game Masters.' WHERE `id` = '424';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn crafts\r\n\r\nLearn all professions and recipes.' WHERE `id` = '425';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.' WHERE `id` = '426';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all lang\r\n\r\nLearn all languages' WHERE `id` = '427';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .learn all recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all recipes enchanting' WHERE `id` = '428';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unlearn #spell [all]\r\n\r\nUnlearn for selected player a spell #spell.  If \'all\' provided then all ranks unlearned.' WHERE `id` = '429';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lfg player\n Shows information about player (state, roles, comment, dungeons selected).' WHERE `id` = '431';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lfg group\n Shows information about all players in the group  (state, roles, comment, dungeons selected).' WHERE `id` = '432';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lfg queue\n Shows info about current lfg queues.' WHERE `id` = '433';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .flg clean\n Cleans current queue, only for debugging purposes.' WHERE `id` = '434';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lfg options [new value]\n Shows current lfg options. New value is set if extra param is present.' WHERE `id` = '435';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list $subcommand\nType .list to see the list of possible subcommands or .help list $subcommand to see info on subcommands' WHERE `id` = '436';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list creature #creature_id [#max_count]\r\n\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.' WHERE `id` = '437';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list item #item_id [#max_count]\r\n\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.' WHERE `id` = '438';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list object #gameobject_id [#max_count]\r\n\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.' WHERE `id` = '439';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list auras\nList auras (passive and active) of selected creature or player. If no creature or player is selected, list your own auras.' WHERE `id` = '440';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .list mail $character\nList of mails the character received.' WHERE `id` = '441';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup $subcommand\nType .lookup to see the list of possible subcommands or .help lookup $subcommand to see info on subcommands' WHERE `id` = '442';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.' WHERE `id` = '443';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.' WHERE `id` = '444';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.' WHERE `id` = '445';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.' WHERE `id` = '446';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.' WHERE `id` = '447';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.' WHERE `id` = '448';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.' WHERE `id` = '449';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.' WHERE `id` = '450';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup player ip $ip ($limit) \r\n\r\n Searchs players, which account ast_ip is $ip with optional parametr $limit of results.' WHERE `id` = '452';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup player account $account ($limit) \r\n\r\n Searchs players, which account username is $account with optional parametr $limit of results.' WHERE `id` = '453';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup player email $email ($limit) \r\n\r\n Searchs players, which account email is $email with optional parametr $limit of results.' WHERE `id` = '454';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.' WHERE `id` = '455';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.' WHERE `id` = '456';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup spell id #spellid\n\nLooks up a spell by #spellid, and returns the match with its spell name.' WHERE `id` = '457';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name.' WHERE `id` = '458';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name.' WHERE `id` = '459';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup title $$namepart\r\n\r\nLooks up a title by $namepart, and returns all matches with their title ID\'s and index\'s.' WHERE `id` = '460';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .lookup map $namepart\r\n\r\nLooks up a map by $namepart, and returns all matches with their map ID\'s.' WHERE `id` = '461';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log.' WHERE `id` = '462';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .channel set ownership $channel [on/off]\n\nGrant ownership to the first person that joins the channel.' WHERE `id` = '465';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gmannounce $announcement\r\nSend an announcement to online Gamemasters.' WHERE `id` = '466';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gmnameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.' WHERE `id` = '467';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gmnotify $notification\r\nDisplays a notification on the screen of all online GM\'s.' WHERE `id` = '468';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .nameannounce $announcement.\nSend an announcement to all online players, displaying the name of the sender.' WHERE `id` = '469';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen.' WHERE `id` = '470';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.' WHERE `id` = '471';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group $subcommand\nType .group to see the list of possible subcommands or .help group $subcommand to see info on subcommands' WHERE `id` = '472';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group leader [$characterName]\n\nSets the given character as his group\'s leader.' WHERE `id` = '473';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group disband [$characterName]\n\nDisbands the given character\'s group.' WHERE `id` = '474';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group remove [$characterName]\n\nRemoves the given character from his group.' WHERE `id` = '475';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group join $AnyCharacterNameFromGroup [$CharacterName] \r\nAdds to group of player $AnyCharacterNameFromGroup player $CharacterName (or selected).' WHERE `id` = '476';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group list [$CharacterName] \r\nLists all the members of the group/party the player is in.' WHERE `id` = '477';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .group summon [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline.' WHERE `id` = '478';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pet $subcommand\nType .pet to see the list of possible subcommands or .help pet $subcommand to see info on subcommands' WHERE `id` = '479';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pet create\r\n\r\nCreates a pet of the selected creature.' WHERE `id` = '480';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pet learn\r\n\r\nLearn #spellid to pet.' WHERE `id` = '481';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pet unlean\r\n\r\nunLearn #spellid to pet.' WHERE `id` = '482';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .send items #playername \"#subject\" \"#text\" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.' WHERE `id` = '484';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .send mail #playername \"#subject\" \"#text\"\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\".' WHERE `id` = '485';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR.' WHERE `id` = '486';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .send money #playername \"#subject\" \"#text\" #money\r\n\r\nSend mail with money to a player. Subject and mail text must be in \"\".' WHERE `id` = '487';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\n\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added.\r\n.' WHERE `id` = '488';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .additemset #itemsetid\r\n\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.' WHERE `id` = '489';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .appear [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait,e.g. when you are in a group. Character can be offline.' WHERE `id` = '490';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .aura #spellid\r\n\r\nAdd the aura from spell #spellid to the selected Unit.' WHERE `id` = '491';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bank\r\n\r\nShow your bank inventory.' WHERE `id` = '492';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .bindsight\r\n\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.' WHERE `id` = '493';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.' WHERE `id` = '494';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cometome $parameter\nMake selected creature come to your current location (new position not saved to DB).' WHERE `id` = '495';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level.' WHERE `id` = '496';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .cooldown [#spell_id]\r\n\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).' WHERE `id` = '497';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.' WHERE `id` = '498';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .dev [on/off]\r\n\r\nEnable or Disable in game Dev tag or show current state if on/off not provided.' WHERE `id` = '499';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you.' WHERE `id` = '500';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .dismount\r\n\r\nDismount you, if you are mounted.' WHERE `id` = '501';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .distance\r\n\r\nDisplay the distance from your character to the selected creature.' WHERE `id` = '502';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .flusharenapoints\r\n\r\nUse it to distribute arena points based on arena team ratings, and start a new week.' WHERE `id` = '503';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .freeze (#player)\r\n\"Freezes\" #player and disables his chat. When using this without #name it will freeze your target.' WHERE `id` = '504';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id' WHERE `id` = '505';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .guid\r\n\r\nDisplay the GUID for the selected character.' WHERE `id` = '506';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.' WHERE `id` = '507';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .hidearea #areaid\r\n\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.' WHERE `id` = '508';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .itemmove #sourceslotid #destinationslotid\r\n\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\n\r\nNot yet implemented' WHERE `id` = '509';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .kick [$charactername] [$reason]\r\n\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is \"No Reason\".' WHERE `id` = '510';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).' WHERE `id` = '511';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .listfreeze\r\n\r\nSearch and output all frozen players.' WHERE `id` = '512';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.' WHERE `id` = '513';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .movegens\r\n  Show movement generators stack for selected creature or player.' WHERE `id` = '514';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.' WHERE `id` = '515';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).' WHERE `id` = '516';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .pinfo [$player_name/#GUID]\r\n\r\nOutput account information and guild information for selected player or player find by $player_name or #GUID.' WHERE `id` = '517';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .playall #soundid\r\n\r\nPlayer a sound to whole server.' WHERE `id` = '518';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .possess\r\n\r\nPossesses indefinitely the selected creature.' WHERE `id` = '519';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .recall [$playername]\r\n\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.' WHERE `id` = '520';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .repairitems\r\n\r\nRepair all selected player\'s items.' WHERE `id` = '521';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .respawn\r\n\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.' WHERE `id` = '522';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you.' WHERE `id` = '523';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .saveall\r\n\r\nSave all characters in game.' WHERE `id` = '524';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .save\r\n\r\nSaves your character.' WHERE `id` = '525';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .setskill #skill #level [#max]\r\n\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.' WHERE `id` = '526';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .showarea #areaid\r\n\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.' WHERE `id` = '527';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .summon [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline.' WHERE `id` = '528';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.' WHERE `id` = '529';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unbindsight\r\n\r\nRemoves bound vision. Cannot be used while currently possessing a target.' WHERE `id` = '530';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unfreeze (#player)\r\n\"Unfreezes\" #player and enables his chat again. When using this without #name it will unfreeze your target.' WHERE `id` = '531';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unmute [$playerName]\r\n\r\nRestore chat messaging for any character from account of character $playerName (or selected). Character can be ofline.' WHERE `id` = '532';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unpossess\r\n\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.' WHERE `id` = '533';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .unstuck $playername [inn/graveyard/startzone]\n\nTeleports specified player to specified location. Default location is player\'s current hearth location.' WHERE `id` = '534';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wchange #weathertype #status\r\n\r\nSet current weather to #weathertype with an intensity of #status.\r\n\r\n#weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.' WHERE `id` = '535';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmaps $subcommand Type .mmaps to see the list of possible subcommands or .help mmaps $subcommand to see info on subcommands' WHERE `id` = '536';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmap loadedtiles to show which tiles are currently loaded' WHERE `id` = '537';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmap loc to print on which tile one is' WHERE `id` = '538';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmap path to calculate and show a path to current select unit' WHERE `id` = '539';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmap stats to show information about current state of mmaps' WHERE `id` = '540';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mmap testarea to calculate paths for all nearby npcs to player' WHERE `id` = '541';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .morph #displayid\r\n\r\nChange your current model id to #displayid.' WHERE `id` = '542';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .demorph\r\n\r\nDemorph the selected player.' WHERE `id` = '543';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify $subcommand\nType .modify to see the list of possible subcommands or .help modify $subcommand to see info on subcommands' WHERE `id` = '544';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify arenapoints #value\r\nAdd $amount arena points to the selected player.' WHERE `id` = '545';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify bit #field #bit\r\n\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.' WHERE `id` = '546';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.' WHERE `id` = '547';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify energy #energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy.' WHERE `id` = '548';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.' WHERE `id` = '549';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify gender male/female\r\n\r\nChange gender of selected player.' WHERE `id` = '550';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify honor $amount\r\n\r\nAdd $amount honor points to the selected player.' WHERE `id` = '551';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify hp #newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp.' WHERE `id` = '552';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify mana #newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana.' WHERE `id` = '553';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify money #money\r\n.money #money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n #gold can be negative to remove money.' WHERE `id` = '554';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.' WHERE `id` = '555';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify phase #phasemask\r\n\r\nSelected character phasemask changed to #phasemask with related world vision update. Change active until in game phase changed, or GM-mode enable/disable, or re-login. Character pts pasemask update to same value.' WHERE `id` = '556';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify rage #newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage.' WHERE `id` = '557';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify reputation #repId (#repvalue | $rankname [#delta])\nSets the selected players reputation with faction #repId to #repvalue or to $reprank.\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.' WHERE `id` = '558';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify runicpower #newrunicpower\r\n\r\nModify the runic power of the selected player. If no player is selected, modify your runic power.' WHERE `id` = '559';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify scale #scale\r\n\nModify size of the selected player or creature to \"normal scale\"*rate. If no player or creature is selected, modify your size.\n#rate may range from 0.1 to 10.' WHERE `id` = '560';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify speed $speedtype #rate\r\n\r\nModify the running speed of the selected player to \"normal base run speed\"= 1. If no player is selected, modify your speed.\r\n\r\n$speedtypes may be fly, all, walk, backwalk, or swim.\r\n\r\n #rate may range from 0.1 to 50.' WHERE `id` = '561';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify aspeed #rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to \"normalbase speed for this move type\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.' WHERE `id` = '562';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify speed backwalk #rate\r\n\r\nModify the speed of the selected player while running backwards to \"normal walk back speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.' WHERE `id` = '563';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify speed fly #rate\r\n\nModify the flying speed of the selected player to \"normal flying speed\"*rate. If no player is selected, modify your speed.\n #rate may range from 0.1 to 50.' WHERE `id` = '564';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify speed bwalk #rate\r\n\r\nModify the speed of the selected player while running to \"normal walk speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.' WHERE `id` = '565';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify speed swim #rate\r\n\r\nModify the swim speed of the selected player to \"normal swim speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.' WHERE `id` = '566';
UPDATE `rbac_permissions` SET `help` = 'TODO' WHERE `id` = '567';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify standstate #emoteid\r\n\r\nChange the emote of your character while standing to #emoteid.' WHERE `id` = '568';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .modify talentpoints #amount\r\n\r\nSet free talent points for selected character or character\'s pet. It will be reset to default expected at next levelup/login/quest reward.' WHERE `id` = '569';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc $subcommand\nType .npc to see the list of possible subcommands or .help npc $subcommand to see info on subcommands' WHERE `id` = '570';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc add #creatureid\r\n\r\nSpawn a creature by the given template id of #creatureid.' WHERE `id` = '571';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc add formation $leader\nAdd selected creature to a leader\'s formation.' WHERE `id` = '572';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc add item #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.' WHERE `id` = '573';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc add move #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.' WHERE `id` = '574';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc add temp\r\n\r\nAdds temporary NPC, not saved to database.' WHERE `id` = '575';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc delete [#guid]\r\n\r\nDelete creature with guid #guid (or the selected if no guid is provided)' WHERE `id` = '576';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc delete item #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.' WHERE `id` = '577';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc follow start\r\n\r\nSelected creature start follow you until death/fight/etc.' WHERE `id` = '578';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc follow stop\r\n\r\nSelected creature (non pet) stop follow you.' WHERE `id` = '579';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.' WHERE `id` = '581';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set entry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.' WHERE `id` = '582';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set factionid #factionid\r\n\r\nSet the faction of the selected creature to #factionid.' WHERE `id` = '583';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.' WHERE `id` = '584';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set level #level\r\n\r\nChange the level of the selected creature to #level.\r\n\r\n#level may range from 1 to (CONFIG_MAX_PLAYER_LEVEL) + 3.' WHERE `id` = '585';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set link $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.' WHERE `id` = '586';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set model #displayid\r\n\r\nChange the model id of the selected creature to #displayid.' WHERE `id` = '587';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set movetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.' WHERE `id` = '588';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set phase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..' WHERE `id` = '589';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.' WHERE `id` = '590';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.' WHERE `id` = '591';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc set data $field $data\nSets data for the selected creature. Used for testing Scripting' WHERE `id` = '592';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.' WHERE `id` = '593';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc move [#creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates.' WHERE `id` = '595';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc playemote #emoteid\r\n\r\nMake the selected creature emote with an emote of id #emoteid.' WHERE `id` = '596';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc say $message\nMake selected creature say specified message.' WHERE `id` = '597';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc textemote #emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id #emoteid.' WHERE `id` = '598';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.' WHERE `id` = '599';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .npc yell $message\nMake selected creature yell specified message.' WHERE `id` = '600';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .quest $subcommand\nType .quest to see the list of possible subcommands or .help quest $subcommand to see info on subcommands' WHERE `id` = '602';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .quest add #quest_id\r\n\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.' WHERE `id` = '603';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.' WHERE `id` = '604';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .quest remove #quest_id\r\n\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.' WHERE `id` = '605';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .quest reward #questId\n\nGrants quest reward to selected player and removes quest from his log (quest must be in completed state).' WHERE `id` = '606';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands' WHERE `id` = '607';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload access_requirement\nReload access_requirement table.' WHERE `id` = '608';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload achievement_criteria_data\nReload achievement_criteria_data table.' WHERE `id` = '609';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload achievement_reward\nReload achievement_reward table.' WHERE `id` = '610';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.' WHERE `id` = '611';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all achievement\r\n\r\nReload achievement_reward, achievement_criteria_data tables.' WHERE `id` = '612';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all area\r\n\r\nReload areatrigger_teleport, areatrigger_tavern, game_graveyard_zone tables.' WHERE `id` = '613';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.' WHERE `id` = '615';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.' WHERE `id` = '616';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.' WHERE `id` = '617';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.' WHERE `id` = '618';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.' WHERE `id` = '619';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.' WHERE `id` = '620';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.' WHERE `id` = '621';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.' WHERE `id` = '622';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.' WHERE `id` = '623';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.' WHERE `id` = '624';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.' WHERE `id` = '625';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload auctions\nReload dynamic data tables from the database.' WHERE `id` = '626';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload autobroadcast\nReload autobroadcast table.' WHERE `id` = '627';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload command\nReload command table.' WHERE `id` = '628';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload conditions\r\nReload conditions table.' WHERE `id` = '629';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.' WHERE `id` = '630';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_questender\nReload creature_questender table.' WHERE `id` = '634';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.' WHERE `id` = '635';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.' WHERE `id` = '636';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table.' WHERE `id` = '637';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_queststarter\nReload creature_queststarter table.' WHERE `id` = '638';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_summon_groups\nReload creature_summon_groups table.' WHERE `id` = '639';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.' WHERE `id` = '640';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload disables\r\nReload disables table.' WHERE `id` = '641';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.' WHERE `id` = '642';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload event_scripts\nReload event_scripts table.' WHERE `id` = '643';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.' WHERE `id` = '644';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload game_graveyard_zone\nReload game_graveyard_zone table.' WHERE `id` = '645';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload game_tele\nReload game_tele table.' WHERE `id` = '646';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gameobject_questender\\nReload gameobject_questender table.' WHERE `id` = '647';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.' WHERE `id` = '648';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gameobject_queststarter\nReload gameobject_queststarter table.' WHERE `id` = '649';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gm_tickets\nReload gm_tickets table.' WHERE `id` = '650';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gossip_menu\nReload gossip_menu table.' WHERE `id` = '651';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.' WHERE `id` = '652';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.' WHERE `id` = '653';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload item_loot_template\nReload item_loot_template table.' WHERE `id` = '654';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload item_set_names\nReload item_set_names table.' WHERE `id` = '655';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.' WHERE `id` = '656';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_creature\nReload locales_creature table.' WHERE `id` = '658';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_creature_text\nReload locales_creature_text Table.' WHERE `id` = '659';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_gameobject\nReload locales_gameobject table.' WHERE `id` = '660';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_gossip_menu_option\nReload locales_gossip_menu_option table.' WHERE `id` = '661';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_item\nReload locales_item table.' WHERE `id` = '662';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_item_set_name\nReload locales_item_set_name table.' WHERE `id` = '663';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_npc_text\nReload locales_npc_text table.' WHERE `id` = '664';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_page_text\nReload locales_page_text table.' WHERE `id` = '665';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_points_of_interest\nReload locales_point_of_interest table.' WHERE `id` = '666';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload locales_quest\nReload locales_quest table.' WHERE `id` = '667';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload mail_level_reward\nReload mail_level_reward table.' WHERE `id` = '668';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.' WHERE `id` = '669';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.' WHERE `id` = '670';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload npc_trainer\nReload npc_trainer table.' WHERE `id` = '672';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload npc_vendor\nReload npc_vendor table.' WHERE `id` = '673';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload page_text\nReload page_text table.' WHERE `id` = '674';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.' WHERE `id` = '675';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload points_of_interest\nReload points_of_interest table.' WHERE `id` = '676';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.' WHERE `id` = '677';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload quest_poi\nReload quest_poi table.' WHERE `id` = '678';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload quest_template\nReload quest_template table.' WHERE `id` = '679';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload rbac\nReload rbac system.' WHERE `id` = '680';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.' WHERE `id` = '681';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload reserved_name\nReload reserved_name table.' WHERE `id` = '682';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.' WHERE `id` = '685';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.' WHERE `id` = '686';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.' WHERE `id` = '687';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.' WHERE `id` = '688';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload smart_scripts\nReload smart_scripts table.' WHERE `id` = '689';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_required\nReload spell_required table.' WHERE `id` = '690';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_area\nReload spell_area table.' WHERE `id` = '691';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_bonus_data\nReload spell_bonus_data table.' WHERE `id` = '692';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_group\nReload spell_group table.' WHERE `id` = '693';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_learn_spell\nReload spell_learn_spell table.' WHERE `id` = '694';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.' WHERE `id` = '695';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.' WHERE `id` = '696';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.' WHERE `id` = '697';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_proc_event\nReload spell_proc_event table.' WHERE `id` = '698';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_proc\nReload spell_proc table.' WHERE `id` = '699';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_scripts\nReload spell_scripts table.' WHERE `id` = '700';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_target_position\nReload spell_target_position table.' WHERE `id` = '701';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_threats\nReload spell_threats table.' WHERE `id` = '702';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.' WHERE `id` = '703';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload trinity_string\nReload trinity_string table.' WHERE `id` = '704';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.' WHERE `id` = '706';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload waypoint_data will reload waypoint_data table.' WHERE `id` = '707';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload vehicle_accessory\n\nReloads GUID-based vehicle accessory definitions from the database.' WHERE `id` = '708';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reload vehicle_template_accessory\n\nReloads entry-based vehicle accessory definitions from the database.' WHERE `id` = '709';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset $subcommand\nType .reset to see the list of possible subcommands or .help reset $subcommand to see info on subcommands' WHERE `id` = '710';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset achievements [$playername]\r\n\r\nReset achievements data for selected or named (online or offline) character. Achievements for persistance progress data like completed quests/etc re-filled at reset. Achievements for events like kills/casts/etc will lost.' WHERE `id` = '711';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character.' WHERE `id` = '712';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.' WHERE `id` = '713';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character.' WHERE `id` = '714';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level.' WHERE `id` = '715';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player or pet or named player. Playername can be name of offline character. With player talents also will be reset talents for all character\'s pets if any.' WHERE `id` = '716';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nRequest reset spells or talents (including talents for all character\'s pets if any) at next login each existed character.' WHERE `id` = '717';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server $subcommand\nType .server to see the list of possible subcommands or .help server $subcommand to see info on subcommands' WHERE `id` = '718';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world.' WHERE `id` = '719';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server exit\r\n\r\nTerminate trinity-core NOW. Exit code 0.' WHERE `id` = '720';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server idlerestart #delay\r\n\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.' WHERE `id` = '721';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any.' WHERE `id` = '722';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server idleshutdown #delay [#exist_code]\r\n\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.' WHERE `id` = '723';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server idleshutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.' WHERE `id` = '724';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server info\r\n\r\nDisplay server version and the number of connected players.' WHERE `id` = '725';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file' WHERE `id` = '726';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server restart #delay\r\n\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.' WHERE `id` = '727';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any.' WHERE `id` = '728';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server set closed on/off\r\n\r\nSets whether the world accepts new client connectsions.' WHERE `id` = '730';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server set loglevel $facility $name $loglevel. $facility can take the values: appender (a) or logger (l). $loglevel can take the values: disabled (0), trace (1), debug (2), info (3), warn (4), error (5) or fatal (6)' WHERE `id` = '732';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day.' WHERE `id` = '733';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server shutdown #delay [#exit_code]\r\n\r\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code.' WHERE `id` = '734';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.' WHERE `id` = '735';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .server motd\r\n\r\nShow server Message of the day.' WHERE `id` = '736';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .tele #location\r\n\r\nTeleport player to a given location.' WHERE `id` = '737';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .tele add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name.' WHERE `id` = '738';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .tele del $name\r\n\r\nRemove location with name $name for .tele command locations list.' WHERE `id` = '739';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .tele name [#playername] #location\n\nTeleport the given character to a given location. Character can be offline.\n\nTo teleport to homebind, set #location to \"$home\" (without quotes).' WHERE `id` = '740';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .tele group#location\r\n\r\nTeleport a selected player and his group members to a given location.' WHERE `id` = '741';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands' WHERE `id` = '742';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.' WHERE `id` = '743';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.' WHERE `id` = '744';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket closedlist\r\nDisplays a list of closed GM tickets.' WHERE `id` = '745';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.' WHERE `id` = '746';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.' WHERE `id` = '748';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket list\r\nDisplays a list of open GM tickets.' WHERE `id` = '751';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket onlinelist\r\nDisplays a list of open GM tickets whose owner is online.' WHERE `id` = '752';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing.' WHERE `id` = '753';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.' WHERE `id` = '758';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.' WHERE `id` = '759';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted.' WHERE `id` = '760';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .titles add #title\r\nAdd title #title (id or shift-link) to known titles list for selected player.' WHERE `id` = '762';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .titles current #title\r\nSet title #title (id or shift-link) as current selected titl for selected player. If title not in known title list for player then it will be added to list.' WHERE `id` = '763';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .titles remove #title\r\nRemove title #title (id or shift-link) from known titles list for selected player.' WHERE `id` = '764';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .titles set mask #mask\r\n\r\nAllows user to use all titles from #mask.\r\n\r\n #mask=0 disables the title-choose-field' WHERE `id` = '766';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp add\r\n\r\nAdd a waypoint for the selected creature at your current position.' WHERE `id` = '768';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp event $subcommand\nType .path event to see the list of possible subcommands or .help path event $subcommand to see info on subcommands.' WHERE `id` = '769';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp load $pathid\nLoad pathid number for selected creature. Creature must have no waypoint data.' WHERE `id` = '770';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp unload\nUnload path for selected creature.' WHERE `id` = '772';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp reload $pathid\nLoad path changes ingame - IMPORTANT: must be applied first for new paths before .wp load #pathid ' WHERE `id` = '773';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .wp show $option\nOptions:\non $pathid (or selected creature with loaded path) - Show path\noff - Hide path\ninfo $slected_waypoint - Show info for selected waypoint.' WHERE `id` = '774';
UPDATE `rbac_permissions` SET `help` = 'Syntax: .mailbox\r\n\r\nShow your mailbox content.' WHERE `id` = '777';
