DELETE FROM `page_text` WHERE `ID` IN (5279 /*5279*/, 5158 /*5158*/, 5126 /*5126*/, 5122 /*5122*/, 5310 /*5310*/, 5309 /*5309*/, 5308 /*5308*/, 4932 /*4932*/, 4928 /*4928*/);
INSERT INTO `page_text` (`ID`, `Text`, `NextPageID`, `PlayerConditionID`, `Flags`, `VerifiedBuild`) VALUES
(5279, 'Ran''thos Lunastre$B$BHead of House Lunastre. Father of Ly''leth and Anarys.$B$BDied in honorable service to Grand Magistrix Elisande.', 0, 0, 0, 22498), -- 5279
(5158, 'Liftbrul, greatest of weightlifters ("No, scratch that part out!") among all drogbar, champion of the Stonedark.\n\nImmortalized in stone by chief Rynox, second-strongest drogbar of his time ("What are you writing there, Stonecarver?").\n\nThis is not a statue, it is Liftbrul. Rynox is a Stoneshaper ("Does it say something nice about me?").', 0, 0, 0, 22498), -- 5158
(5126, 'An officer''s sword stands out among the wreckage. Scanning the nearby bodies, you notice the captain is not among them.', 0, 0, 0, 22498), -- 5126
(5122, '<... ing Legion repelled from Orgrim...>\n\n<... on the Broken Shore. I have every faith that my crew will bring glory to the forsaken and make the Dark Lady proud. We''re half a da...>\n\n<... barely survived. Queen Sylvanas has ordered the fleet to make way for Stormheim. I have a staff meeting with Admiral Harker on the Windrunner in an h...>\n\n<... teresting to be certain. The queen is going to steal the very power of the v... or herself!>\n\n<... separated by a massive storm. I''ve given the order to batten down the hatches and weather it. There''s no sign of the fleet. Once the... [illegible text] ... we''ll catch up and rendezvous at the...>', 0, 0, 0, 22498), -- 5122
(5310, 'THE FATE OF AZSUNA\n\nAzshara wasted no time in punishing Farondis and his people. In a frightening display of arcane power, she destroyed the Tidestone of Golganneth, and in doing so, released a wave of dark energy over all of Azsuna and its inhabitants.\n\nSince that day, the elves of Azsuna have been unable to experience the release of death. Their spirits - our spirits - wander the land indefinitely... all because of our prince''s unwise allegiances.', 0, 0, 0, 22498), -- 5310
(5309, 'THE WRATH OF THE QUEEN\n\nFarondis'' plan was bold, but simple: destroy the Well of Eternity in Zin-Azshari. Doing so would close the portal to Sargeras'' realm and stem the tide of evil before it even started. In order to accomplish this task, he would use the power of an artifact stored deep within Nar''thalas Academy: The Tidestone of Golganneth.\n\nUnfortunately, the queen''s influence in Farondis'' palace was already deep-seated. Vandros, a young noble in Farondis'' court, caught word of Farondis'' plans to defy the Queen, and reported the insurrection to Queen Azshara herself.', 0, 0, 0, 22498), -- 5309
(5308, 'THE DEFIANCE OF FARONDIS\n\nQueen Azshara''s pact with the demon lord Sargeras went mostly uncontested by her subjects. One of the few that dared to defy her was Prince Farondis.\n\nAs one of the queen''s trusted advisors, Farondis was in regular contact with the Highborne of Zin-Azshari, but his palace in Azsuna was several leagues away from the elven capital. As such, he was able to witness Sargeras'' influence on the Highborne court without falling sway to the demons'' temptation.', 0, 0, 0, 22498), -- 5308
(4932, 'Organic awareness of The War is growing too quickly.  Above-ground units possibly infected.  Seed plans for next-gen Blingtron remote to call on veteran units that can assess and destroy.', 0, 0, 0, 22498), -- 4932
(4928, 'Allied destruction total has increased to 64%.  Request supplies.', 0, 0, 0, 22498); -- 4928
