#include "../iron_docks.h"

enum Spells
{
    // Skulloc
    SPELL_WAR_HORN                      = 170909, // + SPELL_EFFECT_DUMMY
    SPELL_GRON_SMASH                    = 168227, //(+)SPELL_EFFECT_SCRIPT_EFFECT | SPELL_EFFECT_DUMMY | SPELL_AURA_STRANGULATE | SPELL_EFFECT_SCHOOL_DAMAGE (N|H|C)
    SPELL_BACK_DRAFT                    = 169131, //(+)SPELL_EFFECT_DUMMY
    SPELL_DUMMY_NUKE                    = 68991,  // + SPELL_EFFECT_SCHOOL_DAMAGE
    SPELL_PERMANENT_FEIGN_DEATH         = 29266,  //(+)SPELL_AURA_DUMMY | SPELL_AURA_MOD_STUN

    SPELL_CANNON_BARRAGE                = 168511, // + SPELL_EFFECT_FORCE_CAST | SPELL_EFFECT_FORCE_CAST | SPELL_AURA_PERIODIC_TRIGGER_SPELL | SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_CANNON_BARRAGE_TRIGGER        = 168537, // +->(+)SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_CANNON_BARRAGE_DAMAGE_1       = 168514, // +-> + SPELL_EFFECT_SCHOOL_DAMAGE (N|H|C)
    SPELL_CANNON_BARRAGE_DAMAGE_2       = 168541, // +-> + SPELL_EFFECT_SCHOOL_DAMAGE (N|H)

    SPELL_CANNON_BARRAGE_CANCEL         = 169072, // + SPELL_EFFECT_REMOVE_AURA[168929] | SPELL_EFFECT_REMOVE_AURA[168129] | SPELL_EFFECT_REMOVE_AURA[168129] | SPELL_EFFECT_REMOVE_AURA[168820]

    SPELL_CHECK_FOR_PLAYERS             = 169071, // + SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_CHECK_FOR_PLAYERS_DUMMY       = 168926, // +->(+)SPELL_EFFECT_DUMMY

    // Koramar
    SPELL_BERSERKER_LEAP                = 168400, // + SPELL_EFFECT_JUMP_DEST
    SPELL_BERSERKER_LEAP_DAMAGE         = 168399, // +-> + SPELL_EFFECT_SCHOOL_DAMAGE (N|H|C)

    SPELL_SHATTERING_BLADE              = 168939, // + SPELL_EFFECT_DUMMY | SPELL_EFFECT_TRIGGER_MISSILE
    SPELL_SHATTERING_BLADE_TIDAL_WAVE   = 148519, // +->(+)SPELL_EFFECT_DUMMY
    SPELL_SHATTERING_BLADE_DAMAGE       = 168955, // +-> + SPELL_EFFECT_SCHOOL_DAMAGE (N|H|C)

    SPELL_BLADESTORM                    = 168402, // + SPELL_AURA_PERIODIC_TRIGGER_SPELL | SPELL_AURA_MOD_DECREASE_SPEED
    SPELL_BLADESTORM_DAMAGE             = 168401, // +-> + SPELL_EFFECT_WEAPON_PERCENT_DAMAGE (N|H|C)

    // Zoggosh
    SPELL_RAPID_FIRE                    = 168394, // + SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_RAPID_FIRE_DAMAGE             = 168348, // +->(+)SPELL_EFFECT_DUMMY | SPELL_EFFECT_SCHOOL_DAMAGE (N|H|C)
};

enum Events
{
    // Skulloc
    EVENT_CANNON_BARRAGE                = 1,

    // Koramar
    EVENT_BERSERKER_LEAP,
    EVENT_SHATTERING_BLADE,
    EVENT_BLADESTORM,

    // Zoggosh
    EVENT_RAPID_FIRE,
};

enum Timer
{
    // Skulloc
    TIME_CANNON_BARRAGE_INIT            = 0 * IN_MILLISECONDS,
    TIME_CANNON_BARRAGE_MIN             = 0 * IN_MILLISECONDS,
    TIME_CANNON_BARRAGE_MAX             = 0 * IN_MILLISECONDS,

    // Koramar
    TIME_BERSERKER_LEAP_INIT            = 0 * IN_MILLISECONDS,
    TIME_BERSERKER_LEAP_MIN             = 0 * IN_MILLISECONDS,
    TIME_BERSERKER_LEAP_MAX             = 0 * IN_MILLISECONDS,

    TIME_SHATTERING_BLADE_INIT          = 0 * IN_MILLISECONDS,
    TIME_SHATTERING_BLADE_MIN           = 0 * IN_MILLISECONDS,
    TIME_SHATTERING_BLADE_MAX           = 0 * IN_MILLISECONDS,

    TIME_BLADESTORM_INIT                = 0 * IN_MILLISECONDS,
    TIME_BLADESTORM_MIN                 = 0 * IN_MILLISECONDS,
    TIME_BLADESTORM_MAX                 = 0 * IN_MILLISECONDS,

    // Zoggosh
    TIME_RAPID_FIRE_INIT                = 0 * IN_MILLISECONDS,
    TIME_RAPID_FIRE_MIN                 = 0 * IN_MILLISECONDS,
    TIME_RAPID_FIRE_MAX                 = 0 * IN_MILLISECONDS,
};