blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/3UxRn4Kn?utm_source=Discord%20Widget&utm_medium=Connect
    about: Chat
  - name: How to Compile
    url: https://trinitycore.atlassian.net/
    about: Wiki
  - name: Community Support Forum
    url: https://community.trinitycore.org/
    about: Forum
  - name: Discussions
    url: https://github.com/TrinityCore/TrinityCore/discussions
    about: Discuss