name: SQL fix
description: Suggest a SQL only fix.
labels: [Comp-Database, Feedback-PatchFix]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! Please make sure to fill all fields, including the Title above.
        For SQL fixes:
        - search for existing issues. If a bug report exists for the issue you are trying to fix, and it's open, post your suggestion there
        - always start suggestion by -- in case previous SQL file has no newline
        - don't modify WDB fields without providing sniffs of those fields (censure guids, character names, anything blizzard can use to identify source)
        - don't hardcode guids (use guid from fixed guid range when adding new objects or creatures)
        - don't DELETE + INSERT to update only few fields of one row
        - don't use database names
        - don't use ' around numbers
        - don't use ( ) if they aren't needed
        - use only one INSERT INTO statement when you add multiple rows to one table, unless you are scripting multiple creatures
        - always add every row you insert below INSERT INTO statement (each row inside new row)
        - always use capital letters for all keywords (DELETE, FROM, SELECT, WHERE, IN, etc.)
        - always use backticks for every column and table name
        - always include column names in every INSERT INTO statement
        - always make every INSERT INTO statement runnable twice (delete what you insert even if row does not exist, don't use REPLACE INTO)
        - DELETE by guid AND id to be sure we don't delete existing spawns

        The wiki page https://github.com/TrinityCore/TrinityCore/wiki/SQL-Fix includes additional details about how to fill this form and an example of a SQL fix.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of what is getting fixed, including how to reproduce the issue if any.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: SQL fix
      description: This field will be formatted automatically as SQL code block, no need to include \`\`\`sql
      placeholder: |
        --
      render: sql
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      options:
        - 3.3.5
        - master
    validations:
      required: true
  - type: textarea
    id: commit
    attributes:
      label: TC rev. hash/commit
      description: |
        Copy the result of server debug command (if you need to run it from client get prat addon)
    validations:
      required: true
