update areatrigger_tavern set name='西部荒野 - 哨兵岭旅店 ' where id=71;
update areatrigger_tavern set name='艾尔文森林 - 闪金镇 - 狮王之傲旅店 ' where id=562;
update areatrigger_tavern set name='赤脊山 - 湖畔旅店 ' where id=682;
update areatrigger_tavern set name='暮色森林 - 夜色 - 血色旅店 ' where id=707;
update areatrigger_tavern set name='希尔斯布莱德丘陵 - 南海镇的旅店 ' where id=708;
update areatrigger_tavern set name='尘泥沼泽 - 塞拉摩岛 ' where id=709;
update areatrigger_tavern set name='丹莫罗 - 卡拉诺斯 - 雷酒厂 ' where id=710;
update areatrigger_tavern set name='洛克莫丹 - 在塞尔萨玛 - 烈酒旅店 ' where id=712;
update areatrigger_tavern set name='湿地 - 米奈希尔港 - 深水酒馆 ' where id=713;
update areatrigger_tavern set name='泰达希尔 - 多兰纳尔 ' where id=715;
update areatrigger_tavern set name='黑海岸 - 奥伯丁 ' where id=716;
update areatrigger_tavern set name='梣谷 - 阿斯特兰纳 ' where id=717;
update areatrigger_tavern set name='提里斯法林地 - 布瑞尔 - 恐惧之末旅店 ' where id=719;
update areatrigger_tavern set name='银松森林 ' where id=720;
update areatrigger_tavern set name='希尔斯布莱德丘陵 ' where id=721;
update areatrigger_tavern set name='莫高雷 ' where id=722;
update areatrigger_tavern set name='贫瘠之地 ' where id=742;
update areatrigger_tavern set name='贫瘠之地 ' where id=743;
update areatrigger_tavern set name='杜洛塔 ' where id=843;
update areatrigger_tavern set name='悲伤沼泽 ' where id=844;
update areatrigger_tavern set name='荆棘谷 ' where id=862;
update areatrigger_tavern set name='贫瘠之地 ' where id=982;
update areatrigger_tavern set name='血谜岛 - 血色守望旅店 ' where id=4241;
update areatrigger_tavern set name='石爪山脉 ' where id=1022;
update areatrigger_tavern set name='塔纳利斯 ' where id=1023;
update areatrigger_tavern set name='菲拉斯 ' where id=1024;
update areatrigger_tavern set name='菲拉斯 ' where id=1025;
update areatrigger_tavern set name='废地 ' where id=1606;
update areatrigger_tavern set name='阿拉希高地 ' where id=1646;
update areatrigger_tavern set name='凄凉之地 ' where id=2266;
update areatrigger_tavern set name='凄凉之地 ' where id=2267;
update areatrigger_tavern set name='千针石林 ' where id=2286;
update areatrigger_tavern set name='冬泉谷 ' where id=2287;
update areatrigger_tavern set name='梣谷 ' where id=2610;
update areatrigger_tavern set name='暴风城休息站 ' where id=2786;
update areatrigger_tavern set name='安宁旅店 ' where id=4108;
update areatrigger_tavern set name='碧蓝岗哨旅店 ' where id=4240;
update areatrigger_tavern set name='萨尔玛旅店 ' where id=4336;
update areatrigger_tavern set name='荣耀堡旅店 ' where id=4337;
update areatrigger_tavern set name='萨布拉金旅店 ' where id=4373;
update areatrigger_tavern set name='如卡拉达尔快捷酒店 ' where id=4375;
update areatrigger_tavern set name='泰拉旅店 ' where id=4376;
update areatrigger_tavern set name='艾兰理堡垒旅店 ' where id=4377;
update areatrigger_tavern set name='塞纳里奥避难所 ' where id=4382;
update areatrigger_tavern set name='猎鹰之翼广场旅店 ' where id=4486;
update areatrigger_tavern set name='影月村旅店 ' where id=4526;
update areatrigger_tavern set name='蛮锤要塞旅店 ' where id=4528;
update areatrigger_tavern set name='摩克纳萨尔村旅店 ' where id=4595;
update areatrigger_tavern set name='星光圣所旅店 ' where id=4607;
update areatrigger_tavern set name='泰伦多尔旅店 ' where id=4374;
update areatrigger_tavern set name='奥雷伯尔港旅店 ' where id=4383;
update areatrigger_tavern set name='特尔哈曼神庙旅店 ' where id=4381;
update areatrigger_tavern set name='希尔瓦纳旅店 ' where id=4499;
update areatrigger_tavern set name='托斯利基地旅店 ' where id=4558;
update areatrigger_tavern set name='雷霆王村旅店 ' where id=4494;
update areatrigger_tavern set name='永恒树林旅店 ' where id=4640;
update areatrigger_tavern set name='52区旅店 ' where id=4521;
update areatrigger_tavern set name='风暴之尖旅店 ' where id=4555;
update areatrigger_tavern set name='萨塔祭坛 ' where id=4577;
update areatrigger_tavern set name='斯坦恩布莱德 ' where id=178;
update areatrigger_tavern set name='蛮锤城堡 ' where id=1042;
update areatrigger_tavern set name='恶齿村 ' where id=3690;
update areatrigger_tavern set name='格罗姆高营地 ' where id=3886;
update areatrigger_tavern set name='圣光之愿礼拜堂 ' where id=4058;
update areatrigger_tavern set name='塞纳里奥城堡 ' where id=3985;
update areatrigger_tavern set name='石爪峰 ' where id=4090;
update areatrigger_tavern set name='幽暗城 ' where id=3547;
update areatrigger_tavern set name='铁炉堡大门 ' where id=4769;
update areatrigger_tavern set name='泥链营地旅店 ' where id=4714;
update areatrigger_tavern set name='蕨墙村旅店 ' where id=4775;
update areatrigger_tavern set name='奎尔丹纳斯岛，日境港酒店 ' where id=4847;
update areatrigger_tavern set name='骁勇要塞旅店 ' where id=4961;
update areatrigger_tavern set name='嘶轴简易机场旅店 ' where id=4867;
update areatrigger_tavern set name='昂纽沛旅店 ' where id=4977;
update areatrigger_tavern set name='坦卡雷村旅店 ' where id=4868;
update areatrigger_tavern set name='战歌堡 ' where id=4910;
update areatrigger_tavern set name='博格洛克前哨旅店 ' where id=4861;
update areatrigger_tavern set name='冬蹄营地旅店 ' where id=4755;
update areatrigger_tavern set name='威德瓦堡垒旅店 ' where id=4756;
update areatrigger_tavern set name='阿格玛之锤 ' where id=5045;
update areatrigger_tavern set name='繁星之眠 ' where id=4964;
update areatrigger_tavern set name='琥珀松小屋旅店 ' where id=4965;
update areatrigger_tavern set name='西荒兵团驻营 ' where id=4966;
update areatrigger_tavern set name='欧尼克瓦营地 ' where id=4967;
update areatrigger_tavern set name='征服堡 ' where id=4970;
update areatrigger_tavern set name='默亚基港 ' where id=4975;
update areatrigger_tavern set name='卡玛廓 ' where id=4976;
update areatrigger_tavern set name='毒怨之地 ' where id=4979;
update areatrigger_tavern set name='温特加德要塞 ' where id=4993;
update areatrigger_tavern set name='矛生驻营 ' where id=5030;
update areatrigger_tavern set name='银白看台 ' where id=5062;
update areatrigger_tavern set name='辛讬加 ' where id=5164;
update areatrigger_tavern set name='霜堡 ' where id=5182;
update areatrigger_tavern set name='K3 ' where id=5183;
update areatrigger_tavern set name='布伦希尔达村 ' where id=5200;
update areatrigger_tavern set name='石崖避难所 ' where id=5204;
update areatrigger_tavern set name='奈辛瓦里营地 ' where id=5217;
update areatrigger_tavern set name='银白先锋 ' where id=5227;
update areatrigger_tavern set name='坦卡罗营地 ' where id=5323;
update areatrigger_tavern set name='卡萨斯平台 ' where id=5327;
update areatrigger_tavern set name='镇西旅店 ' where id=4753;
update areatrigger_tavern set name='晴风村旅店 ' where id=4265;
update areatrigger_tavern set name='奈辛瓦里远征队营地 ' where id=98;
update areatrigger_tavern set name='安宁地旅店（上层） ' where id=4109;
update areatrigger_tavern set name='塞纳里奥难民 - 外旅店 ' where id=4300;
update areatrigger_tavern set name='石堡旅店 ' where id=4378;
update areatrigger_tavern set name='猎鹰岗哨旅店 ' where id=4380;
update areatrigger_tavern set name='旧希尔斯布莱德丘陵旅店 ' where id=4498;
update areatrigger_tavern set name='圣殿的星星旅店（上层） ' where id=4608;
update areatrigger_tavern set name='龙眠神殿地下室' where id=5314;
update areatrigger_tavern set name='龙眠神殿 一层' where id=5315;
update areatrigger_tavern set name='龙眠神殿 二层' where id=5316;
update areatrigger_tavern set name='龙眠神殿 三层' where id=5317;
update areatrigger_tavern set name='格罗玛什坠毁点' where id=5360;
