update game_event set description='仲夏焰火节 ' where eventEntry=1;
update game_event set description='冬幕节 ' where eventEntry=2;
update game_event set description='暗月马戏团（泰罗卡森林） ' where eventEntry=3;
update game_event set description='暗月马戏团（艾尔文森林） ' where eventEntry=4;
update game_event set description='暗月马戏团（莫高雷） ' where eventEntry=5;
update game_event set description='除夕' where eventEntry=6;
update game_event set description='农历节庆' where eventEntry=7;
update game_event set description='爱意弥漫的天空 ' where eventEntry=8;
update game_event set description='贵族花园 ' where eventEntry=9;
update game_event set description='儿童周 ' where eventEntry=10;
update game_event set description='收获节 ' where eventEntry=11;
update game_event set description='万圣节 ' where eventEntry=12;
update game_event set description='安其拉之战 ' where eventEntry=22;
update game_event set description='天灾入侵 ' where eventEntry=17;
update game_event set description='元素生物入侵 ' where eventEntry=13;
update game_event set description='钓鱼比赛 ' where eventEntry=14;
update game_event set description='古拉巴什竞技场战斗 ' where eventEntry=16;
update game_event set description='钓鱼比赛 ' where eventEntry=15;
update game_event set description='战斗的召唤：奥特兰克山谷 ' where eventEntry=18;
update game_event set description='战斗的召唤：战歌峡谷 ' where eventEntry=19;
update game_event set description='战斗的召唤：阿拉希盆地 ' where eventEntry=20;
update game_event set description='战斗的召唤：风暴之眼 ' where eventEntry=21;
update game_event set description='奥格瑞玛狼群进攻 ( 队伍一 ) ' where eventEntry=23;
update game_event set description='奥格瑞玛狼群进攻 ( 队伍二 ) ' where eventEntry=24;
update game_event set description='奥格瑞玛防守战斗 ' where eventEntry=25;
update game_event set description='金亚莱之主, 库图比萨 ' where eventEntry=27;
update game_event set description='亡灵军队进攻暴风城 (亡灵进攻) ' where eventEntry=28;
update game_event set description='夜幕 ' where eventEntry=29;
update game_event set description='战斗的召唤：远古海滩 ' where eventEntry=30;
update game_event set description='达拉然 - 冠军邀请' where eventEntry=31;
update game_event set description='海盗节日 ' where eventEntry=32;
update game_event set description='三月 ' where eventEntry=52;
update game_event set description='二月 ' where eventEntry=51;
update game_event set description='元素生物 & 暮光之锤的入侵 ' where eventEntry=48;
update game_event set description='冬幕节:礼物 ' where eventEntry=49;
update game_event set description='四月 ' where eventEntry=53;
update game_event set description='六月 ' where eventEntry=55;
update game_event set description='七月 ' where eventEntry=56;
update game_event set description='八月 ' where eventEntry=57;
update game_event set description='九月 ' where eventEntry=58;
update game_event set description='十月 ' where eventEntry=59;
update game_event set description='十一月 ' where eventEntry=60;
update game_event set description='五月 ' where eventEntry=54;
update game_event set description='一月 ' where eventEntry=50;
update game_event set description='十二月 ' where eventEntry=61;
update game_event set description='世界的尽头旅店：佩里·盖特的公告 ' where eventEntry=62;
update game_event set description='世界的尽头旅店：佩里·盖特的表演 ' where eventEntry=63;
update game_event set description='冬季钓鱼大赛 ' where eventEntry=64;
update game_event set description='感恩节' where eventEntry=26;
