--
UPDATE `page_text` SET `Text`="To the Schneiders,$B$BGood day.  I trust business in the canal district is good.  We are booming here in the trader's square.$B$BWe are in need of knitted cloth goods, as our supply is all but depleted.  Please send the standard load as soon as you are able.$B$BGood fortune, and I hope your son Thurman's studies progress well,$B$B--Harlan Bagley" WHERE `ID`=336;
UPDATE `page_text` SET `Text`="Our first plan has already failed!$B$BFist was successful in switching the guard roster for the tunnel shifts that evening, but due to some unforeseen efforts by some of the citizens of Stormwind, our target was able to flee from the scene before we could capture him. But we planned for such contingencies. Plan 2 has been set in motion and was well under way before our ambush was set off in Stormwind." WHERE `ID`=580;
UPDATE `page_text` SET `Text`="Master Carevin,$B$BThe bearer of this note has shown $Ghimself:herself; to be upstanding in the Light, capable of battling the undead and demons that plague the borders of Duskwood, and willing to join the Carevin family in their cause of Light.$B$BI would thereby suggest that you give this warrior of the Light further duties--perhaps to investigate some of the townsfolk that are under suspicion of succor to the enemies of the Light.$B$BYours faithfully,$BCalor" WHERE `ID`=63;
UPDATE `page_text` SET `Text`="Okay, you should have your NG-5 charges and detonators ready. I've labeled them for you... Blue is for the lumber mill. Red is for Windshear Mine.$B$BI did some scouting, and there are enough explosives throughout Windshear Crag that it shouldn't be a problem at all for you to get in, plant the explosives, and then get out before detonating them.$B$BRemember, this is a distraction. Get far from the wagons before the goblins get there to check out what happened, then sneak in behind them." WHERE `ID`=417;
UPDATE `page_text` SET `Text`="Be careful with them by the way. The Nitromirglyceronium alone could reduce you to dust. I've encased some of the liquid in copper tubes which should keep it stable and safe.$B$BThe scroll you got from Collin I used on the detonator boxes. They will now send a silent message to the NG-5 charges after you've set them. I used a simple Stalthwargon mechanism to make sure the wire conductivity is optimal and the flow of the Nitroglyceronium between the differential fluid is better than average." WHERE `ID`=418;
UPDATE `page_text` SET `Text`="Before I get back into the details about my design, let me explain where you should place the explosives.$B$BPlan Alpha- the lumber mill:$BThere's a wagon out in front of the lumber mill (this is northeast of their deforestation and lumber collection construct). I suspect the engineering plans are inside of the lumber mill.$B$BTo plant the charge, head to the back of the wagon. Once it's set, make haste and get some distance." WHERE `ID`=419;
UPDATE `page_text` SET `Text`="When you're ready, hit the detonator.$B$BI've ensured a strong signal by routing copper and silver wires with a Melthusian antenae array within the casing of the box. That should give you good range. Just be careful of the goblins nearby. They won't appreciate my creation if they catch you in their site.$B$BOh, just in case it wasn't obvious, don't be near the wagon when it blows... it'll hurt." WHERE `ID`=420;
UPDATE `page_text` SET `Text`="Plan Beta- Windshear Mine:$B$BI saw the goblins using another wagon of explosives north of the mine's entrance. I think that should be a good enough place to plant NG-5 Charge (Red). After you set the charge in the back of the wagon, get some distance and hit the button.$B$BIf the goblins don't come running to check out the commotion, it's probably because the mountain came down on top of their heads." WHERE `ID`=421;
UPDATE `page_text` SET `Text`="The Venture Co. Letters are outside the mine... I think on some crates on the bottom level.$B$BGood luck, and remember...$B$BBlue Charge: lumber mill$BRed Charge: mine$B$BOh, and destroy this letter after you've accomplished your mission. Hmm, maybe I should look into a way to make these things destroy themselves after they're read. That's not a bad idea..." WHERE `ID`=422;
UPDATE `page_text` SET `Text`="Day 1:$B6am to 11am - upper camp$B11am to 11:30 am- break, lunch$B11:30am to 4:00pm - canyon pass$B4:00pm to 7:30pm - upper camp$B$BDay 2:$BSame schedule as day 1$B$BDay 3:$BSame schedule$B$BDay 4:$BSame schedule, with one exception.  Just before sunset, Thorsen had me cover for him as he crept down the canyon pass.  I assumed he went to meet with our agents.$B$BBut he returned an hour later.  This surprised me.  I had hoped he met with our agents and would rejoin Kurzen.  Something is wrong." WHERE `ID`=311;
UPDATE `page_text` SET `Text`="Day 5:$BThorsen was very agitated today.  Whatever he saw or whomever he met during his excursion yesterday must have scared him.$B$BI assumed our agents spoke with him, but when I asked Thorsen where he went while I covered for him, he remained quiet.  He believes I am his friend, and he believes he is protecting me from a dangerous secret.$B$BHis loyalties are misplaced, but they are strong.  When he rejoins us, he will be a valuable addition to Kurzen's forces." WHERE `ID`=312;
UPDATE `page_text` SET `Text`="Day 6:$BEarly in the morning, Thorsen spoke at length with Sergeant Yohwa.  I had to pretend I still slept and so was unable to move within earshot.  But I assume they spoke of Thorsen's earlier excursion.$B$BI watched him closely at lunch and noticed Yohwa doing the same.  Later, Doren summoned Thorsen.  The three of them share a secret.  Doren and Yohwa must know that Thorsen is meeting with your agents.$B$BHe is spying for the rebels." WHERE `ID`=313;
UPDATE `page_text` SET `Text`="We must give Thorsen no more intelligence, and we must kill him.  He is of no more use to our Colonel.$B$BI will put an end to Thorsen if given the opportunity, but if you receive this letter then you will know I have not yet had the chance.$B$BIn which case, I suggest Thorsen's next meeting with our agents is a fatal one.$B$BHail Kurzen,$B-M" WHERE `ID`=314;
