-- UPDATE `spell_dbc` SET `EffectTriggerSpell1`=30571 WHERE `Id`=30576;
UPDATE `serverside_spell_effect` SET `EffectTriggerSpell`=30576 WHERE `SpellID`=30576 AND `EffectIndex`=0 AND `DifficultyID`=0;
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_gen_restoration','spell_gen_nitrous_boost','spell_kelthuzad_frost_blast','spell_inoculate_nestlewood','spell_item_extract_gas','spell_alar_flame_quills','spell_item_absorb_eye_of_grillok','spell_sha_t3_8p_bonus','spell_pursuing_spikes',/*'spell_sha_mana_tide',*/'spell_gen_negative_energy_periodic','spell_jormungars_slime_pool',/*'spell_pal_beacon_of_light',*/'spell_silithus_summon_cultist_periodic');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(23493, 'spell_gen_restoration'),
(24379, 'spell_gen_restoration'),
(27746, 'spell_gen_nitrous_boost'),
(27808, 'spell_kelthuzad_frost_blast'),
(29528, 'spell_inoculate_nestlewood'),
(30427, 'spell_item_extract_gas'),
(34229, 'spell_alar_flame_quills'),
(38554, 'spell_item_absorb_eye_of_grillok'),
(28820, 'spell_sha_t3_8p_bonus'),
(65920, 'spell_pursuing_spikes'),
(65922, 'spell_pursuing_spikes'),
(65923, 'spell_pursuing_spikes'),
-- (16191, 'spell_sha_mana_tide'),
(46284, 'spell_gen_negative_energy_periodic'),
(66882, 'spell_jormungars_slime_pool'),
-- (53563, 'spell_pal_beacon_of_light'),
(24745, 'spell_silithus_summon_cultist_periodic'),
(24747, 'spell_silithus_summon_cultist_periodic'),
(24757, 'spell_silithus_summon_cultist_periodic'),
(24759, 'spell_silithus_summon_cultist_periodic'),
(24761, 'spell_silithus_summon_cultist_periodic'),
(24762, 'spell_silithus_summon_cultist_periodic'),
(24766, 'spell_silithus_summon_cultist_periodic'),
(24769, 'spell_silithus_summon_cultist_periodic'),
(24771, 'spell_silithus_summon_cultist_periodic'),
(24773, 'spell_silithus_summon_cultist_periodic'),
(24785, 'spell_silithus_summon_cultist_periodic'),
(24787, 'spell_silithus_summon_cultist_periodic'),
(24791, 'spell_silithus_summon_cultist_periodic'),
(24792, 'spell_silithus_summon_cultist_periodic'),
(24793, 'spell_silithus_summon_cultist_periodic'),
(46595, 'spell_silithus_summon_cultist_periodic');
