ALTER TABLE `creature`
  CHANGE `Type` `Type` MEDIUMINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `FemaleSubName`,
  ADD COLUMN `Family` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `Type`,
  CHANGE `Rank` `Classification` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL,
  CHANGE `InhabitType` `InhabitType` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL; 
