-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.33-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping structure for table trinitycore.command
DROP TABLE IF EXISTS `command`;
CREATE TABLE IF NOT EXISTS `command` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `permission` smallint(5) unsigned NOT NULL DEFAULT '0',
  `help` longtext,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Chat System';

-- Dumping data for table trinitycore.command: 629 rows
DELETE FROM `command`;
/*!40000 ALTER TABLE `command` DISABLE KEYS */;
INSERT INTO `command` (`name`, `permission`, `help`) VALUES
	('account create', 219, 'Syntax: .account create $account $password\r\n\r\nCreate account and set password to it.'),
	('account delete', 220, 'Syntax: .account delete $account\r\n\r\nDelete account with all characters.'),
	('account lock ip', 223, 'Syntax: .account lock ip [on|off]\nAllow login from account only from current used IP or remove this requirement.'),
	('account onlinelist', 224, 'Syntax: .account onlinelist\r\n\r\nShow list of online accounts.'),
	('account password', 225, 'Syntax: .account password $old_password $new_password $new_password [$email]\r\n\r\nChange your account password. You may need to check the actual security mode to see if email input is necessary.'),
	('account set addon', 227, 'Syntax: .account set addon [$account] #addon\n\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata, 4 - mop, 5 - wod, 6 - legion.'),
	('account set gmlevel', 228, 'Syntax: .account set gmlevel [$accountName] #level [#realmID]\n\nSet the security level for targeted player (can\'t be used at self) or for account $accountName to a level of #level on the realm #realmID.\n\n#level may range from 0 to 3.\n\n#realmID - Default: -1 for all realms.\n\nNote: this command will be removed soon. Use \'account set seclevel\' instead.'),
	('account set password', 229, 'Syntax: .account set password $account $password $password\r\n\r\nSet password for account.'),
	('account set', 226, 'Syntax: .account set $subcommand\nType .account set to see the list of possible subcommands or .help account set $subcommand to see info on subcommands'),
	('account', 217, 'Syntax: .account\r\n\r\nDisplay the access level of your account and the email adress if you possess the necessary permissions.'),
	('additem', 488, 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount #bonusListIDs\n\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added. #bonusListIDs is a semicolon separated list of bonuses to add to item (such as Mythic/Heroic/Warforged/socket)'),
	('additemset', 489, 'Syntax: .additemset #itemsetid #bonusListIDs\n\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.\n\nIf the itemset has multiple levels it adds one of each item level. #bonusListIDs is a semicolon separated list of bonuses to add to all items (such as Mythic/Heroic/Warforged/socket)'),
	('announce', 462, 'Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log.'),
	('aura', 491, 'Syntax: .aura #spellid\r\n\r\nAdd the aura from spell #spellid to the selected Unit.'),
	('ban account', 240, 'Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban character', 241, 'Syntax: .ban character $Name $bantime $reason\nBan character and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban ip', 242, 'Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban', 239, 'Syntax: .ban $subcommand\nType .ban to see the list of possible subcommands or .help ban $subcommand to see info on subcommands'),
	('baninfo account', 245, 'Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban.'),
	('baninfo character', 246, 'Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban.'),
	('baninfo ip', 247, 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban.'),
	('baninfo', 244, 'Syntax: .baninfo $subcommand\nType .baninfo to see the list of possible subcommands or .help baninfo $subcommand to see info on subcommands'),
	('bank', 492, 'Syntax: .bank\r\n\r\nShow your bank inventory.'),
	('banlist account', 249, 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.'),
	('banlist character', 250, 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required.'),
	('banlist ip', 251, 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.'),
	('banlist', 248, 'Syntax: .banlist $subcommand\nType .banlist to see the list of possible subcommands or .help banlist $subcommand to see info on subcommands'),
	('bindsight', 493, 'Syntax: .bindsight\r\n\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.'),
	('cast back', 268, 'Syntax: .cast back #spellid [triggered]\r\n  Selected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast dist', 269, 'Syntax: .cast dist #spellid [#dist [triggered]]\r\n  You will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.'),
	('cast self', 270, 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast target', 271, 'Syntax: .cast target #spellid [triggered]\r\n  Selected target will cast #spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast', 267, 'Syntax: .cast #spellid [triggered]\r\n  Cast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('character customize', 274, 'Syntax: .character customize [$name]\r\n\r\nMark selected in game or by $name in command character for customize at next login.'),
	('character erase', 282, 'Syntax: .character erase $name\r\n\r\nDelete character $name. Character finally deleted in case any deleting options.'),
	('character level', 283, 'Syntax: .character level [$playername] [#level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.'),
	('character rename', 284, 'Syntax: .character rename [$name] [$newName] \n\nMark selected in game or by $name in command character for rename at next login.\n\nIf $newName then the player will be forced rename.'),
	('character reputation', 285, 'Syntax: .character reputation [$player_name]\r\n\r\nShow reputation information for selected player or player find by $player_name.'),
	('combatstop', 494, 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.'),
	('cometome', 495, 'Syntax: .cometome\nMake selected creature come to your current location (new position not saved to DB).'),
	('commands', 496, 'Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level.'),
	('cooldown', 497, 'Syntax: .cooldown [#spell_id]\r\n\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or their pet or you (if no selection).'),
	('damage', 498, 'Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.'),
	('debug arena', 303, 'Syntax: .debug arena\r\n\r\nToggle debug mode for arenas. In debug mode GM can start arena with single player.'),
	('debug bg', 304, 'Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.'),
	('debug play cinematic', 316, 'Syntax: .debug play cinematic #cinematicid\r\n\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.\r\n'),
	('debug play movie', 317, 'Syntax: .debug play movie #movieid\r\n\r\nPlay movie #movieid for you.'),
	('debug play sound', 318, 'Syntax: .debug play sound #soundid\r\n\r\nPlay sound with #soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...'),
	('debug', 300, 'Syntax: .debug $subcommand\nType .debug to see the list of possible subcommands or .help debug $subcommand to see info on subcommands'),
	('demorph', 543, 'Syntax: .demorph\r\n\r\nDemorph the selected player.'),
	('die', 500, 'Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you.'),
	('dismount', 501, 'Syntax: .dismount\r\n\r\nDismount you, if you are mounted.'),
	('distance', 502, 'Syntax: .distance\r\n\r\nDisplay the distance from your character to the selected creature.'),
	('event activelist', 368, 'Syntax: .event activelist\r\nShow list of currently active events.'),
	('event start', 369, 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).'),
	('event stop', 370, 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).'),
	('event info', 367, 'Syntax: .event info #event_id\r\nShow details about event with #event_id.'),
	('cheat cooldown', 293, 'Syntax: .cheat cooldown [on/off]\r\nEnables or disables your character\'s spell cooldowns.'),
	('cheat power', 296, 'Syntax: .cheat power [on/off]\r\nEnables or disables your character\'s spell cost (e.g mana).'),
	('freeze', 504, 'Syntax: .freeze [#player] [#duration]\nFreezes #player for #duration (seconds)\nFreezes the selected player if no arguments are given.\nDefault duration: GM.FreezeAuraDuration (worldserver.conf)'),
	('gm chat', 372, 'Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided.'),
	('gm fly', 373, 'Syntax: .gm fly [on/off]\r\nEnable/disable gm fly mode.'),
	('gm ingame', 374, 'Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters.'),
	('gm list', 375, 'Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels.'),
	('gm visible', 376, 'Syntax: .gm visible on/off\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.'),
	('gm', 371, 'Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided.'),
	('gmannounce', 466, 'Syntax: .gmannounce $announcement\r\nSend an announcement to online Gamemasters.'),
	('gmnameannounce', 467, 'Syntax: .gmnameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.'),
	('gmnotify', 468, 'Syntax: .gmnotify $notification\r\nDisplays a notification on the screen of all online GM\'s.'),
	('go creature', 378, 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.'),
	('go graveyard', 379, 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.'),
	('go grid', 380, 'Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).'),
	('go object', 381, 'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid'),
	('go taxinode', 382, 'Syntax: .go taxinode #taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart'),
	('go trigger', 384, 'Syntax: .go trigger #trigger_id\r\n\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.'),
	('go xyz', 385, 'Syntax: .go xyz #x #y [#z [#mapid [#orientation]]]\r\n\r\nTeleport player to point with (#x,#y,#z) coordinates at map #mapid with orientation #orientation. If z is not provided, ground/water level will be used. If mapid is not provided, the current map will be used. If #orientation is not provided, the current orientation will be used.'),
	('go zonexy', 386, 'Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart'),
	('go offset', 852, 'Syntax: .go offset [x[ y[ z[ o]]]]\nTeleports the player by given offset from his current coordinates.'),
	('gobject activate', 388, 'Syntax: .gobject activate #guid\r\n\r\nActivates an object like a door or a button.'),
	('gobject add', 389, 'Syntax: .gobject add #id <spawntimeSecs>\r\n\r\nAdd a game object from game object templates to the world at your current location using the #id.\r\nspawntimesecs sets the spawntime, it is optional.\r\n\r\nNote: this is a copy of .gameobject.'),
	('gobject delete', 391, 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.'),
	('gobject move', 393, 'Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).'),
	('gobject near', 394, 'Syntax: .gobject near  [#distance]\r\n\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.'),
	('gobject add temp', 390, 'Adds a temporary gameobject that is not saved to DB.'),
	('gobject target', 398, 'Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.'),
	('gobject set phase', 396, 'Syntax: .gobject set phase #guid #phasemask\r\n\r\nGameobject with DB guid #guid phasemask changed to #phasemask with related world vision update for players. Gameobject state saved to DB and persistent.'),
	('gobject turn', 399, 'Syntax: .gobject turn [guid|link] [oz [oy [ox]]]\r\n\r\nSet the orientation of the gameobject to player\'s orientation or the given orientation.'),
	('gobject', 387, 'Syntax: .gobject $subcommand\nType .gobject to see the list of possible subcommands or .help gobject $subcommand to see info on subcommands'),
	('summon', 528, 'Syntax: .summon [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline.'),
	('gps', 505, 'Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id'),
	('group summon', 478, 'Syntax: .group summon [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline.'),
	('guid', 506, 'Syntax: .guid\r\n\r\nDisplay the GUID for the selected character.'),
	('guild create', 402, 'Syntax: .guild create [$GuildLeaderName] "$GuildName"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes.'),
	('guild delete', 403, 'Syntax: .guild delete "$GuildName"\r\n\r\nDelete guild $GuildName. Guild name must in quotes.'),
	('guild invite', 404, 'Syntax: .guild invite [$CharacterName] "$GuildName"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes.'),
	('guild rank', 406, 'Syntax: .guild rank [$CharacterName] #Rank\r\n\r\nSet for player $CharacterName (or selected) rank #Rank in a guild.'),
	('guild uninvite', 405, 'Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild.'),
	('guild', 401, 'Syntax: .guild $subcommand\nType .guild to see the list of possible subcommands or .help guild $subcommand to see info on subcommands'),
	('help', 507, 'Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.'),
	('hidearea', 508, 'Syntax: .hidearea #areaid\r\n\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.'),
	('honor add', 409, 'Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained today) to the selected player.'),
	('honor add kill', 410, 'Syntax: .honor add kill\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)'),
	('honor update', 411, 'Syntax: .honor update\r\n\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.'),
	('honor', 408, 'Syntax: .honor $subcommand\nType .honor to see the list of possible subcommands or .help honor $subcommand to see info on subcommands'),
	('modify talentpoints', 569, 'Syntax: .modify talentpoints #amount\r\n\r\nSet free talent points for selected character or character\'s pet. It will be reset to default expected at next levelup/login/quest reward.'),
	('instance listbinds', 413, 'Syntax: .instance listbinds\r\n  Lists the binds of the selected player.'),
	('instance savedata', 416, 'Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB.'),
	('instance stats', 415, 'Syntax: .instance stats\r\n  Shows statistics about instances.'),
	('instance unbind', 414, 'Syntax: .instance unbind <mapid|all> [difficulty]\r\n  Clear all/some of player\'s binds'),
	('instance', 412, 'Syntax: .instance $subcommand\nType .instance to see the list of possible subcommands or .help instance $subcommand to see info on subcommands'),
	('itemmove', 509, 'Syntax: .itemmove #sourceslotid #destinationslotid\r\n\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\n\r\nNot yet implemented'),
	('kick', 510, 'Syntax: .kick [$charactername] [$reason]\r\n\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is "No Reason".'),
	('learn all my talents', 423, 'Syntax: .learn all my talents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class.'),
	('learn all my spells', 422, 'Syntax: .learn all my spells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.'),
	('learn all my pettalents', 421, 'Syntax: .learn all my pettalents\r\n\r\nLearn all talents for your pet available for his creature type (only for hunter pets).'),
	('learn all my class', 420, 'Syntax: .learn all my class\r\n\r\nLearn all spells and talents available for his class.'),
	('learn all gm', 424, 'Syntax: .learn all gm\r\n\r\nLearn all default spells for Game Masters.'),
	('learn all lang', 427, 'Syntax: .learn all lang\r\n\r\nLearn all languages'),
	('learn all default', 426, 'Syntax: .learn all default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.'),
	('learn', 417, 'Syntax: .learn #spell [all]\r\n\r\nSelected character learn a spell of id #spell. If \'all\' provided then all ranks learned.'),
	('modify scale', 560, '.modify scale #scale\nModify size of the selected player or creature to "normal scale"*rate. If no player or creature is selected, modify your size.\n#rate may range from 0.1 to 10.'),
	('learn all crafts', 425, 'Syntax: .learn crafts\r\n\r\nLearn all professions and recipes.'),
	('levelup', 287, 'Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.'),
	('linkgrave', 511, 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).'),
	('list auras', 440, 'Syntax: .list auras\nList auras (passive and active) of selected creature or player. If no creature or player is selected, list your own auras.'),
	('list creature', 437, 'Syntax: .list creature #creature_id [#max_count]\r\n\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.'),
	('list item', 438, 'Syntax: .list item #item_id [#max_count]\r\n\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.'),
	('list object', 439, 'Syntax: .list object #gameobject_id [#max_count]\r\n\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.'),
	('list', 436, 'Syntax: .list $subcommand\nType .list to see the list of possible subcommands or .help list $subcommand to see info on subcommands'),
	('listfreeze', 512, 'Syntax: .listfreeze\r\n\r\nSearch and output all frozen players.'),
	('wp reload', 773, 'Syntax: .wp reload $pathid\nLoad path changes ingame - IMPORTANT: must be applied first for new paths before .wp load #pathid '),
	('reload spell_group', 693, 'Syntax: .reload spell_group\nReload spell_group table.'),
	('lookup area', 443, 'Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.'),
	('lookup creature', 444, 'Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.'),
	('lookup event', 445, 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.'),
	('lookup faction', 446, 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.'),
	('lookup item', 447, 'Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.'),
	('lookup itemset', 448, 'Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.'),
	('lookup map', 461, 'Syntax: .lookup map $namepart\r\n\r\nLooks up a map by $namepart, and returns all matches with their map ID\'s.'),
	('lookup object', 449, 'Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.'),
	('lookup player account', 453, 'Syntax: .lookup player account $account ($limit) \r\n\r\n Searchs players, which account username is $account with optional parametr $limit of results.'),
	('lookup player email', 454, 'Syntax: .lookup player email $email ($limit) \r\n\r\n Searchs players, which account email is $email with optional parametr $limit of results.'),
	('lookup player ip', 452, 'Syntax: .lookup player ip $ip ($limit) \r\n\r\n Searchs players, which account ast_ip is $ip with optional parametr $limit of results.'),
	('lookup quest', 450, 'Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.'),
	('lookup skill', 455, 'Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.'),
	('lookup spell', 456, 'Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.'),
	('lookup taxinode', 458, 'Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name.'),
	('lookup tele', 459, 'Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name.'),
	('lookup', 442, 'Syntax: .lookup $subcommand\nType .lookup to see the list of possible subcommands or .help lookup $subcommand to see info on subcommands'),
	('group set leader', 473, 'Syntax: .group set leader [$characterName]\n\nSets the given character (or selected) as his group\'s leader. Alias for \'.group leader\'.'),
	('modify speed walk', 565, 'Syntax: .modify speed bwalk #rate\r\n\r\nModify the speed of the selected player while running to "normal walk speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.'),
	('modify speed swim', 566, 'Syntax: .modify speed swim #rate\r\n\r\nModify the swim speed of the selected player to "normal swim speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.'),
	('modify drunk', 547, 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.'),
	('modify energy', 548, 'Syntax: .modify energy #energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy.'),
	('modify faction', 549, 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.'),
	('modify speed fly', 564, '.modify speed fly #rate\nModify the flying speed of the selected player to "normal flying speed"*rate. If no player is selected, modify your speed.\n #rate may range from 0.1 to 50.'),
	('modify gender', 550, 'Syntax: .modify gender male/female\r\n\r\nChange gender of selected player.'),
	('modify honor', 551, 'Syntax: .modify honor $amount\r\n\r\nAdd $amount honor points to the selected player.'),
	('modify hp', 552, 'Syntax: .modify hp #newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp.'),
	('modify mana', 553, 'Syntax: .modify mana #newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana.'),
	('modify money', 554, 'Syntax: .modify money #money\r\n.money #money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n #gold can be negative to remove money.'),
	('modify mount', 555, 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.'),
	('modify phase', 556, 'Syntax: .modify phase #phasemask\r\n\r\nSelected character phasemask changed to #phasemask with related world vision update. Change active until in game phase changed, or GM-mode enable/disable, or re-login. Character pts pasemask update to same value.'),
	('modify rage', 557, 'Syntax: .modify rage #newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage.'),
	('modify reputation', 558, 'Syntax: .modify reputation #repId (#repvalue | $rankname [#delta])\nSets the selected players reputation with faction #repId to #repvalue or to $reprank.\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.'),
	('modify runicpower', 559, 'Syntax: .modify runicpower #newrunicpower\r\n\r\nModify the runic power of the selected player. If no player is selected, modify your runic power.'),
	('modify speed', 561, 'Syntax: .modify speed $speedtype #rate\r\n\r\nModify the running speed of the selected player to "normal base run speed"= 1. If no player is selected, modify your speed.\r\n\r\n$speedtypes may be fly, all, walk, backwalk, or swim.\r\n\r\n #rate may range from 0.1 to 50.'),
	('modify spell', 567, 'TODO'),
	('modify standstate', 568, 'Syntax: .modify standstate #emoteid\r\n\r\nChange the emote of your character while standing to #emoteid.'),
	('modify speed backwalk', 563, 'Syntax: .modify speed backwalk #rate\r\n\r\nModify the speed of the selected player while running backwards to "normal walk back speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.'),
	('character titles', 286, 'Syntax: .character titles [$player_name]\r\n\r\nShow known titles list for selected player or player find by $player_name.'),
	('modify speed all', 562, 'Syntax: .modify aspeed #rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to "normalbase speed for this move type"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.'),
	('modify', 544, 'Syntax: .modify $subcommand\nType .modify to see the list of possible subcommands or .help modify $subcommand to see info on subcommands'),
	('movegens', 514, 'Syntax: .movegens\r\n  Show movement generators stack for selected creature or player.'),
	('mute', 515, 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.'),
	('nameannounce', 469, 'Syntax: .nameannounce $announcement.\nSend an announcement to all online players, displaying the name of the sender.'),
	('appear', 490, 'Syntax: .appear [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait,e.g. when you are in a group. Character can be offline.'),
	('neargrave', 516, 'Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).'),
	('notify', 470, 'Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen.'),
	('npc set phase', 589, 'Syntax: .npc set phase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..'),
	('npc set movetype', 588, 'Syntax: .npc set movetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.'),
	('npc set model', 587, 'Syntax: .npc set model #displayid\r\n\r\nChange the model id of the selected creature to #displayid.'),
	('npc set link', 586, 'Syntax: .npc set link $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.'),
	('wpgps', 340, 'Syntax: .wpgps\n\nOutput current position to sql developer log as partial SQL query to be used in pathing'),
	('npc say', 597, 'Syntax: .npc say $message\nMake selected creature say specified message.'),
	('npc move', 595, 'Syntax: .npc move [#creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates.'),
	('npc playemote', 596, 'Syntax: .npc playemote #emoteid\r\n\r\nMake the selected creature emote with an emote of id #emoteid.'),
	('npc follow stop', 579, 'Syntax: .npc follow stop\r\n\r\nSelected creature (non pet) stop follow you.'),
	('npc info', 593, 'Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.'),
	('npc follow', 578, 'Syntax: .npc follow start\r\n\r\nSelected creature start follow you until death/fight/etc.'),
	('npc set flag', 584, 'Syntax: .npc set flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.'),
	('npc set factionid', 583, 'Syntax: .npc set factionid #factionid\r\n\r\nSet the faction of the selected creature to #factionid.'),
	('npc set level', 585, 'Syntax: .npc set level #level\r\n\r\nChange the level of the selected creature to #level.\r\n\r\n#level may range from 1 to (CONFIG_MAX_PLAYER_LEVEL) + 3.'),
	('npc delete', 576, 'Syntax: .npc delete [#guid]\r\n\r\nDelete creature with guid #guid (or the selected if no guid is provided)'),
	('npc delete item', 577, 'Syntax: .npc delete item #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.'),
	('npc set allowmove', 581, 'Syntax: .npc set allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.'),
	('npc set entry', 582, 'Syntax: .npc set entry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.'),
	('npc add move', 574, 'Syntax: .npc add move #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.'),
	('npc add item', 573, 'Syntax: .npc add item #itemId <#maxcount><#incrtime><#extendedcost><#bonusListIDs>\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.\r\n#bonusListIDs is a semicolon separated list of bonuses to add to item (such as Mythic/Heroic/Warforged/socket)'),
	('npc add formation', 572, 'Syntax: .npc add formation $leader\nAdd selected creature to a leader\'s formation.'),
	('npc', 570, 'Syntax: .npc $subcommand\nType .npc to see the list of possible subcommands or .help npc $subcommand to see info on subcommands'),
	('pdump load', 289, 'Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid.'),
	('pdump write', 290, 'Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename.'),
	('pdump', 288, 'Syntax: .pdump $subcommand\nType .pdump to see the list of possible subcommands or .help pdump $subcommand to see info on subcommands'),
	('pet create', 480, 'Syntax: .pet create\r\n\r\nCreates a pet of the selected creature.'),
	('pet learn', 481, 'Syntax: .pet learn\r\n\r\nLearn #spellid to pet.'),
	('reload spell_proc', 699, 'Syntax: .reload spell_proc\nReload spell_proc table.'),
	('pet unlearn', 482, 'Syntax: .pet unlean\r\n\r\nunLearn #spellid to pet.'),
	('pet', 479, 'Syntax: .pet $subcommand\nType .pet to see the list of possible subcommands or .help pet $subcommand to see info on subcommands'),
	('pinfo', 517, 'Syntax: .pinfo [$player_name/#GUID]\r\n\r\nOutput account information and guild information for selected player or player find by $player_name or #GUID.'),
	('playall', 518, 'Syntax: .playall #soundid\r\n\r\nPlayer a sound to whole server.'),
	('possess', 519, 'Syntax: .possess\r\n\r\nPossesses indefinitely the selected creature.'),
	('quest add', 603, 'Syntax: .quest add #quest_id\r\n\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.'),
	('quest complete', 604, 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.'),
	('quest remove', 605, 'Syntax: .quest remove #quest_id\r\n\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.'),
	('quest', 602, 'Syntax: .quest $subcommand\nType .quest to see the list of possible subcommands or .help quest $subcommand to see info on subcommands'),
	('recall', 520, 'Syntax: .recall [$playername]\r\n\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.'),
	('reload all quest', 620, 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.'),
	('reload all npc', 619, 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.'),
	('reload all loot', 618, 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.'),
	('reload all item', 616, 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.'),
	('reload all locales', 617, 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.'),
	('reload all gossips', 615, 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.'),
	('reload all', 611, 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.'),
	('reload areatrigger_involvedrelation', 623, 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.'),
	('reload areatrigger_tavern', 624, 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.'),
	('reload areatrigger_teleport', 625, 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.'),
	('reload autobroadcast', 627, 'Syntax: .reload autobroadcast\nReload autobroadcast table.'),
	('reload command', 628, 'Syntax: .reload command\nReload command table.'),
	('reload config', 630, 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.'),
	('reload creature_summon_groups', 638, 'Syntax: .reload creature_summon_groups\nReload creature_summon_groups table.'),
	('reload creature_queststarter', 637, 'Syntax: .reload creature_queststarter\nReload creature_queststarter table.'),
	('reload creature_questender', 636, 'Syntax: .reload creature_questender\nReload creature_questender table.'),
	('reload disenchant_loot_template', 642, 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.'),
	('reload event_scripts', 643, 'Syntax: .reload event_scripts\nReload event_scripts table.'),
	('reload fishing_loot_template', 644, 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.'),
	('reload graveyard_zone', 645, 'Syntax: .reload graveyard_zone\nReload graveyard_zone table.'),
	('reload game_tele', 646, 'Syntax: .reload game_tele\nReload game_tele table.'),
	('reload gameobject_loot_template', 648, 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.'),
	('reload gameobject_queststarter', 649, 'Syntax: .reload gameobject_queststarter\nReload gameobject_queststarter table.'),
	('reload support', 650, 'Syntax: .reload support\r\nReload support system tables.'),
	('reload item_random_bonus_list_template', 653, 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.'),
	('reload item_loot_template', 654, 'Syntax: .reload item_loot_template\nReload item_loot_template table.'),
	('reload creature_template_locale', 658, 'Syntax: .reload creature_template_locale\nReload creature_template_locale table.'),
	('reload gameobject_template_locale', 660, 'Syntax: .reload gameobject_template_locale\nReload gameobject_template_locale table.'),
	('ticket bug assign', 805, 'Usage: .ticket bug assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.'),
	('reload quest_greeting', 843, 'Syntax: .reload quest_greeting\nReload quest_greeting table.'),
	('reload page_text_locale', 665, 'Syntax: .reload page_text_locale\nReload page_text_locale table.'),
	('reload points_of_interest_locale', 666, 'Syntax: .reload points_of_interest_locale\nReload points_of_interest_locale table.'),
	('reload quest_locale', 667, 'Syntax: .reload quest_locale\nReload all quest_*_locale tables.'),
	('reload milling_loot_template', 670, 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.'),
	('reload trainer', 672, 'Syntax: .reload trainer\nReloads trainer, trainer_locale and trainer_spell tables.'),
	('reload npc_vendor', 673, 'Syntax: .reload npc_vendor\nReload npc_vendor table.'),
	('reload page_text', 674, 'Syntax: .reload page_text\nReload page_text table.'),
	('reload pickpocketing_loot_template', 675, 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.'),
	('reload points_of_interest', 676, 'Syntax: .reload points_of_interest\nReload points_of_interest table.'),
	('reload prospecting_loot_template', 677, 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.'),
	('lookup spell id', 457, 'Syntax: .lookup spell id #spellid\n\nLooks up a spell by #spellid, and returns the match with its spell name.'),
	('reload mail_loot_template', 669, 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.'),
	('reload quest_template', 679, 'Syntax: .reload quest_template\nReload quest_template table.'),
	('reload reference_loot_template', 681, 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.'),
	('reload reserved_name', 682, 'Syntax: .reload reserved_name\nReload reserved_name table.'),
	('reload skill_discovery_template', 685, 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.'),
	('reload skill_extra_item_template', 686, 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.'),
	('reload skill_fishing_base_level', 687, 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.'),
	('reload skinning_loot_template', 688, 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.'),
	('reload spell_area', 691, 'Syntax: .reload spell_area\nReload spell_area table.'),
	('ticket bug close', 806, 'Usage: .ticket bug close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.'),
	('reload disables', 641, 'Syntax: .reload disables\r\nReload disables table.'),
	('reload spell_group_stack_rules', 703, 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.'),
	('reload spell_learn_spell', 694, 'Syntax: .reload spell_learn_spell\nReload spell_learn_spell table.'),
	('reload spell_linked_spell', 696, 'Usage: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.'),
	('reload spell_loot_template', 695, 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.'),
	('reload spell_pet_auras', 697, 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.'),
	('character changeaccount', 698, 'Syntax: .character changeaccount [$player] $account\n\nTransfers ownership of named (or selected) character to another account'),
	('reload spell_required', 690, 'Syntax: .reload spell_required\nReload spell_required table.'),
	('reload spell_scripts', 700, 'Syntax: .reload spell_scripts\nReload spell_scripts table.'),
	('reload spell_target_position', 701, 'Syntax: .reload spell_target_position\nReload spell_target_position table.'),
	('reload spell_threats', 702, 'Syntax: .reload spell_threats\nReload spell_threats table.'),
	('reload trinity_string', 704, 'Syntax: .reload trinity_string\nReload trinity_string table.'),
	('reload waypoint_scripts', 706, 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.'),
	('reload', 607, 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands'),
	('repairitems', 521, 'Syntax: .repairitems\r\n\r\nRepair all selected player\'s items.'),
	('reset achievements', 711, 'Syntax: .reset achievements [$playername]\r\n\r\nReset achievements data for selected or named (online or offline) character. Achievements for persistance progress data like completed quests/etc re-filled at reset. Achievements for events like kills/casts/etc will lost.'),
	('reset all', 717, 'Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nRequest reset spells or talents (including talents for all character\'s pets if any) at next login each existed character.'),
	('reset honor', 712, 'Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character.'),
	('reset level', 713, 'Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.'),
	('reset spells', 714, 'Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character.'),
	('reset stats', 715, 'Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level.'),
	('reset talents', 716, 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player or pet or named player. Playername can be name of offline character. With player talents also will be reset talents for all character\'s pets if any.'),
	('reset', 710, 'Syntax: .reset $subcommand\nType .reset to see the list of possible subcommands or .help reset $subcommand to see info on subcommands'),
	('respawn', 522, 'Syntax: .respawn\r\n\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.'),
	('revive', 523, 'Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you.'),
	('save', 525, 'Syntax: .save\r\n\r\nSaves your character.'),
	('saveall', 524, 'Syntax: .saveall\r\n\r\nSave all characters in game.'),
	('send items', 484, 'Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.'),
	('send mail', 485, 'Syntax: .send mail #playername "#subject" "#text"\r\n\r\nSend a mail to a player. Subject and mail text must be in "".'),
	('send message', 486, 'Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR.'),
	('send money', 487, 'Syntax: .send money #playername "#subject" "#text" #money\r\n\r\nSend mail with money to a player. Subject and mail text must be in "".'),
	('server corpses', 719, 'Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world.'),
	('server exit', 720, 'Syntax: .server exit\r\n\r\nTerminate trinity-core NOW. Exit code 0.'),
	('server idlerestart cancel', 722, 'Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server idlerestart', 721, 'Syntax: .server idlerestart #delay [#exit_code] [reason]\n\nRestart the server after #delay seconds if no active connections are present (no players). Use #exit_code or 2 as program exit code.'),
	('server idleshutdown cancel', 724, 'Syntax: .server idleshutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server idleshutdown', 723, 'Syntax: .server idleshutdown #delay [#exit_code] [reason]\n\nShut the server down after #delay seconds if no active connections are present (no players). Use #exit_code or 0 as program exist code.'),
	('server info', 725, 'Syntax: .server info\r\n\r\nDisplay server version and the number of connected players.'),
	('server motd', 736, 'Syntax: .server motd\r\n\r\nShow server Message of the day.'),
	('server plimit', 726, 'Syntax: .server plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file'),
	('server restart cancel', 728, 'Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server restart', 727, 'Syntax: .server restart [force] #delay [#exit_code] [reason]\n\nRestart the server after #delay seconds. Use #exit_code or 2 as program exit code. Specify \'force\' to allow short-term shutdown despite other players being connected.'),
	('server set closed', 730, 'Syntax: server set closed on/off\r\n\r\nSets whether the world accepts new client connectsions.'),
	('server set motd', 733, 'Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day.'),
	('server shutdown cancel', 735, 'Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server shutdown', 734, 'Syntax: .server shutdown [force] #delay [#exit_code] [reason]\n\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code. Specify \'force\' to allow short-term shutdown despite other players being connected.'),
	('server', 718, 'Syntax: .server $subcommand\nType .server to see the list of possible subcommands or .help server $subcommand to see info on subcommands'),
	('setskill', 526, 'Syntax: .setskill #skill #level [#max]\r\n\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.'),
	('showarea', 527, 'Syntax: .showarea #areaid\r\n\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.'),
	('unstuck', 534, 'Syntax: .unstuck $playername [inn/graveyard/startzone]\n\nTeleports specified player to specified location. Default location is player\'s current hearth location.'),
	('cheat god', 295, 'Syntax: .cheat god [on/off]\r\nEnables or disables your character\'s ability to take damage.'),
	('cheat casttime', 292, 'Syntax: .cheat casttime [on/off]\r\nEnables or disables your character\'s spell cast times.'),
	('tele add', 738, 'Syntax: .tele add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name.'),
	('tele del', 739, 'Syntax: .tele del $name\r\n\r\nRemove location with name $name for .tele command locations list.'),
	('tele group', 741, 'Syntax: .tele group#location\r\n\r\nTeleport a selected player and his group members to a given location.'),
	('tele name', 740, 'Syntax: .tele name [#playername] #location\n\nTeleport the given character to a given location. Character can be offline.\n\nTo teleport to homebind, set #location to "$home" (without quotes).'),
	('tele', 737, 'Syntax: .tele #location\r\n\r\nTeleport player to a given location.'),
	('ticket', 742, 'Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands'),
	('unaura', 529, 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.'),
	('unban account', 253, 'Syntax: .unban account $Name\r\nUnban accounts for account name pattern.'),
	('unban character', 254, 'Syntax: .unban character $Name\r\nUnban accounts for character name pattern.'),
	('unban ip', 255, 'Syntax : .unban ip $Ip\r\nUnban accounts for IP pattern.'),
	('unban', 252, 'Syntax: .unban $subcommand\nType .unban to see the list of possible subcommands or .help unban $subcommand to see info on subcommands'),
	('unbindsight', 530, 'Syntax: .unbindsight\r\n\r\nRemoves bound vision. Cannot be used while currently possessing a target.'),
	('unfreeze', 531, 'Syntax: .unfreeze (#player)\r\n"Unfreezes" #player and enables his chat again. When using this without #name it will unfreeze your target.'),
	('unlearn', 429, 'Syntax: .unlearn #spell [all]\r\n\r\nUnlearn for selected player a spell #spell.  If \'all\' provided then all ranks unlearned.'),
	('unmute', 532, 'Syntax: .unmute [$playerName]\r\n\r\nRestore chat messaging for any character from account of character $playerName (or selected). Character can be ofline.'),
	('unpossess', 533, 'Syntax: .unpossess\r\n\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.'),
	('cheat', 291, 'Syntax: .cheat $subcommand\r\nType .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands'),
	('wchange', 535, 'Syntax: .wchange #weathertype #status\r\n\r\nSet current weather to #weathertype with an intensity of #status.\r\n\r\n#weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.'),
	('whispers', 471, 'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.'),
	('wp event', 769, 'Syntax: .wp event $subcommand\nType .path event to see the list of possible subcommands or .help path event $subcommand to see info on subcommands.'),
	('wp load', 770, 'Syntax: .wp load $pathid\nLoad pathid number for selected creature. Creature must have no waypoint data.'),
	('wp show', 774, 'Syntax: .wp show $option\nOptions:\non $pathid (or selected creature with loaded path) - Show path\nfirst $pathid (or selected creature with loaded path) - Show first waypoint in path\nlast $pathid (or selected creature with loaded path) - Show last waypoint in path\noff - Hide all paths\ninfo $selected_waypoint - Show info for selected waypoint.'),
	('wp unload', 772, 'Syntax: .wp unload\nUnload path for selected creature.'),
	('account addon', 218, 'Syntax: .account addon #addon\n\nSet expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata, 4 - mop, 5 - wod, 6 - legion.'),
	('titles remove', 764, 'Syntax: .titles remove #title\r\nRemove title #title (id or shift-link) from known titles list for selected player.'),
	('titles current', 763, 'Syntax: .titles current #title\r\nSet title #title (id or shift-link) as current selected title for selected player. If title is not in known title list for player then it will be added to list.'),
	('titles add', 762, 'Syntax: .titles add #title\r\nAdd title #title (id or shift-link) to known titles list for selected player.'),
	('titles set mask', 766, 'Syntax: .titles set mask #mask\r\n\r\nAllows user to use all titles from #mask.\r\n\r\n #mask=0 disables the title-choose-field'),
	('lookup title', 460, 'Syntax: .lookup title $$namepart\r\n\r\nLooks up a title by $namepart, and returns all matches with their title ID\'s and index\'s.'),
	('channel set ownership', 465, 'Syntax: .channel set ownership $channel [on/off]\n\nGrant ownership to the first person that joins the channel.'),
	('gobject info', 392, 'Syntax: .gobject info [$entry|$link | guid [$guid|$link]\r \r Query Gameobject information for given gameobject entry, guid or link.\rFor example .gobject info 36\ror .gobject info guid 100'),
	('reload creature_onkill_reputation', 635, 'Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table.'),
	('character deleted delete', 278, 'Syntax: .character deleted delete #guid|$name\r\n\r\nCompletely deletes the selected characters.\r\nIf $name is supplied, only characters with that string in their name will be deleted, if #guid is supplied, only the character with that GUID will be deleted.'),
	('reload creature_loot_template', 634, 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.'),
	('reload conditions', 629, 'Reload conditions table.'),
	('character deleted list', 279, 'Syntax: .character deleted list [#guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if #guid is supplied, only the character with that GUID will be selected.'),
	('character deleted old', 281, 'Syntax: .character deleted old [#keepDays]\r\n\r\nCompletely deletes all characters with deleted time longer #keepDays. If #keepDays not provided the  used value from mangosd.conf option \'CharDelete.KeepDays\'. If referenced config option disabled (use 0 value) then command can\'t be used without #keepDays.'),
	('character deleted restore', 280, 'Syntax: .character deleted restore #guid|$name [$newname] [#new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If #newaccount is set, the character will be restored to specific account character list. This works only with one character!'),
	('reload gossip_menu', 651, 'Syntax: .reload gossip_menu\nReload gossip_menu table.'),
	('reload gossip_menu_option', 652, 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.'),
	('cast dest', 272, 'Syntax: .cast dest #spellid #x #y #z [triggered]\r\n  Selected target will cast #spellid at provided destination. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('reload all scripts', 621, 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.'),
	('reload gossip_menu_option_locale', 661, 'Syntax: .reload gossip_menu_option_locale\nReload gossip_menu_option_locale table.'),
	('reload quest_poi', 678, 'Syntax: .reload quest_poi\nReload quest_poi table.'),
	('reload lfg_dungeon_rewards', 656, 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.'),
	('character changefaction', 275, 'Syntax: .character changefaction $name\r\n\r\nChange character faction.'),
	('character changerace', 276, 'Syntax: .character changerace $name\r\n\r\nChange character race.'),
	('ban playeraccount', 243, 'Syntax: .ban playeraccount $Name $bantime $reason\nBan account and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('achievement add', 231, 'Syntax: .achievement add $achievement\nAdd an achievement to the targeted player.\n$achievement: can be either achievement id or achievement link'),
	('achievement', 230, 'Syntax: .achievement $subcommand\nType .achievement to see the list of possible subcommands or .help achievement $subcommand to see info on subcommands'),
	('mailbox', 777, 'Syntax: .mailbox\r\n\r\nShow your mailbox content.'),
	('debug areatriggers', 302, 'Syntax: .debug areatriggers\nToggle debug mode for areatriggers. In debug mode GM will be notified if reaching an areatrigger'),
	('learn all recipes', 428, 'Syntax: .learn all recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all recipes enchanting'),
	('npc set spawndist', 590, 'Syntax: .npc set spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.'),
	('npc set spawntime', 591, 'Syntax: .npc set spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.'),
	('npc add', 571, 'Syntax: .npc add #entry\n  Spawn a creature using template #entry and save it to the database.\n  If you want a temporary spawn that is not saved to the database, use .npc add temp instead.'),
	('npc textemote', 598, 'Syntax: .npc textemote #emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id #emoteid.'),
	('npc whisper', 599, 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.'),
	('npc yell', 600, 'Syntax: .npc yell $message\nMake selected creature yell specified message.'),
	('wp add', 768, 'Syntax: .wp add\r\n\r\nAdd a waypoint for the selected creature at your current position.'),
	('reload all spell', 622, 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.'),
	('server set loglevel', 732, 'Syntax: .server set loglevel $facility $name $loglevel. $facility can take the values: appender (a) or logger (l). $loglevel can take the values: disabled (0), trace (1), debug (2), info (3), warn (4), error (5) or fatal (6)'),
	('reload access_requirement', 608, 'Syntax: .reload access_requirement\nReload access_requirement table.'),
	('reload criteria_data', 609, 'Syntax: .reload criteria_data\nReload criteria_data table.'),
	('reload achievement_reward', 610, 'Syntax: .reload achievement_reward\nReload achievement_reward table.'),
	('reload all achievement', 612, 'Syntax: .reload all achievement\r\n\r\nReload achievement_reward, achievement_criteria_data tables.'),
	('reload all area', 613, 'Syntax: .reload all area\n\nReload areatrigger_teleport, areatrigger_tavern, graveyard_zone tables.'),
	('reload auctions', 626, 'Syntax: .reload auctions\nReload dynamic data tables from the database.'),
	('reload mail_level_reward', 668, 'Syntax: .reload mail_level_reward\nReload mail_level_reward table.'),
	('reload smart_scripts', 689, 'Syntax: .reload smart_scripts\nReload smart_scripts table.'),
	('reload vehicle_accessory', 708, 'Syntax: .reload vehicle_accessory\n\nReloads GUID-based vehicle accessory definitions from the database.'),
	('reload vehicle_template_accessory', 709, 'Syntax: .reload vehicle_template_accessory\n\nReloads entry-based vehicle accessory definitions from the database.'),
	('dev', 499, 'Syntax: .dev [on/off]\r\n\r\nEnable or Disable in game Dev tag or show current state if on/off not provided.'),
	('ticket reset', 753, 'Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing.'),
	('reload waypoint_data', 707, 'Syntax: .reload waypoint_data will reload waypoint_data table.'),
	('group', 472, 'Syntax: .group $subcommand\nType .group to see the list of possible subcommands or .help group $subcommand to see info on subcommands'),
	('group leader', 473, 'Syntax: .group leader [$characterName]\n\nSets the given character as his group\'s leader.'),
	('group disband', 474, 'Syntax: .group disband [$characterName]\n\nDisbands the given character\'s group.'),
	('group remove', 475, 'Syntax: .group remove [$characterName]\n\nRemoves the given character from his group.'),
	('debug moveflags', 314, 'Syntax: .debug moveflags [$newMoveFlags [$newMoveFlags2]]\r\nNo params given will output the current moveflags of the target'),
	('reload creature_text_locale', 659, 'Syntax: .reload creature_text_locale\nReload creature_text_locale Table.'),
	('morph', 542, 'Syntax: .morph #displayid\r\n\r\nChange your current model id to #displayid.'),
	('modify currency', 775, 'Syntax: .modify currency #id #value\nAdd $amount (without precision) of $currency to the selected player.'),
	('npc set data', 592, 'Syntax: .npc set data $field $data\nSets data for the selected creature. Used for testing Scripting'),
	('disable add quest', 355, 'Syntax: .disable add quest $entry $flag $comment'),
	('disable add map', 352, 'Syntax: .disable add map $entry $flag $comment'),
	('disable add battleground', 351, 'Syntax: .disable add battleground $entry $flag $comment'),
	('disable add criteria', 350, 'Syntax: .disable add criteria $entry $flag $comment'),
	('disable add spell', 356, 'Syntax: .disable add spell $entry $flag $comment'),
	('disable add outdoorpvp', 354, 'Syntax: .disable add outdoorpvp $entry $flag $comment'),
	('disable add vmap', 357, 'Syntax: .disable add vmap $entry $flag $comment'),
	('disable remove quest', 364, 'Syntax: .disable remove quest $entry'),
	('disable remove map', 361, 'Syntax: .disable remove map $entry'),
	('disable remove battleground', 360, 'Syntax: .disable remove battleground $entry'),
	('disable remove criteria', 359, 'Syntax: .disable remove criteria $entry'),
	('disable remove spell', 365, 'Syntax: .disable remove spell $entry'),
	('disable remove outdoorpvp', 363, 'Syntax: .disable remove outdoorpvp $entry'),
	('disable remove vmap', 366, 'Syntax: .disable remove vmap $entry'),
	('bf start', 258, 'Syntax: .bf start #battleid'),
	('bf stop', 259, 'Syntax: .bf stop #battleid'),
	('bf enable', 262, 'Syntax: .bf enable #battleid'),
	('bf switch', 260, 'Syntax: .bf switch #battleid'),
	('bf timer', 261, 'Syntax: .bf timer #battleid #timer'),
	('quest reward', 606, 'Syntax: .quest reward #questId\n\nGrants quest reward to selected player and removes quest from his log (quest must be in completed state).'),
	('cheat waterwalk', 299, 'Syntax: .cheat waterwalk on/off\r\nSet on/off waterwalk state for selected player or self if no player selected.'),
	('cheat explore', 294, 'Syntax: .cheat explore #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.'),
	('cheat taxi', 298, 'Syntax: .cheat taxi on/off\r\nTemporary grant access or remove to all taxi routes for the selected character.\r\n If no character is selected, hide or reveal all routes to you.Visited taxi nodes sill accessible after removing access.'),
	('cheat status', 297, 'Syntax: .cheat status \n\nShows the cheats you currently have enabled.'),
	('debug phase', 776, 'Syntax: .debug phase\r\n\r\nSends a phase debug report of a player to you.'),
	('lfg player', 431, 'Syntax: .lfg player\n Shows information about player (state, roles, comment, dungeons selected).'),
	('lfg group', 432, 'Syntax: .lfg group\n Shows information about all players in the group  (state, roles, comment, dungeons selected).'),
	('lfg queue', 433, 'Syntax: .lfg queue\n Shows info about current lfg queues.'),
	('lfg clean', 434, 'Syntax: .flg clean\n Cleans current queue, only for debugging purposes.'),
	('lfg options', 435, 'Syntax: .lfg options [new value]\n Shows current lfg options. New value is set if extra param is present.'),
	('mmap', 536, 'Syntax: Syntax: .mmaps $subcommand Type .mmaps to see the list of possible subcommands or .help mmaps $subcommand to see info on subcommands'),
	('mmap path', 539, 'Syntax: .mmap path to calculate and show a path to current select unit'),
	('mmap loc', 538, 'Syntax: .mmap loc to print on which tile one is'),
	('mmap loadedtiles', 537, 'Syntax: .mmap loadedtiles to show which tiles are currently loaded'),
	('mmap stats', 540, 'Syntax: .mmap stats to show information about current state of mmaps'),
	('mmap testarea', 541, 'Syntax: .mmap testarea to calculate paths for all nearby npcs to player'),
	('disable add mmap', 353, 'Syntax: .disable add mmap $entry $flag $comment'),
	('disable remove mmap', 362, 'Syntax: .disable remove mmap $entry'),
	('group join', 476, 'Syntax: .group join $AnyCharacterNameFromGroup [$CharacterName] \r\nAdds to group of player $AnyCharacterNameFromGroup player $CharacterName (or selected).'),
	('group list', 477, 'Syntax: .group list [$CharacterName] \r\nLists all the members of the group/party the player is in.'),
	('bnetaccount set password', 213, 'Syntax: .bnetaccount set password $account $password $password\nSet password for account.'),
	('bnetaccount set', 212, 'Syntax: .bnetaccount set $subcommand\nType .bnetaccount set to see the list of possible subcommands or .help bnetaccount set $subcommand to see info on subcommands.'),
	('bnetaccount password', 211, 'Syntax: .bnetaccount password $old_password $new_password $new_password\nChange your account password.'),
	('bnetaccount lock ip', 210, 'Syntax: .bnetaccount lock ip [on|off]\nAllow login to account only from current used IP or remove this requirement.'),
	('bnetaccount lock country', 209, 'Syntax: .bnetaccount lock country [on|off]\nAllow login to account only from current used Country or remove this requirement.'),
	('bnetaccount create', 208, 'Syntax: .bnetaccount create $account $password\nCreate battle.net account and set password to it. Account must contain the @ symbol.'),
	('reload creature_template', 639, 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.'),
	('reload creature_text', 640, 'Syntax: .reload creature_text\nReload creature_text Table.'),
	('debug transport', 400, 'Syntax: .debug transport [start/stop]\r\n\r\n Allows to stop a transport at its nearest wait point and start movement of a stopped one. Not all transports can be started or stopped.'),
	('rbac list', 206, 'Syntax: rbac list [$id]\n\nView list of all permissions. If $id is given will show only info for that permission.'),
	('rbac account revoke', 205, 'Syntax: rbac account revoke [$account] #id\n\nRemove a permission from an account\n\nNote: Removes the permission from granted or denied permissions'),
	('rbac account deny', 204, 'Syntax: rbac account deny [$account] #id [#realmId]\n\nDeny a permission to selected player or given account.\n\n#reamID may be -1 for all realms.'),
	('rbac account grant', 203, 'Syntax: rbac account grant [$account] #id [#realmId]\n\nGrant a permission to selected player or given account.\n\n#reamID may be -1 for all realms.'),
	('rbac account list', 202, 'Syntax: rbac account list [$account]\n\nView permissions of selected player or given account\nNote: Only those that affect current realm'),
	('reload creature_linked_respawn', 633, 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.'),
	('reload rbac', 680, 'Syntax: .reload rbac\nReload rbac system.'),
	('deserter instance add', 346, 'Syntax: .deserter instance add $time \n\n Adds the instance deserter debuff to your target with $time duration.'),
	('deserter instance remove', 347, 'Syntax: .deserter instance remove \n\n Removes the instance deserter debuff from your target.'),
	('deserter bg add', 343, 'Syntax: .deserter bg add $time \n\n Adds the bg deserter debuff to your target with $time duration.'),
	('deserter bg remove', 344, 'Syntax: .deserter bg remove \n\n Removes the bg deserter debuff from your target.'),
	('list mail', 441, 'Syntax: .list mail $character\nList of mails the character received.'),
	('account lock country', 222, 'Syntax: .account lock country [on|off]\nAllow login from account only from current used Country or remove this requirement.'),
	('guild rename', 407, 'Syntax: .guild rename "$GuildName" "$NewGuildName" \n\n Rename a guild named $GuildName with $NewGuildName. Guild name and new guild name must in quotes.'),
	('arena create', 234, 'Syntax: .arena create $name "arena name" #type\n\nA command to create a new Arena-team in game. #type  = [2/3/5]'),
	('arena disband', 235, 'Syntax: .arena disband #TeamID\n\nA command to disband Arena-team in game.'),
	('arena rename', 238, 'Syntax: .arena rename "oldname" "newname"\n\nA command to rename Arena-team name.'),
	('arena captain', 233, 'Syntax: .arena captain #TeamID $name\n\nA command to set new captain to the team $name must be in the team'),
	('arena info', 236, 'Syntax: .arena info #TeamID\n\nA command that show info about arena team'),
	('arena lookup', 237, 'Syntax: .arena lookup $name\n\nA command that give a list of arenateam with the given $name'),
	('reload gameobject_questender', 647, 'Syntax: .reload gameobject_questender\\nReload gameobject_questender table.'),
	('account set sec regmail', 266, 'Syntax: .account set sec regmail $account $regmail $regmailconfirmation\r\n\r\nSets the regmail for entered player account.'),
	('account set sec email', 265, 'Syntax: .account set sec email $accountname $email $emailconfirmation\r\n\r\nSet the email for entered player account.'),
	('account email', 263, 'Syntax: .account email $oldemail $currentpassword $newemail $newemailconfirmation\r\n\r\n Change your account email. You may need to check the actual security mode to see if email input is necessary for password change'),
	('bnetaccount', 207, 'Syntax: .bnetaccount $subcommand\nType .bnetaccount to see the list of possible subcommands or .help account set $subcommand to see info on subcommands.'),
	('reload battleground_template', 631, 'Syntax: .reload battleground_template\r\nReload Battleground Templates.'),
	('reload reputation_reward_rate', 683, 'Syntax: .reload reputation_reward_rate\r\nReload reputation_reward_rate table.'),
	('reload reputation_spillover_template', 684, 'Syntax: .reload reputation_spillover_template\r\nReload reputation_spillover_template table.'),
	('reload warden_action', 705, 'Syntax: .reload warden_action\r\nReload warden_action.'),
	('ahbot items', 779, 'Syntax: .ahbot items $GrayItems $WhiteItems $GreenItems $BlueItems $PurpleItems $OrangeItems $YellowItems\r\n\r\nSet amount of each items color be selled on auction.'),
	('ahbot items gray', 780, 'Syntax: .ahbot items gray $GrayItems\r\n\r\nSet amount of Gray color items be selled on auction.'),
	('ahbot items white', 781, 'Syntax: .ahbot items white $WhiteItems\r\n\r\nSet amount of White color items be selled on auction.'),
	('ahbot items green', 782, 'Syntax: .ahbot items green $GreenItems\r\n\r\nSet amount of Green color items be selled on auction.'),
	('ahbot items blue', 783, 'Syntax: .ahbot items blue $BlueItems\r\n\r\nSet amount of Blue color items be selled on auction.'),
	('ahbot items purple', 784, 'Syntax: .ahbot items purple $PurpleItems\r\n\r\nSet amount of Purple color items be selled on auction.'),
	('ahbot items orange', 785, 'Syntax: .ahbot items orange $OrangeItems\r\n\r\nSet amount of Orange color items be selled on auction.'),
	('ahbot items yellow', 786, 'Syntax: .ahbot items yellow $YellowItems\r\n\r\nSet amount of Yellow color items be selled on auction.'),
	('ahbot ratio', 787, 'Syntax: .ahbot ratio $allianceratio $horderatio $neutralratio\r\n\r\nSet ratio of items in 3 auctions house.'),
	('ahbot ratio alliance', 788, 'Syntax: .ahbot ratio alliance $allianceratio\r\n\r\nSet ratio of items in alliance auction house.'),
	('ahbot ratio horde', 789, 'Syntax: .ahbot ratio horde $horderatio\r\n\r\nSet ratio of items in horde auction house.'),
	('ahbot ratio neutral', 790, 'Syntax: .ahbot ratio neutral $neutralratio\r\n\r\nSet ratio of items in $neutral auction house.'),
	('ahbot rebuild', 791, 'Syntax: .ahbot rebuild [all]\r\n\r\nExpire all actual auction of ahbot except bided by player. Binded auctions included to expire if "all" option used. Ahbot re-fill auctions base at current settings then.'),
	('ahbot reload', 792, 'Syntax: .ahbot reload\r\n\r\nReload AHBot settings from configuration file.'),
	('ahbot status', 793, 'Syntax: .ahbot status [all]\r\n\r\nShow current ahbot state data in short form, and with "all" with details.'),
	('guild info', 794, 'Shows information about target\'s guild or a given guild identifier or name.'),
	('instance setbossstate', 795, 'Syntax: .instance setbossstate $bossId $encounterState [$Name]\r\nSets the EncounterState for the given boss id to a new value. EncounterStates range from 0 to 5.\r\nIf no character name is provided, the current map will be used as target.'),
	('instance getbossstate', 796, 'Syntax: .instance getbossstate $bossId [$Name]\r\nGets the current EncounterState for the provided boss id.\r\nIf no character name is provided, the current map will be used as target.'),
	('bnetaccount link', 214, 'Syntax: .bnetaccount link $email $login\nLinks battle.net account ($email) to an existing game account ($login).'),
	('bnetaccount unlink', 215, 'Syntax: .bnetaccount unlink $gameaccount $password\nRemoves battle.net account link from $gameaccount'),
	('bnetaccount gameaccountcreate', 216, 'Syntax: .bnetaccount gameaccountcreate $account\nCreate additional game account for specified battle.net account.'),
	('modify xp', 798, 'Syntax: .modify xp #xp\n\nGives experience points to the targeted player or self.'),
	('pvpstats', 797, 'Shows number of battleground victories in the last 7 days'),
	('ticket bug closedlist', 807, 'Usage: Displays a list of closed bug tickets.'),
	('ticket bug comment', 808, 'Usage: .ticket bug comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.'),
	('ticket bug delete', 809, 'Usage: .ticket bug delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.'),
	('ticket bug list', 810, 'Usage: Displays a list of open bug tickets.'),
	('ticket bug unassign', 811, 'Usage: .ticket bug unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.'),
	('ticket bug view', 812, 'Usage: .ticket bug view $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket complaint assign', 813, 'Usage: .ticket complaint assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.'),
	('ticket complaint close', 814, 'Usage: .ticket complaint close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.'),
	('ticket complaint closedlist', 815, 'Usage: Displays a list of closed complaint tickets.'),
	('ticket complaint comment', 816, 'Usage: .ticket complaint comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.'),
	('ticket complaint delete', 817, 'Usage: .ticket complaint delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.'),
	('ticket complaint list', 818, 'Usage: Displays a list of open complaint tickets.'),
	('ticket complaint unassign', 819, 'Usage: .ticket complaint unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.'),
	('ticket complaint view', 820, 'Usage: .ticket complaint view $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket suggestion assign', 821, 'Usage: .ticket suggestion assign $ticketid $gmname.Assigns the specified ticket to the specified Game Master.'),
	('ticket suggestion close', 822, 'Usage: .ticket suggestion close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.'),
	('ticket suggestion closedlist', 823, 'Usage: Displays a list of closed suggestion tickets.'),
	('ticket suggestion comment', 824, 'Usage: .ticket suggestion comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.'),
	('ticket suggestion delete', 825, 'Usage: .ticket suggestion delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.'),
	('ticket suggestion list', 826, 'Usage: Displays a list of open suggestion tickets.'),
	('ticket suggestion unassign', 827, 'Usage: .ticket suggestion unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.'),
	('ticket suggestion view', 828, 'Usage: .ticket suggestion view $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket reset all', 829, 'Usage: Removes all closed tickets and resets the counter, if no pending open tickets exist.'),
	('ticket reset bug', 831, 'Usage: Removes all closed bug tickets and resets the counter, if no pending open tickets exist.'),
	('ticket reset complaint', 832, 'Usage: Removes all closed complaint tickets and resets the counter, if no pending open tickets exist.'),
	('ticket reset suggestion', 833, 'Usage: Removes all closed suggestion tickets and resets the counter, if no pending open tickets exist.'),
	('scene', 844, ''),
	('scene debug', 845, 'Syntax: .scene debug\nToggle debug mode for scenes. In debug mode GM will be notified in chat when scenes start/stop/trigger event'),
	('go quest', 834, 'Syntax: .go quest #quest_id\r\n\r\nTeleport your character to first quest poi with id #quest_id.'),
	('debug loadcells', 835, 'Syntax: .debug loadcells [mapId]\nLoads all cells for debugging purposes'),
	('debug boundary', 836, 'Syntax: .debug boundary [fill] [duration]\nFlood fills the targeted unit\'s movement boundary and marks the edge of said boundary with debug creatures.\nSpecify \'fill\' as first parameter to fill the entire area with debug creatures.'),
	('debug raidreset', 414, 'Syntax: .debug raidreset mapid [difficulty]\nForces a global reset of the specified map on all difficulties (or only the specific difficulty if specified). Effectively the same as setting the specified map\'s reset timer to now.'),
	('server shutdown force', 839, 'Syntax: .server shutdown [force] #delay [#exit_code] [reason]\n\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code. Specify \'force\' to allow short-term shutdown despite other players being connected.'),
	('server restart force', 840, 'Syntax: .server restart [force] #delay [#exit_code] [reason]\n\nRestart the server after #delay seconds. Use #exit_code or 2 as program exit code. Specify \'force\' to allow short-term shutdown despite other players being connected.'),
	('npc add temp', 575, 'Syntax: .npc add temp [loot/noloot] #entry\nAdds temporary NPC, not saved to database.\n  Specify \'loot\' to have the NPC\'s corpse stick around for some time after death, allowing it to be looted.\n  Specify \'noloot\' to have the corpse disappear immediately.'),
	('npc evade', 837, 'Syntax: .npc evade [reason] [force]\nMakes the targeted NPC enter evade mode.\nDefaults to specifying EVADE_REASON_OTHER, override this by providing the reason string (ex.: .npc evade EVADE_REASON_BOUNDARY).\nSpecify \'force\' to clear any pre-existing evade state before evading - this may cause weirdness, use at your own risk.'),
	('pet level', 838, 'Syntax: .pet level #dLevel\nIncreases/decreases the pet\'s level by #dLevel. Pet\'s level cannot exceed the owner\'s level.'),
	('debug neargraveyard', 841, 'Syntax: .debug neargraveyard [linked]\nFind the nearest graveyard from dbc or db (if linked)'),
	('scene play', 846, 'Syntax: .scene play #sceneId\nPlays scene with id for targeted player'),
	('scene playpackage', 847, 'Syntax: .scene playpackage #scenePackageId #playbackFlags\nPlays scene with package id and playback flags for targeted player'),
	('scene cancel', 848, 'Syntax: .scene cancel #scenePackageId\nCancels scene with package id for targeted player'),
	('list scenes', 849, 'Syntax: .list scenes\nList of all active scenes for targeted character.'),
	('reload scene_template', 850, 'Syntax: .reload scene_template\nReload scene_template table.'),
	('bnetaccount listgameaccounts', 830, 'Syntax: .bnetaccount listgameaccounts $email $password\nLists all game accounts linked to battle.net $email'),
	('rbac', 200, 'Syntax: bf $subcommand\n Type .rbac to see a list of possible subcommands\n or .help bf $subcommand to see info on the subcommand.'),
	('rbac account', 201, 'Syntax: rbac account $subcommand\n Type .rbac account to see a list of possible subcommands\n or .help rbac account $subcommand to see info on the subcommand.'),
	('account lock', 221, 'Syntax: .account lock [on|off]\n\n Allow login from account only from current used IP or remove this requirement.'),
	('arena', 232, 'Syntax: arena $subcommand\n Type .arena to see a list of possible subcommands\n or .help arena $subcommand to see info on the subcommand.'),
	('unban playeraccount', 256, 'Syntax: '),
	('bf', 257, 'Syntax: bf $subcommand\n Type .bf to see a list of possible subcommands\n or .help bf $subcommand to see info on the subcommand.'),
	('account set sec', 264, 'Syntax: '),
	('character', 273, 'Syntax: character $subcommand\n Type .character to see a list of possible subcommands\n or .help character $subcommand to see info on the subcommand.'),
	('character deleted', 277, 'Syntax: character deleted $subcommand\n Type .character deleted to see a list of possible subcommands\n or .help character deleted $subcommand to see info on the subcommand.'),
	('debug anim', 301, 'Syntax: '),
	('debug entervehicle', 305, 'Syntax: '),
	('debug getitemstate', 306, 'Syntax: '),
	('debug combat', 309, 'Syntax: .debug combat\n\nLists the target\'s (or own) combat references.'),
	('debug itemexpire', 310, 'Syntax: '),
	('debug lootrecipient', 311, 'Syntax: '),
	('debug los', 312, 'Syntax: '),
	('debug play', 315, 'Syntax: '),
	('debug send', 319, 'Syntax: '),
	('debug send buyerror', 320, 'Syntax: '),
	('debug send channelnotify', 321, 'Syntax: '),
	('debug send chatmessage', 322, 'Syntax: '),
	('debug send equiperror', 323, 'Syntax: '),
	('debug send largepacket', 324, 'Syntax: '),
	('debug send opcode', 325, 'Syntax: '),
	('debug send qinvalidmsg', 326, 'Syntax: '),
	('debug send qpartymsg', 327, 'Syntax: '),
	('debug send sellerror', 328, 'Syntax: '),
	('debug send setphaseshift', 329, 'Syntax: '),
	('debug send spellfail', 330, 'Syntax: '),
	('debug setaurastate', 331, 'Syntax: '),
	('debug setvid', 335, 'Syntax: '),
	('debug spawnvehicle', 336, 'Syntax: '),
	('debug threat', 337, 'Syntax: .debug threat\n\nLists the units threatened by target (or self). If target has a threat list, lists that threat list, too.'),
	('debug worldstate', 339, 'Syntax: debug worldstate $stateId $value\n\nSends a world state update for the specified state to your client.'),
	('deserter', 341, 'Syntax: deserter $subcommand\n Type .deserter to see a list of possible subcommands\n or .help deserter $subcommand to see info on the subcommand.'),
	('deserter bg', 342, 'Syntax: '),
	('deserter instance', 345, 'Syntax: '),
	('disable', 348, 'Syntax: disable $subcommand\n Type .disable to see a list of possible subcommands\n or .help disable $subcommand to see info on the subcommand.'),
	('disable add', 349, 'Syntax: '),
	('disable remove', 358, 'Syntax: '),
	('gobject set', 395, 'Syntax: '),
	('gobject set state', 397, 'Syntax: '),
	('learn all', 418, 'Syntax: '),
	('learn all my', 419, 'Syntax: '),
	('lfg', 430, 'Syntax: lfg $subcommand\n Type .lfg to see a list of possible subcommands\n or .help lfg $subcommand to see info on the subcommand.'),
	('lookup player', 451, 'Syntax: '),
	('channel', 463, 'Syntax: channel $subcommand\n Type .channel to see a list of possible subcommands\n or .help channel $subcommand to see info on the subcommand.'),
	('channel set', 464, 'Syntax: '),
	('send', 483, 'Syntax: send $subcommand\n Type .send to see a list of possible subcommands\n or .help send $subcommand to see info on the subcommand.'),
	('npc set', 580, 'Syntax: '),
	('npc near', 594, 'Syntax: '),
	('npc tame', 601, 'Syntax: '),
	('mutehistory', 632, 'Syntax: '),
	('reload achievement_reward_locale', 657, 'Syntax: .reload achievement_reward_locale\nReload achievement_reward_locale table.'),
	('reload npc_spellclick_spells', 671, 'Syntax: '),
	('server set', 729, 'Syntax: '),
	('server set difftime', 731, 'Syntax: '),
	('ticket togglesystem', 757, 'Syntax: '),
	('titles', 761, 'Syntax: '),
	('titles set', 765, 'Syntax: '),
	('wp', 767, 'Syntax: wp $subcommand\n Type .wp to see a list of possible subcommands\n or .help wp $subcommand to see info on the subcommand.'),
	('wp modify', 771, 'Syntax: '),
	('ahbot', 778, 'Syntax: ahbot $subcommand\n Type .ahbot to see a list of possible subcommands\n or .help ahbot $subcommand to see info on the subcommand.'),
	('debug conversation', 854, 'Syntax: .debug conversation $conversationId\r\nPlay given conversation.'),
	('reload conversation_template', 853, 'Syntax: .reload conversation_template\r\nReload conversation tables.'),
	('modify power', 868, 'Syntax: .modify power #powerType #amount \r\n\r\nModify the power of the selected player. If no player is selected, modify your power.'),
	('debug send playerchoice', 869, 'Syntax: .debug send playerchoice $choiceId\r\nSend given choice to player.'),
	('server debug', 872, 'Syntax: .server debug\n\nShows detailed information about server setup, useful when reporting a bug'),
	('debug play music', 855, 'Syntax: .debug play music #musicId\nPlay music with #musicId.\nMusic will be played only for you. Other players will not hear this.'),
	('account set seclevel', 228, 'Syntax: .account set seclevel [$accountName] #level [#realmID]\n\nSet the security level for targeted player (can\'t be used at self) or for account $accountName to a level of #level on the realm #realmID.\n\n#level may range from 0 to 3.\n\n#realmID - Default: -1 for all realms.'),
	('group set assistant', 862, 'Syntax: .group set assistant [$characterName]\n\nToggles the given character\'s assistant state in his raid group.'),
	('group set maintank', 863, 'Syntax: .group set maintank [$characterName]\n\nToggles the given character\'s main tank flag in his raid group.'),
	('group set mainassist', 864, 'Syntax: .group set mainassist [$characterName]\n\nToggles the given character\'s main assist flag in his raid group.'),
	('npc showloot', 865, 'Syntax: .npc showloot [all]\n\nShows the loot contained in targeted dead creature.'),
	('npc spawngroup', 856, 'Syntax: .npc spawngroup $groupId [ignorerespawn] [force]'),
	('npc despawngroup', 857, 'Syntax: .npc despawngroup $groupId [removerespawntime]'),
	('gobject spawngroup', 858, 'Syntax: .gobject spawngroup $groupId [ignorerespawn] [force]'),
	('gobject despawngroup', 859, 'Syntax: .gobject despawngroup $groupId [removerespawntime]'),
	('list respawns', 860, 'Syntax: .list respawns [distance]\n\nLists all pending respawns within <distance> yards, or within current zone if not specified.'),
	('list spawnpoints', 866, 'Syntax: .list spawnpoints\n\nLists all spawn points (both creatures and GOs) in the current zone.');
/*!40000 ALTER TABLE `command` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
