// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: club_enum.proto

#ifndef PROTOBUF_club_5fenum_2eproto__INCLUDED
#define PROTOBUF_club_5fenum_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include "Define.h" // for TC_PROTO_API
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {
namespace club {
namespace v1 {

// Internal implementation detail -- do not call these.
void TC_PROTO_API protobuf_AddDesc_club_5fenum_2eproto();
void protobuf_AssignDesc_club_5fenum_2eproto();
void protobuf_ShutdownFile_club_5fenum_2eproto();


enum PrivacyLevel {
  PRIVACY_LEVEL_CLOSED = 0,
  PRIVACY_LEVEL_OPEN_INVITATION = 1,
  PRIVACY_LEVEL_OPEN_TICKET = 2,
  PRIVACY_LEVEL_OPEN = 3
};
TC_PROTO_API bool PrivacyLevel_IsValid(int value);
const PrivacyLevel PrivacyLevel_MIN = PRIVACY_LEVEL_CLOSED;
const PrivacyLevel PrivacyLevel_MAX = PRIVACY_LEVEL_OPEN;
const int PrivacyLevel_ARRAYSIZE = PrivacyLevel_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* PrivacyLevel_descriptor();
inline const ::std::string& PrivacyLevel_Name(PrivacyLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    PrivacyLevel_descriptor(), value);
}
inline bool PrivacyLevel_Parse(
    const ::std::string& name, PrivacyLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PrivacyLevel>(
    PrivacyLevel_descriptor(), name, value);
}
enum VisibilityLevel {
  VISIBILITY_LEVEL_PRIVATE = 0,
  VISIBILITY_LEVEL_PUBLIC = 1
};
TC_PROTO_API bool VisibilityLevel_IsValid(int value);
const VisibilityLevel VisibilityLevel_MIN = VISIBILITY_LEVEL_PRIVATE;
const VisibilityLevel VisibilityLevel_MAX = VISIBILITY_LEVEL_PUBLIC;
const int VisibilityLevel_ARRAYSIZE = VisibilityLevel_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* VisibilityLevel_descriptor();
inline const ::std::string& VisibilityLevel_Name(VisibilityLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    VisibilityLevel_descriptor(), value);
}
inline bool VisibilityLevel_Parse(
    const ::std::string& name, VisibilityLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<VisibilityLevel>(
    VisibilityLevel_descriptor(), name, value);
}
enum ClubRemovedReason {
  CLUB_REMOVED_REASON_NONE = 0,
  CLUB_REMOVED_REASON_MEMBER_LEFT = 1,
  CLUB_REMOVED_REASON_MEMBER_KICKED = 2,
  CLUB_REMOVED_REASON_MEMBER_BANNED = 3,
  CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE = 4,
  CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER = 5,
  CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE = 6
};
TC_PROTO_API bool ClubRemovedReason_IsValid(int value);
const ClubRemovedReason ClubRemovedReason_MIN = CLUB_REMOVED_REASON_NONE;
const ClubRemovedReason ClubRemovedReason_MAX = CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE;
const int ClubRemovedReason_ARRAYSIZE = ClubRemovedReason_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* ClubRemovedReason_descriptor();
inline const ::std::string& ClubRemovedReason_Name(ClubRemovedReason value) {
  return ::google::protobuf::internal::NameOfEnum(
    ClubRemovedReason_descriptor(), value);
}
inline bool ClubRemovedReason_Parse(
    const ::std::string& name, ClubRemovedReason* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ClubRemovedReason>(
    ClubRemovedReason_descriptor(), name, value);
}
enum StreamVoiceLevel {
  VOICE_LEVEL_DISABLED = 0,
  VOICE_LEVEL_PUSH_TO_TALK = 1,
  VOICE_LEVEL_OPEN_MIC = 2
};
TC_PROTO_API bool StreamVoiceLevel_IsValid(int value);
const StreamVoiceLevel StreamVoiceLevel_MIN = VOICE_LEVEL_DISABLED;
const StreamVoiceLevel StreamVoiceLevel_MAX = VOICE_LEVEL_OPEN_MIC;
const int StreamVoiceLevel_ARRAYSIZE = StreamVoiceLevel_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* StreamVoiceLevel_descriptor();
inline const ::std::string& StreamVoiceLevel_Name(StreamVoiceLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    StreamVoiceLevel_descriptor(), value);
}
inline bool StreamVoiceLevel_Parse(
    const ::std::string& name, StreamVoiceLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StreamVoiceLevel>(
    StreamVoiceLevel_descriptor(), name, value);
}
enum VoiceMicrophoneState {
  MICROPHONE_STATE_NORMAL = 0,
  MICROPHONE_STATE_SELF_MUTE = 1,
  MICROPHONE_STATE_SELF_DEAF = 2
};
TC_PROTO_API bool VoiceMicrophoneState_IsValid(int value);
const VoiceMicrophoneState VoiceMicrophoneState_MIN = MICROPHONE_STATE_NORMAL;
const VoiceMicrophoneState VoiceMicrophoneState_MAX = MICROPHONE_STATE_SELF_DEAF;
const int VoiceMicrophoneState_ARRAYSIZE = VoiceMicrophoneState_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* VoiceMicrophoneState_descriptor();
inline const ::std::string& VoiceMicrophoneState_Name(VoiceMicrophoneState value) {
  return ::google::protobuf::internal::NameOfEnum(
    VoiceMicrophoneState_descriptor(), value);
}
inline bool VoiceMicrophoneState_Parse(
    const ::std::string& name, VoiceMicrophoneState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<VoiceMicrophoneState>(
    VoiceMicrophoneState_descriptor(), name, value);
}
enum PresenceLevel {
  PRESENCE_LEVEL_NONE = 0,
  PRESENCE_LEVEL_BASIC = 1,
  PRESENCE_LEVEL_RICH = 2
};
TC_PROTO_API bool PresenceLevel_IsValid(int value);
const PresenceLevel PresenceLevel_MIN = PRESENCE_LEVEL_NONE;
const PresenceLevel PresenceLevel_MAX = PRESENCE_LEVEL_RICH;
const int PresenceLevel_ARRAYSIZE = PresenceLevel_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* PresenceLevel_descriptor();
inline const ::std::string& PresenceLevel_Name(PresenceLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    PresenceLevel_descriptor(), value);
}
inline bool PresenceLevel_Parse(
    const ::std::string& name, PresenceLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PresenceLevel>(
    PresenceLevel_descriptor(), name, value);
}
enum WhisperLevel {
  WHISPER_LEVEL_OPEN = 0,
  WHISPER_LEVEL_RESTRICTED = 1
};
TC_PROTO_API bool WhisperLevel_IsValid(int value);
const WhisperLevel WhisperLevel_MIN = WHISPER_LEVEL_OPEN;
const WhisperLevel WhisperLevel_MAX = WHISPER_LEVEL_RESTRICTED;
const int WhisperLevel_ARRAYSIZE = WhisperLevel_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* WhisperLevel_descriptor();
inline const ::std::string& WhisperLevel_Name(WhisperLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    WhisperLevel_descriptor(), value);
}
inline bool WhisperLevel_Parse(
    const ::std::string& name, WhisperLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<WhisperLevel>(
    WhisperLevel_descriptor(), name, value);
}
enum StreamNotificationFilter {
  STREAM_NOTIFICATION_FILTER_NONE = 0,
  STREAM_NOTIFICATION_FILTER_MENTION = 1,
  STREAM_NOTIFICATION_FILTER_ALL = 2
};
TC_PROTO_API bool StreamNotificationFilter_IsValid(int value);
const StreamNotificationFilter StreamNotificationFilter_MIN = STREAM_NOTIFICATION_FILTER_NONE;
const StreamNotificationFilter StreamNotificationFilter_MAX = STREAM_NOTIFICATION_FILTER_ALL;
const int StreamNotificationFilter_ARRAYSIZE = StreamNotificationFilter_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* StreamNotificationFilter_descriptor();
inline const ::std::string& StreamNotificationFilter_Name(StreamNotificationFilter value) {
  return ::google::protobuf::internal::NameOfEnum(
    StreamNotificationFilter_descriptor(), value);
}
inline bool StreamNotificationFilter_Parse(
    const ::std::string& name, StreamNotificationFilter* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StreamNotificationFilter>(
    StreamNotificationFilter_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace club
}  // namespace protocol
}  // namespace bgs

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bgs::protocol::club::v1::PrivacyLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::PrivacyLevel>() {
  return ::bgs::protocol::club::v1::PrivacyLevel_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::VisibilityLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::VisibilityLevel>() {
  return ::bgs::protocol::club::v1::VisibilityLevel_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::ClubRemovedReason> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::ClubRemovedReason>() {
  return ::bgs::protocol::club::v1::ClubRemovedReason_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::StreamVoiceLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::StreamVoiceLevel>() {
  return ::bgs::protocol::club::v1::StreamVoiceLevel_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::VoiceMicrophoneState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::VoiceMicrophoneState>() {
  return ::bgs::protocol::club::v1::VoiceMicrophoneState_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::PresenceLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::PresenceLevel>() {
  return ::bgs::protocol::club::v1::PresenceLevel_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::WhisperLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::WhisperLevel>() {
  return ::bgs::protocol::club::v1::WhisperLevel_descriptor();
}
template <> struct is_proto_enum< ::bgs::protocol::club::v1::StreamNotificationFilter> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::club::v1::StreamNotificationFilter>() {
  return ::bgs::protocol::club::v1::StreamNotificationFilter_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_club_5fenum_2eproto__INCLUDED
