// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friends_types.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "friends_types.pb.h"

#include <utility>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {
namespace friends {
namespace v1 {

namespace {

const ::google::protobuf::Descriptor* Friend_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Friend_reflection_ = NULL;
const ::google::protobuf::Descriptor* FriendOfFriend_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FriendOfFriend_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReceivedInvitation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReceivedInvitation_reflection_ = NULL;
const ::google::protobuf::Descriptor* FriendInvitation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FriendInvitation_reflection_ = NULL;
const ::google::protobuf::Descriptor* SentInvitation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SentInvitation_reflection_ = NULL;
const ::google::protobuf::Descriptor* FriendInvitationParams_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FriendInvitationParams_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscribeResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscribeResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* AcceptInvitationOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AcceptInvitationOptions_reflection_ = NULL;

}  // namespace

void protobuf_AssignDesc_friends_5ftypes_2eproto() {
  protobuf_AddDesc_friends_5ftypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "friends_types.proto");
  GOOGLE_CHECK(file != NULL);
  Friend_descriptor_ = file->message_type(0);
  static const int Friend_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, account_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, privileges_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, attributes_epoch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, creation_time_),
  };
  Friend_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Friend_descriptor_,
      Friend::default_instance_,
      Friend_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Friend, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Friend));
  FriendOfFriend_descriptor_ = file->message_type(1);
  static const int FriendOfFriend_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, account_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, privileges_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, full_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, battle_tag_),
  };
  FriendOfFriend_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FriendOfFriend_descriptor_,
      FriendOfFriend::default_instance_,
      FriendOfFriend_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendOfFriend, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FriendOfFriend));
  ReceivedInvitation_descriptor_ = file->message_type(2);
  static const int ReceivedInvitation_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, inviter_identity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, invitee_identity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, inviter_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, invitee_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, creation_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, program_),
  };
  ReceivedInvitation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReceivedInvitation_descriptor_,
      ReceivedInvitation::default_instance_,
      ReceivedInvitation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReceivedInvitation, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReceivedInvitation));
  FriendInvitation_descriptor_ = file->message_type(3);
  static const int FriendInvitation_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitation, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitation, attribute_),
  };
  FriendInvitation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FriendInvitation_descriptor_,
      FriendInvitation::default_instance_,
      FriendInvitation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FriendInvitation));
  SentInvitation_descriptor_ = file->message_type(4);
  static const int SentInvitation_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, target_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, creation_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, program_),
  };
  SentInvitation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SentInvitation_descriptor_,
      SentInvitation::default_instance_,
      SentInvitation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SentInvitation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SentInvitation));
  FriendInvitationParams_descriptor_ = file->message_type(5);
  static const int FriendInvitationParams_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, target_email_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, target_battle_tag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, attribute_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, target_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, program_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, target_phone_number_),
  };
  FriendInvitationParams_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FriendInvitationParams_descriptor_,
      FriendInvitationParams::default_instance_,
      FriendInvitationParams_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FriendInvitationParams, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FriendInvitationParams));
  SubscribeResponse_descriptor_ = file->message_type(6);
  static const int SubscribeResponse_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, max_friends_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, max_received_invitations_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, max_sent_invitations_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, friends_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, received_invitations_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, sent_invitations_),
  };
  SubscribeResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SubscribeResponse_descriptor_,
      SubscribeResponse::default_instance_,
      SubscribeResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SubscribeResponse));
  AcceptInvitationOptions_descriptor_ = file->message_type(7);
  static const int AcceptInvitationOptions_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptInvitationOptions, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptInvitationOptions, program_),
  };
  AcceptInvitationOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AcceptInvitationOptions_descriptor_,
      AcceptInvitationOptions::default_instance_,
      AcceptInvitationOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptInvitationOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptInvitationOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AcceptInvitationOptions));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_friends_5ftypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Friend_descriptor_, &Friend::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FriendOfFriend_descriptor_, &FriendOfFriend::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReceivedInvitation_descriptor_, &ReceivedInvitation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FriendInvitation_descriptor_, &FriendInvitation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SentInvitation_descriptor_, &SentInvitation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FriendInvitationParams_descriptor_, &FriendInvitationParams::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SubscribeResponse_descriptor_, &SubscribeResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AcceptInvitationOptions_descriptor_, &AcceptInvitationOptions::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_friends_5ftypes_2eproto() {
  delete Friend::default_instance_;
  delete Friend_reflection_;
  delete FriendOfFriend::default_instance_;
  delete FriendOfFriend_reflection_;
  delete ReceivedInvitation::default_instance_;
  delete ReceivedInvitation_reflection_;
  delete FriendInvitation::default_instance_;
  delete FriendInvitation_reflection_;
  delete SentInvitation::default_instance_;
  delete SentInvitation_reflection_;
  delete FriendInvitationParams::default_instance_;
  delete FriendInvitationParams_reflection_;
  delete SubscribeResponse::default_instance_;
  delete SubscribeResponse_reflection_;
  delete AcceptInvitationOptions::default_instance_;
  delete AcceptInvitationOptions_reflection_;
}

void protobuf_AddDesc_friends_5ftypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::bgs::protocol::protobuf_AddDesc_global_5fextensions_2ffield_5foptions_2eproto();
  ::bgs::protocol::protobuf_AddDesc_attribute_5ftypes_2eproto();
  ::bgs::protocol::protobuf_AddDesc_entity_5ftypes_2eproto();
  ::bgs::protocol::protobuf_AddDesc_api_2fcommon_2fv1_2finvitation_5ftypes_2eproto();
  ::bgs::protocol::protobuf_AddDesc_role_5ftypes_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023friends_types.proto\022\027bgs.protocol.frie"
    "nds.v1\032%global_extensions/field_options."
    "proto\032\025attribute_types.proto\032\022entity_typ"
    "es.proto\032$api/common/v1/invitation_types"
    ".proto\032\020role_types.proto\"\273\001\n\006Friend\022*\n\na"
    "ccount_id\030\001 \002(\0132\026.bgs.protocol.EntityId\022"
    "*\n\tattribute\030\002 \003(\0132\027.bgs.protocol.Attrib"
    "ute\022\020\n\004role\030\003 \003(\rB\002\020\001\022\022\n\nprivileges\030\004 \001("
    "\004\022\034\n\020attributes_epoch\030\005 \001(\004B\002\030\001\022\025\n\rcreat"
    "ion_time\030\006 \001(\004\"\245\001\n\016FriendOfFriend\022*\n\nacc"
    "ount_id\030\001 \001(\0132\026.bgs.protocol.EntityId\022\034\n"
    "\004role\030\003 \003(\rB\016\020\001\212\371+\010*\006\n\004\010\001\020\001\022\022\n\nprivilege"
    "s\030\004 \001(\004\022\031\n\tfull_name\030\006 \001(\tB\006\202\371+\002\010\001\022\032\n\nba"
    "ttle_tag\030\007 \001(\tB\006\202\371+\002\010\001\"\357\001\n\022ReceivedInvit"
    "ation\022\n\n\002id\030\001 \002(\006\0220\n\020inviter_identity\030\002 "
    "\002(\0132\026.bgs.protocol.Identity\0220\n\020invitee_i"
    "dentity\030\003 \002(\0132\026.bgs.protocol.Identity\022\034\n"
    "\014inviter_name\030\004 \001(\tB\006\202\371+\002\010\001\022\034\n\014invitee_n"
    "ame\030\005 \001(\tB\006\202\371+\002\010\001\022\025\n\rcreation_time\030\007 \001(\004"
    "\022\017\n\007program\030\t \001(\007*\005\010d\020\220N\"\317\001\n\020FriendInvit"
    "ation\022\034\n\004role\030\002 \003(\rB\016\020\001\212\371+\010*\006\n\004\010\001\020\001\022*\n\ta"
    "ttribute\030\003 \003(\0132\027.bgs.protocol.Attribute2"
    "q\n\021friend_invitation\022+.bgs.protocol.frie"
    "nds.v1.ReceivedInvitation\030g \001(\0132).bgs.pr"
    "otocol.friends.v1.FriendInvitation\"\233\001\n\016S"
    "entInvitation\022\n\n\002id\030\001 \001(\006\022\033\n\013target_name"
    "\030\002 \001(\tB\006\202\371+\002\010\001\022\014\n\004role\030\003 \001(\r\022*\n\tattribut"
    "e\030\004 \003(\0132\027.bgs.protocol.Attribute\022\025\n\rcrea"
    "tion_time\030\005 \001(\004\022\017\n\007program\030\006 \001(\007\"\342\002\n\026Fri"
    "endInvitationParams\022\034\n\014target_email\030\001 \001("
    "\tB\006\202\371+\002\010\001\022!\n\021target_battle_tag\030\002 \001(\tB\006\202\371"
    "+\002\010\001\022\034\n\004role\030\006 \003(\rB\016\020\001\212\371+\010*\006\n\004\010\001\020\001\022*\n\tat"
    "tribute\030\010 \003(\0132\027.bgs.protocol.Attribute\022\033"
    "\n\013target_name\030\t \001(\tB\006\202\371+\002\010\001\022\023\n\007program\030\n"
    " \001(\007B\002\030\001\022#\n\023target_phone_number\030\013 \001(\tB\006\202"
    "\371+\002\010\0012f\n\rfriend_params\022\036.bgs.protocol.In"
    "vitationParams\030g \001(\0132/.bgs.protocol.frie"
    "nds.v1.FriendInvitationParams\"\326\002\n\021Subscr"
    "ibeResponse\022\027\n\013max_friends\030\001 \001(\rB\002\030\001\022$\n\030"
    "max_received_invitations\030\002 \001(\rB\002\030\001\022 \n\024ma"
    "x_sent_invitations\030\003 \001(\rB\002\030\001\022 \n\004role\030\004 \003"
    "(\0132\022.bgs.protocol.Role\0220\n\007friends\030\005 \003(\0132"
    "\037.bgs.protocol.friends.v1.Friend\022I\n\024rece"
    "ived_invitations\030\007 \003(\0132+.bgs.protocol.fr"
    "iends.v1.ReceivedInvitation\022A\n\020sent_invi"
    "tations\030\010 \003(\0132\'.bgs.protocol.friends.v1."
    "SentInvitation\"F\n\027AcceptInvitationOption"
    "s\022\032\n\004role\030\001 \001(\rB\014\212\371+\010\022\006\n\004\010\000\020\002\022\017\n\007program"
    "\030\002 \001(\007B.\n\027bgs.protocol.friends.v1B\021Frien"
    "dsTypesProtoH\002P\000", 1976);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "friends_types.proto", &protobuf_RegisterTypes);
  Friend::default_instance_ = new Friend();
  FriendOfFriend::default_instance_ = new FriendOfFriend();
  ReceivedInvitation::default_instance_ = new ReceivedInvitation();
  FriendInvitation::default_instance_ = new FriendInvitation();
  SentInvitation::default_instance_ = new SentInvitation();
  FriendInvitationParams::default_instance_ = new FriendInvitationParams();
  SubscribeResponse::default_instance_ = new SubscribeResponse();
  AcceptInvitationOptions::default_instance_ = new AcceptInvitationOptions();
  Friend::default_instance_->InitAsDefaultInstance();
  FriendOfFriend::default_instance_->InitAsDefaultInstance();
  ReceivedInvitation::default_instance_->InitAsDefaultInstance();
  FriendInvitation::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::bgs::protocol::friends::v1::ReceivedInvitation::default_instance(),
    103, 11, false, false,
    &::bgs::protocol::friends::v1::FriendInvitation::default_instance());
  SentInvitation::default_instance_->InitAsDefaultInstance();
  FriendInvitationParams::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::bgs::protocol::InvitationParams::default_instance(),
    103, 11, false, false,
    &::bgs::protocol::friends::v1::FriendInvitationParams::default_instance());
  SubscribeResponse::default_instance_->InitAsDefaultInstance();
  AcceptInvitationOptions::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_friends_5ftypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_friends_5ftypes_2eproto {
  StaticDescriptorInitializer_friends_5ftypes_2eproto() {
    protobuf_AddDesc_friends_5ftypes_2eproto();
  }
} static_descriptor_initializer_friends_5ftypes_2eproto_;
// ===================================================================

#ifndef _MSC_VER
const int Friend::kAccountIdFieldNumber;
const int Friend::kAttributeFieldNumber;
const int Friend::kRoleFieldNumber;
const int Friend::kPrivilegesFieldNumber;
const int Friend::kAttributesEpochFieldNumber;
const int Friend::kCreationTimeFieldNumber;
#endif  // !_MSC_VER

Friend::Friend()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.Friend)
}

void Friend::InitAsDefaultInstance() {
  account_id_ = const_cast< ::bgs::protocol::EntityId*>(&::bgs::protocol::EntityId::default_instance());
}

Friend::Friend(const Friend& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.Friend)
}

void Friend::SharedCtor() {
  _cached_size_ = 0;
  account_id_ = NULL;
  privileges_ = GOOGLE_ULONGLONG(0);
  attributes_epoch_ = GOOGLE_ULONGLONG(0);
  creation_time_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Friend::~Friend() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.Friend)
  SharedDtor();
}

void Friend::SharedDtor() {
  if (this != default_instance_) {
    delete account_id_;
  }
}

void Friend::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Friend::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Friend_descriptor_;
}

const Friend& Friend::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

Friend* Friend::default_instance_ = NULL;

Friend* Friend::New() const {
  return new Friend;
}

void Friend::Swap(Friend* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata Friend::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Friend_descriptor_;
  metadata.reflection = Friend_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int FriendOfFriend::kAccountIdFieldNumber;
const int FriendOfFriend::kRoleFieldNumber;
const int FriendOfFriend::kPrivilegesFieldNumber;
const int FriendOfFriend::kFullNameFieldNumber;
const int FriendOfFriend::kBattleTagFieldNumber;
#endif  // !_MSC_VER

FriendOfFriend::FriendOfFriend()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.FriendOfFriend)
}

void FriendOfFriend::InitAsDefaultInstance() {
  account_id_ = const_cast< ::bgs::protocol::EntityId*>(&::bgs::protocol::EntityId::default_instance());
}

FriendOfFriend::FriendOfFriend(const FriendOfFriend& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.FriendOfFriend)
}

void FriendOfFriend::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  account_id_ = NULL;
  privileges_ = GOOGLE_ULONGLONG(0);
  full_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FriendOfFriend::~FriendOfFriend() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.FriendOfFriend)
  SharedDtor();
}

void FriendOfFriend::SharedDtor() {
  if (full_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete full_name_;
  }
  if (battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete battle_tag_;
  }
  if (this != default_instance_) {
    delete account_id_;
  }
}

void FriendOfFriend::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FriendOfFriend::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FriendOfFriend_descriptor_;
}

const FriendOfFriend& FriendOfFriend::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

FriendOfFriend* FriendOfFriend::default_instance_ = NULL;

FriendOfFriend* FriendOfFriend::New() const {
  return new FriendOfFriend;
}

void FriendOfFriend::Swap(FriendOfFriend* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FriendOfFriend::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FriendOfFriend_descriptor_;
  metadata.reflection = FriendOfFriend_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int ReceivedInvitation::kIdFieldNumber;
const int ReceivedInvitation::kInviterIdentityFieldNumber;
const int ReceivedInvitation::kInviteeIdentityFieldNumber;
const int ReceivedInvitation::kInviterNameFieldNumber;
const int ReceivedInvitation::kInviteeNameFieldNumber;
const int ReceivedInvitation::kCreationTimeFieldNumber;
const int ReceivedInvitation::kProgramFieldNumber;
#endif  // !_MSC_VER

ReceivedInvitation::ReceivedInvitation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.ReceivedInvitation)
}

void ReceivedInvitation::InitAsDefaultInstance() {
  inviter_identity_ = const_cast< ::bgs::protocol::Identity*>(&::bgs::protocol::Identity::default_instance());
  invitee_identity_ = const_cast< ::bgs::protocol::Identity*>(&::bgs::protocol::Identity::default_instance());
}

ReceivedInvitation::ReceivedInvitation(const ReceivedInvitation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.ReceivedInvitation)
}

void ReceivedInvitation::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = GOOGLE_ULONGLONG(0);
  inviter_identity_ = NULL;
  invitee_identity_ = NULL;
  inviter_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  invitee_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  creation_time_ = GOOGLE_ULONGLONG(0);
  program_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReceivedInvitation::~ReceivedInvitation() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.ReceivedInvitation)
  SharedDtor();
}

void ReceivedInvitation::SharedDtor() {
  if (inviter_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete inviter_name_;
  }
  if (invitee_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete invitee_name_;
  }
  if (this != default_instance_) {
    delete inviter_identity_;
    delete invitee_identity_;
  }
}

void ReceivedInvitation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReceivedInvitation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReceivedInvitation_descriptor_;
}

const ReceivedInvitation& ReceivedInvitation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

ReceivedInvitation* ReceivedInvitation::default_instance_ = NULL;

ReceivedInvitation* ReceivedInvitation::New() const {
  return new ReceivedInvitation;
}

void ReceivedInvitation::Swap(ReceivedInvitation* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata ReceivedInvitation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReceivedInvitation_descriptor_;
  metadata.reflection = ReceivedInvitation_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int FriendInvitation::kRoleFieldNumber;
const int FriendInvitation::kAttributeFieldNumber;
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int FriendInvitation::kFriendInvitationFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::bgs::protocol::friends::v1::ReceivedInvitation,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::friends::v1::FriendInvitation >, 11, false >
  FriendInvitation::friend_invitation(kFriendInvitationFieldNumber, ::bgs::protocol::friends::v1::FriendInvitation::default_instance());
FriendInvitation::FriendInvitation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.FriendInvitation)
}

void FriendInvitation::InitAsDefaultInstance() {
}

FriendInvitation::FriendInvitation(const FriendInvitation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.FriendInvitation)
}

void FriendInvitation::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FriendInvitation::~FriendInvitation() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.FriendInvitation)
  SharedDtor();
}

void FriendInvitation::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FriendInvitation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FriendInvitation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FriendInvitation_descriptor_;
}

const FriendInvitation& FriendInvitation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

FriendInvitation* FriendInvitation::default_instance_ = NULL;

FriendInvitation* FriendInvitation::New() const {
  return new FriendInvitation;
}

void FriendInvitation::Swap(FriendInvitation* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FriendInvitation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FriendInvitation_descriptor_;
  metadata.reflection = FriendInvitation_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int SentInvitation::kIdFieldNumber;
const int SentInvitation::kTargetNameFieldNumber;
const int SentInvitation::kRoleFieldNumber;
const int SentInvitation::kAttributeFieldNumber;
const int SentInvitation::kCreationTimeFieldNumber;
const int SentInvitation::kProgramFieldNumber;
#endif  // !_MSC_VER

SentInvitation::SentInvitation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.SentInvitation)
}

void SentInvitation::InitAsDefaultInstance() {
}

SentInvitation::SentInvitation(const SentInvitation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.SentInvitation)
}

void SentInvitation::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = GOOGLE_ULONGLONG(0);
  target_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  role_ = 0u;
  creation_time_ = GOOGLE_ULONGLONG(0);
  program_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SentInvitation::~SentInvitation() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.SentInvitation)
  SharedDtor();
}

void SentInvitation::SharedDtor() {
  if (target_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_name_;
  }
  if (this != default_instance_) {
  }
}

void SentInvitation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SentInvitation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SentInvitation_descriptor_;
}

const SentInvitation& SentInvitation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

SentInvitation* SentInvitation::default_instance_ = NULL;

SentInvitation* SentInvitation::New() const {
  return new SentInvitation;
}

void SentInvitation::Swap(SentInvitation* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata SentInvitation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SentInvitation_descriptor_;
  metadata.reflection = SentInvitation_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int FriendInvitationParams::kTargetEmailFieldNumber;
const int FriendInvitationParams::kTargetBattleTagFieldNumber;
const int FriendInvitationParams::kRoleFieldNumber;
const int FriendInvitationParams::kAttributeFieldNumber;
const int FriendInvitationParams::kTargetNameFieldNumber;
const int FriendInvitationParams::kProgramFieldNumber;
const int FriendInvitationParams::kTargetPhoneNumberFieldNumber;
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int FriendInvitationParams::kFriendParamsFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::bgs::protocol::InvitationParams,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::friends::v1::FriendInvitationParams >, 11, false >
  FriendInvitationParams::friend_params(kFriendParamsFieldNumber, ::bgs::protocol::friends::v1::FriendInvitationParams::default_instance());
FriendInvitationParams::FriendInvitationParams()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.FriendInvitationParams)
}

void FriendInvitationParams::InitAsDefaultInstance() {
}

FriendInvitationParams::FriendInvitationParams(const FriendInvitationParams& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.FriendInvitationParams)
}

void FriendInvitationParams::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  target_email_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  program_ = 0u;
  target_phone_number_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FriendInvitationParams::~FriendInvitationParams() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.FriendInvitationParams)
  SharedDtor();
}

void FriendInvitationParams::SharedDtor() {
  if (target_email_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_email_;
  }
  if (target_battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_battle_tag_;
  }
  if (target_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_name_;
  }
  if (target_phone_number_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_phone_number_;
  }
  if (this != default_instance_) {
  }
}

void FriendInvitationParams::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FriendInvitationParams::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FriendInvitationParams_descriptor_;
}

const FriendInvitationParams& FriendInvitationParams::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

FriendInvitationParams* FriendInvitationParams::default_instance_ = NULL;

FriendInvitationParams* FriendInvitationParams::New() const {
  return new FriendInvitationParams;
}

void FriendInvitationParams::Swap(FriendInvitationParams* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FriendInvitationParams::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FriendInvitationParams_descriptor_;
  metadata.reflection = FriendInvitationParams_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int SubscribeResponse::kMaxFriendsFieldNumber;
const int SubscribeResponse::kMaxReceivedInvitationsFieldNumber;
const int SubscribeResponse::kMaxSentInvitationsFieldNumber;
const int SubscribeResponse::kRoleFieldNumber;
const int SubscribeResponse::kFriendsFieldNumber;
const int SubscribeResponse::kReceivedInvitationsFieldNumber;
const int SubscribeResponse::kSentInvitationsFieldNumber;
#endif  // !_MSC_VER

SubscribeResponse::SubscribeResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.SubscribeResponse)
}

void SubscribeResponse::InitAsDefaultInstance() {
}

SubscribeResponse::SubscribeResponse(const SubscribeResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.SubscribeResponse)
}

void SubscribeResponse::SharedCtor() {
  _cached_size_ = 0;
  max_friends_ = 0u;
  max_received_invitations_ = 0u;
  max_sent_invitations_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SubscribeResponse::~SubscribeResponse() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.SubscribeResponse)
  SharedDtor();
}

void SubscribeResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SubscribeResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscribeResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscribeResponse_descriptor_;
}

const SubscribeResponse& SubscribeResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

SubscribeResponse* SubscribeResponse::default_instance_ = NULL;

SubscribeResponse* SubscribeResponse::New() const {
  return new SubscribeResponse;
}

void SubscribeResponse::Swap(SubscribeResponse* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata SubscribeResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscribeResponse_descriptor_;
  metadata.reflection = SubscribeResponse_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int AcceptInvitationOptions::kRoleFieldNumber;
const int AcceptInvitationOptions::kProgramFieldNumber;
#endif  // !_MSC_VER

AcceptInvitationOptions::AcceptInvitationOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.friends.v1.AcceptInvitationOptions)
}

void AcceptInvitationOptions::InitAsDefaultInstance() {
}

AcceptInvitationOptions::AcceptInvitationOptions(const AcceptInvitationOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.friends.v1.AcceptInvitationOptions)
}

void AcceptInvitationOptions::SharedCtor() {
  _cached_size_ = 0;
  role_ = 0u;
  program_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AcceptInvitationOptions::~AcceptInvitationOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.friends.v1.AcceptInvitationOptions)
  SharedDtor();
}

void AcceptInvitationOptions::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AcceptInvitationOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AcceptInvitationOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AcceptInvitationOptions_descriptor_;
}

const AcceptInvitationOptions& AcceptInvitationOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_friends_5ftypes_2eproto();
  return *default_instance_;
}

AcceptInvitationOptions* AcceptInvitationOptions::default_instance_ = NULL;

AcceptInvitationOptions* AcceptInvitationOptions::New() const {
  return new AcceptInvitationOptions;
}

void AcceptInvitationOptions::Swap(AcceptInvitationOptions* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata AcceptInvitationOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AcceptInvitationOptions_descriptor_;
  metadata.reflection = AcceptInvitationOptions_reflection_;
  return metadata;
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace friends
}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)
