// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_types.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "role_types.pb.h"

#include <utility>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* Role_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Role_reflection_ = NULL;
const ::google::protobuf::Descriptor* RoleState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RoleState_reflection_ = NULL;

}  // namespace

void protobuf_AssignDesc_role_5ftypes_2eproto() {
  protobuf_AddDesc_role_5ftypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "role_types.proto");
  GOOGLE_CHECK(file != NULL);
  Role_descriptor_ = file->message_type(0);
  static const int Role_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, privilege_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, assignable_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, required_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, unique_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, relegation_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, kickable_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, removable_role_),
  };
  Role_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Role_descriptor_,
      Role::default_instance_,
      Role_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Role, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Role));
  RoleState_descriptor_ = file->message_type(1);
  static const int RoleState_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, assignable_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, required_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, unique_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, relegation_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, kickable_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, removable_role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, mentionable_role_),
  };
  RoleState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RoleState_descriptor_,
      RoleState::default_instance_,
      RoleState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoleState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RoleState));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_role_5ftypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Role_descriptor_, &Role::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RoleState_descriptor_, &RoleState::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_role_5ftypes_2eproto() {
  delete Role::default_instance_;
  delete Role_reflection_;
  delete RoleState::default_instance_;
  delete RoleState_reflection_;
}

void protobuf_AddDesc_role_5ftypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020role_types.proto\022\014bgs.protocol\"\302\001\n\004Rol"
    "e\022\n\n\002id\030\001 \002(\r\022\014\n\004name\030\002 \002(\t\022\021\n\tprivilege"
    "\030\003 \003(\t\022\033\n\017assignable_role\030\004 \003(\rB\002\020\001\022\020\n\010r"
    "equired\030\005 \001(\010\022\016\n\006unique\030\006 \001(\010\022\027\n\017relegat"
    "ion_role\030\007 \001(\r\022\031\n\rkickable_role\030\t \003(\rB\002\020"
    "\001\022\032\n\016removable_role\030\n \003(\rB\002\020\001\"\306\001\n\tRoleSt"
    "ate\022\014\n\004name\030\002 \001(\t\022\033\n\017assignable_role\030\004 \003"
    "(\rB\002\020\001\022\020\n\010required\030\005 \001(\010\022\016\n\006unique\030\006 \001(\010"
    "\022\027\n\017relegation_role\030\007 \001(\r\022\031\n\rkickable_ro"
    "le\030\t \003(\rB\002\020\001\022\032\n\016removable_role\030\n \003(\rB\002\020\001"
    "\022\034\n\020mentionable_role\030\013 \003(\rB\002\020\001B\002H\002", 434);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "role_types.proto", &protobuf_RegisterTypes);
  Role::default_instance_ = new Role();
  RoleState::default_instance_ = new RoleState();
  Role::default_instance_->InitAsDefaultInstance();
  RoleState::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_role_5ftypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_role_5ftypes_2eproto {
  StaticDescriptorInitializer_role_5ftypes_2eproto() {
    protobuf_AddDesc_role_5ftypes_2eproto();
  }
} static_descriptor_initializer_role_5ftypes_2eproto_;
// ===================================================================

#ifndef _MSC_VER
const int Role::kIdFieldNumber;
const int Role::kNameFieldNumber;
const int Role::kPrivilegeFieldNumber;
const int Role::kAssignableRoleFieldNumber;
const int Role::kRequiredFieldNumber;
const int Role::kUniqueFieldNumber;
const int Role::kRelegationRoleFieldNumber;
const int Role::kKickableRoleFieldNumber;
const int Role::kRemovableRoleFieldNumber;
#endif  // !_MSC_VER

Role::Role()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.Role)
}

void Role::InitAsDefaultInstance() {
}

Role::Role(const Role& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.Role)
}

void Role::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0u;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  required_ = false;
  unique_ = false;
  relegation_role_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Role::~Role() {
  // @@protoc_insertion_point(destructor:bgs.protocol.Role)
  SharedDtor();
}

void Role::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void Role::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Role::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Role_descriptor_;
}

const Role& Role::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_role_5ftypes_2eproto();
  return *default_instance_;
}

Role* Role::default_instance_ = NULL;

Role* Role::New() const {
  return new Role;
}

void Role::Swap(Role* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata Role::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Role_descriptor_;
  metadata.reflection = Role_reflection_;
  return metadata;
}

// ===================================================================

#ifndef _MSC_VER
const int RoleState::kNameFieldNumber;
const int RoleState::kAssignableRoleFieldNumber;
const int RoleState::kRequiredFieldNumber;
const int RoleState::kUniqueFieldNumber;
const int RoleState::kRelegationRoleFieldNumber;
const int RoleState::kKickableRoleFieldNumber;
const int RoleState::kRemovableRoleFieldNumber;
const int RoleState::kMentionableRoleFieldNumber;
#endif  // !_MSC_VER

RoleState::RoleState()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.RoleState)
}

void RoleState::InitAsDefaultInstance() {
}

RoleState::RoleState(const RoleState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.RoleState)
}

void RoleState::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  required_ = false;
  unique_ = false;
  relegation_role_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RoleState::~RoleState() {
  // @@protoc_insertion_point(destructor:bgs.protocol.RoleState)
  SharedDtor();
}

void RoleState::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void RoleState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoleState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoleState_descriptor_;
}

const RoleState& RoleState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_role_5ftypes_2eproto();
  return *default_instance_;
}

RoleState* RoleState::default_instance_ = NULL;

RoleState* RoleState::New() const {
  return new RoleState;
}

void RoleState::Swap(RoleState* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RoleState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RoleState_descriptor_;
  metadata.reflection = RoleState_reflection_;
  return metadata;
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)
