/*
 * Copyright (C) 2008-2011 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

/// List of Opcodes
enum Opcodes
{
    NUM_OPCODE_HANDLERS                             = (0xFFFF+1),
    UNKNOWN_OPCODE                                  = NUM_OPCODE_HANDLERS,
    
    CMSG_ACCEPT_LEVEL_GRANT                          = 0xDC4B, // 14545
    CMSG_ACCEPT_TRADE                                = 0x00, // 
    CMSG_ACTIVATETAXI                                = 0x00, // 
    CMSG_ACTIVATETAXIEXPRESS                         = 0x00, // 
    CMSG_ADD_FRIEND                                  = 0x5C57, // 14545
    CMSG_ADD_IGNORE                                  = 0xCEEA, // 14545
    CMSG_ADD_VOICE_IGNORE                            = 0xA7A, // 14545
    CMSG_ALTER_APPEARANCE                            = 0x00, // 
    CMSG_AREATRIGGER                                 = 0x5862, // 14545
    CMSG_AREA_SPIRIT_HEALER_QUERY                    = 0xDC7E, // 14545
    CMSG_AREA_SPIRIT_HEALER_QUEUE                    = 0x00, // 
    CMSG_ARENA_TEAM_ACCEPT                           = 0x00, // 
    CMSG_ARENA_TEAM_DECLINE                          = 0x00, // 
    CMSG_ARENA_TEAM_DISBAND                          = 0x4A5A, // 14545
    CMSG_ARENA_TEAM_INVITE                           = 0x4862, // 14545
    CMSG_ARENA_TEAM_LEADER                           = 0x8F3, // 14545
    CMSG_ARENA_TEAM_LEAVE                            = 0x48EB, // 14545
    CMSG_ARENA_TEAM_QUERY                            = 0x872, // 14545
    CMSG_ARENA_TEAM_REMOVE                           = 0xCE5E, // 14545
    CMSG_ARENA_TEAM_ROSTER                           = 0x00, // 
    CMSG_ATTACKSTOP                                  = 0x00, // 
    CMSG_ATTACKSWING                                 = 0x00, // 
    CMSG_AUCTION_LIST_BIDDER_ITEMS                   = 0x00, // 
    CMSG_AUCTION_LIST_ITEMS                          = 0xDC5F, // 14545
    CMSG_AUCTION_LIST_OWNER_ITEMS                    = 0x00, // 
    CMSG_AUCTION_PLACE_BID                           = 0x8E76, // 14545
    CMSG_AUCTION_REMOVE_ITEM                         = 0xCEC3, // 14545
    CMSG_AUCTION_SELL_ITEM                           = 0xCE6, // 14545
    CMSG_AUTH_SESSION                                = 0x1019, // 14545
    CMSG_AUTOEQUIP_GROUND_ITEM                       = 0x00, //
    CMSG_AUTOEQUIP_ITEM                              = 0x8E66, // 14545
    CMSG_AUTOEQUIP_ITEM_SLOT                         = 0x00, // 
    CMSG_AUTO_DECLINE_GUILD_INVITES                  = 0x586F, // 14545
    CMSG_AUTOSTORE_BAG_ITEM                          = 0x00, // 
    CMSG_AUTOSTORE_GROUND_ITEM                       = 0x00, //
    CMSG_AUTOSTORE_LOOT_ITEM                         = 0x00, // 
    CMSG_BANKER_ACTIVATE                             = 0x00, // 
    CMSG_BATTLEFIELD_JOIN                            = 0x00, // 
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA              = 0x00, // 
    CMSG_BATTLEFIELD_STATUS                          = 0x00, // 
    MSG_BATTLEGROUND_PLAYER_POSITIONS                = 0x00, // 
    CMSG_BATTLEMASTER_JOIN_ARENA                     = 0x00, // 
    CMSG_BEGIN_TRADE                                 = 0x00, //
    CMSG_BINDER_ACTIVATE                             = 0x00, // 
    CMSG_BOT_DETECTED2                               = 0x00, //
    CMSG_BUG                                         = 0x1A77, // 14545
    CMSG_BUSY_TRADE                                  = 0x00, //
    CMSG_BUYBACK_ITEM                                = 0xDEE6, // 14545
    CMSG_BUY_BANK_SLOT                               = 0x487F, // 14545
    CMSG_BUY_ITEM                                    = 0x00, // 
    CMSG_CALENDAR_ADD_EVENT                          = 0x1CF3, // 14545
    CMSG_CALENDAR_ARENA_TEAM                         = 0x00, // 
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP               = 0x00, // 
    CMSG_CALENDAR_COPY_EVENT                         = 0x00, // 
    CMSG_CALENDAR_EVENT_INVITE                       = 0x1EDA, // 14545
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS             = 0x00, // 
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                = 0x00, // 
    CMSG_CALENDAR_EVENT_STATUS                       = 0x00, // 
    CMSG_CALENDAR_GET_EVENT                          = 0x00, // 
    CMSG_CALENDAR_GET_NUM_PENDING                    = 0x00, // 
    CMSG_CALENDAR_GUILD_FILTER                       = 0x00, // 
    CMSG_CALENDAR_REMOVE_EVENT                       = 0x00, // 
    CMSG_CALENDAR_UPDATE_EVENT                       = 0x5CD2, // 14545
    CMSG_CANCEL_AURA                                 = 0x00, // 
    CMSG_CANCEL_AUTO_REPEAT_SPELL                    = 0x5CEE, // 14545
    CMSG_CANCEL_CAST                                 = 0x00, // 
    CMSG_CANCEL_CHANNELLING                          = 0xC8FE, // 14545
    CMSG_CANCEL_GROWTH_AURA                          = 0xDEF7, // 14545
    CMSG_CANCEL_MOUNT_AURA                           = 0x00, // 
    CMSG_CANCEL_TEMP_ENCHANTMENT                     = 0x00, // 
    CMSG_CANCEL_TRADE                                = 0x35A5, // 14545
    CMSG_CAST_SPELL                                  = 0x00, // 
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE          = 0x00, //
    CMSG_CHANNEL_ANNOUNCEMENTS                       = 0x00, // 
    CMSG_CHANNEL_BAN                                 = 0x00, // 
    CMSG_CHANNEL_DISPLAY_LIST                        = 0x00, // 
    CMSG_CHANNEL_INVITE                              = 0x00, // 
    CMSG_CHANNEL_KICK                                = 0x00, // 
    CMSG_CHANNEL_LIST                                = 0x00, // 
    CMSG_CHANNEL_MODERATOR                           = 0x00, // 
    CMSG_CHANNEL_MUTE                                = 0x00, // 
    CMSG_CHANNEL_OWNER                               = 0x00, // 
    CMSG_CHANNEL_PASSWORD                            = 0x00, // 
    CMSG_CHANNEL_ROSTER_INFO                         = 0x00, //
    CMSG_CHANNEL_SET_OWNER                           = 0x00, //
    CMSG_CHANNEL_UNBAN                               = 0x00, // 
    CMSG_CHANNEL_UNMODERATOR                         = 0x00, // 
    CMSG_CHANNEL_UNMUTE                              = 0x00, // 
    CMSG_CHAR_CREATE                                 = 0x1AC6, // 14545
    CMSG_CHAR_CUSTOMIZE                              = 0xDECF, // 14545
    CMSG_CHAR_DELETE                                 = 0x1ED3, // 14545
    CMSG_CHAR_ENUM                                   = 0x4A8B, // 14545
    CMSG_CHAR_FACTION_CHANGE                         = 0xCCEE, // 14545
    CMSG_CHAR_RACE_CHANGE                            = 0xDC57, // 14545
    CMSG_CHAR_RENAME                                 = 0x5E6F, // 14545
    CMSG_CLEAR_CHANNEL_WATCH                         = 0x9CC2, // 14545
    CMSG_CLEAR_TRADE_ITEM                            = 0x00, // 
    CMSG_COMMENTATOR_ENABLE                          = 0x1CF7, // 14545
    CMSG_COMMENTATOR_ENTER_INSTANCE                  = 0x8EF6, // 14545
    CMSG_COMMENTATOR_EXIT_INSTANCE                   = 0x4C7B, // 14545
    CMSG_COMMENTATOR_GET_MAP_INFO                    = 0xDEE7, // 14545
    CMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x9EF3, // 14545
    CMSG_COMMENTATOR_INSTANCE_COMMAND                = 0x5CEB, // 14545
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND          = 0x9C4E, // 14545
    CMSG_COMMENTATOR_START_WARGAME                   = 0x00, //
    CMSG_COMPLAIN                                    = 0x00, // 
    CMSG_COMPLETE_CINEMATIC                          = 0x1A6F, // 14545
    CMSG_COMPLETE_MOVIE                              = 0x00, // 
    CMSG_CONTACT_LIST                                = 0xCECF, // 14545
    CMSG_CORPSE_MAP_POSITION_QUERY                   = 0xDC7F, // 14545
    CMSG_CREATURE_QUERY                              = 0x5A7E, // 14545
    CMSG_DANCE_QUERY                                 = 0x5C5E, // 14545
    CMSG_DECLINE_CHANNEL_INVITE                      = 0x00, // 
    CMSG_DEL_FRIEND                                  = 0xC852, // 14545
    CMSG_DEL_IGNORE                                  = 0x8ADA, // 14545
    CMSG_DEL_VOICE_IGNORE                            = 0x8C73, // 14545
    CMSG_DESTROYITEM                                 = 0x4E7A, // 14545
    CMSG_DESTROY_ITEMS                               = 0x00, //
    CMSG_DUEL_ACCEPTED                               = 0x00, // 
    CMSG_DUEL_CANCELLED                              = 0x00, // 
    CMSG_EJECT_PASSENGER                             = 0x00, // 
    CMSG_EQUIPMENT_SET_DELETE                        = 0x00, // 
    CMSG_EQUIPMENT_SET_SAVE                          = 0x00, // 
    CMSG_EQUIPMENT_SET_USE                           = 0x4853, // 14545
    CMSG_EMOTE                                       = 0x9843, // 14545
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK          = 0x00, //
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK               = 0x00, //
    CMSG_FORCE_MOVE_ROOT_ACK                         = 0x00, // 
    CMSG_FORCE_MOVE_UNROOT_ACK                       = 0x00, // 
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                 = 0x00, //
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK             = 0x00, //
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                  = 0x00, // 
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK            = 0x00, //
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                 = 0x00, //
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                  = 0x00, //
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                 = 0x00, //
    CMSG_GAMEOBJECT_QUERY                            = 0xCEFF, // 14545
    CMSG_GAMEOBJ_REPORT_USE                          = 0x00, // 
    CMSG_GAMEOBJ_USE                                 = 0x00, // 
    CMSG_GAMESPEED_SET                               = 0x00, //
    CMSG_GAMETIME_SET                                = 0x00, // 
    CMSG_GET_MAIL_LIST                               = 0xB284, // 14545
    CMSG_GET_MIRRORIMAGE_DATA                        = 0xDAF3, // 14545
    CMSG_GETDEATHBINDZONE                            = 0x00, //
    CMSG_GHOST                                       = 0x00, //
    CMSG_GM_INVIS                                    = 0x00, //
    CMSG_GMRESPONSE_RESOLVE                          = 0x00, // 
    CMSG_GMSURVEY_SUBMIT                             = 0x00, // 
    CMSG_GMTICKET_CREATE                             = 0x00, // 
    CMSG_GMTICKET_DELETETICKET                       = 0x00, // 
    CMSG_GMTICKET_GETTICKET                          = 0x00, // 
    CMSG_GMTICKET_SYSTEMSTATUS                       = 0x4A7A, // 14545
    CMSG_GMTICKET_UPDATETEXT                         = 0x8A7B, // 14545
    CMSG_GM_NUKE                                     = 0x00, //
    CMSG_GM_SET_SECURITY_GROUP                       = 0x00, //
    CMSG_GM_REPORT_LAG                               = 0x00, // 
    CMSG_GOSSIP_HELLO                                = 0xAD3, // 14545
    CMSG_GOSSIP_SELECT_OPTION                        = 0x984E, // 14545
    CMSG_GRANT_LEVEL                                 = 0x1CD6, // 14545
    CMSG_GROUP_ACCEPT                                = 0x00, //
    CMSG_GROUP_ASSISTANT_LEADER                      = 0xC8CA, // 14545
    CMSG_GROUP_CANCEL                                = 0x00, //
    CMSG_GROUP_CHANGE_SUB_GROUP                      = 0x1AD2, // 14545
    CMSG_GROUP_DECLINE                               = 0x00, //
    CMSG_GROUP_DISBAND                               = 0x00, // 
    CMSG_GROUP_INVITE                                = 0x00, // 
    CMSG_GROUP_RAID_CONVERT                          = 0xC85A, // 14545
    CMSG_GROUP_SET_LEADER                            = 0xCEC7, // 14545
    CMSG_GROUP_SWAP_SUB_GROUP                        = 0x5AD7, // 14545
    CMSG_GROUP_UNINVITE                              = 0x00, //
    CMSG_GROUP_UNINVITE_GUID                         = 0x00, // 
    CMSG_GUILD_ACCEPT                                = 0x00, //
    CMSG_GUILD_BANKER_ACTIVATE                       = 0x4E77, // 14545
    CMSG_GUILD_BANK_BUY_TAB                          = 0x00, // 
    CMSG_GUILD_BANK_DEPOSIT_MONEY                    = 0x00, // 
    CMSG_GUILD_BANK_NOTE                             = 0x00, // 
    CMSG_GUILD_BANK_QUERY_TAB                        = 0xDE46, // 14545
    CMSG_GUILD_BANK_SWAP_ITEMS                       = 0x85B, // 14545
    CMSG_GUILD_BANK_UPDATE_TAB                       = 0x00, // 
    CMSG_GUILD_BANK_WITHDRAW_MONEY                   = 0x00, // 
    CMSG_GUILD_CREATE                                = 0x00, //
    CMSG_GUILD_DECLINE                               = 0x00, //
    CMSG_GUILD_DEMOTE                                = 0x00, //
    CMSG_GUILD_DISBAND                               = 0x00, //
    CMSG_GUILD_INFO                                  = 0xCE76, // 14545
    CMSG_GUILD_INVITE                                = 0x00, // 
    CMSG_GUILD_PROMOTE                               = 0x00, //
    CMSG_GUILD_QUERY                                 = 0x00, // 
    CMSG_GUILD_LEADER                                = 0x00, //
    CMSG_GUILD_LEAVE                                 = 0x00, //
    CMSG_GUILD_MOTD                                  = 0x00, //
    CMSG_GUILD_REMOVE                                = 0x00, //
    CMSG_GUILD_ROSTER                                = 0x00, //
    CMSG_HEARTH_AND_RESURRECT                        = 0x00, // 
    CMSG_IGNORE_TRADE                                = 0x00, //
    CMSG_INITIATE_TRADE                              = 0x00, //
    CMSG_INSPECT                                     = 0x9A7B, // 14545
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE              = 0x8CF7, // 14545
    CMSG_ITEM_QUERY_SINGLE                           = 0x8E2, // 14545
    CMSG_ITEM_QUERY_MULTIPLE                         = 0x00, // 
    CMSG_ITEM_REFUND                                 = 0xCC3, // 14545
    CMSG_ITEM_REFUND_INFO                            = 0x1C7E, // 14545
    CMSG_ITEM_TEXT_QUERY                             = 0x4AEB, // 14545
    CMSG_JOIN_CHANNEL                                = 0x3441, // 14545
    CMSG_KEEP_ALIVE                                  = 0xC87A, // 14545
    CMSG_LEARN_PREVIEW_TALENTS                       = 0xDEE3, // 14545
    CMSG_LEARN_PREVIEW_TALENTS_PET                   = 0x9AFB, // 14545
    CMSG_LEARN_TALENT                                = 0x98F3, // 14545
    CMSG_LEAVE_BATTLEFIELD                           = 0x1AE7, // 14545
    CMSG_LEAVE_CHANNEL                               = 0x00, // 
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                 = 0x00, // 
    CMSG_LFG_GET_PLAYER_INFO                         = 0x00, // 
    CMSG_LFG_JOIN                                    = 0x00, // 
    CMSG_LFG_LEAVE                                   = 0x00, // 
    CMSG_LFG_PROPOSAL_RESULT                         = 0x00, // 
    SMSG_LFG_BOOT_PLAYER                             = 0x00, // 
    CMSG_LFG_SET_ROLES                               = 0x4843, // 14545
    CMSG_LFG_TELEPORT                                = 0x8C7A, // 14545
    CMSG_LIST_INVENTORY                              = 0xDCFE, // 14545
    CMSG_LOG_DISCONNECT                              = 0x00, // 
    CMSG_LOGOUT_CANCEL                               = 0xA76, // 14545
    CMSG_LOGOUT_REQUEST                              = 0x4C7A, // 14545
    CMSG_LOOT                                        = 0x00, // 
    CMSG_LOOT_METHOD                                 = 0x00, // 
    CMSG_LOOT_MONEY                                  = 0x00, // 
    CMSG_LOOT_RELEASE                                = 0x4A6A, // 14545
    CMSG_LOOT_ROLL                                   = 0x00, // 
    CMSG_MAIL_CREATE_TEXT_ITEM                       = 0x886E, // 14545
    CMSG_MAIL_DELETE                                 = 0x4CCF, // 14545
    CMSG_MAIL_MARK_AS_READ                           = 0x00, // 
    CMSG_MAIL_RETURN_TO_SENDER                       = 0x587E, // 14545
    CMSG_MAIL_TAKE_ITEM                              = 0xCC2, // 14545
    CMSG_MAIL_TAKE_MONEY                             = 0x4CD6, // 14545
    CMSG_MEETINGSTONE_INFO                           = 0xCA5B, // 14545
    CMSG_MESSAGECHAT_AFK                             = 0x00, // 
    CMSG_MESSAGECHAT_BATTLEGROUND                    = 0x00, // 
    CMSG_MESSAGECHAT_BATTLEGROUND_LEADER             = 0x00, //
    CMSG_MESSAGECHAT_CHANNEL                         = 0x00, // 
    CMSG_MESSAGECHAT_DND                             = 0x00, // 
    CMSG_MESSAGECHAT_EMOTE                           = 0x00, // 
    CMSG_MESSAGECHAT_GUILD                           = 0x00, // 
    CMSG_MESSAGECHAT_OFFICER                         = 0x00, // 
    CMSG_MESSAGECHAT_PARTY                           = 0x00, // 
    CMSG_MESSAGECHAT_PARTY_LEADER                    = 0x00, //
    CMSG_MESSAGECHAT_RAID                            = 0x00, // 
    CMSG_MESSAGECHAT_RAID_LEADER                     = 0x00, //
    CMSG_MESSAGECHAT_RAID_WARNING                    = 0x00, // 
    CMSG_MESSAGECHAT_SAY                             = 0x00, // 
    CMSG_MESSAGECHAT_WHISPER                         = 0x00, // 
    CMSG_MESSAGECHAT_YELL                            = 0x00, // 
    CMSG_MINIGAME_MOVE                               = 0x00, // 
    CMSG_MOUNTSPECIAL_ANIM                           = 0x00, // 
    CMSG_MOVE_KNOCK_BACK_ACK                         = 0x00, //
    CMSG_MOVE_SET_RAW_POSITION                       = 0x00, //
    CMSG_MOVE_TIME_SKIPPED                           = 0x00, // 
    CMSG_ENABLE_NAGLE                                = 0x00, // 
    CMSG_NAME_QUERY                                  = 0x586A, // 14545
    CMSG_NEW_SPELL_SLOT                              = 0x00, //
    CMSG_NEXT_CINEMATIC_CAMERA                       = 0x8E63, // 14545
    CMSG_NPC_TEXT_QUERY                              = 0x5C63, // 14545
    CMSG_OFFER_PETITION                              = 0xC8DE, // 14545
    CMSG_OPEN_ITEM                                   = 0x88C7, // 14545
    CMSG_OPENING_CINEMATIC                           = 0xD8D2, // 14545
    CMSG_OPT_OUT_OF_LOOT                             = 0x00, // 
    CMSG_PAGE_TEXT_QUERY                             = 0x8A5F, // 14545
    CMSG_PETITION_BUY                                = 0x8E4E, // 14545
    CMSG_PETITION_QUERY                              = 0xCEF3, // 14545
    CMSG_PETITION_SHOWLIST                           = 0x00, // 
    CMSG_PETITION_SHOW_SIGNATURES                    = 0x00, // 
    CMSG_PETITION_SIGN                               = 0x4A5E, // 14545
    CMSG_PET_ABANDON                                 = 0x00, //
    CMSG_PET_ACTION                                  = 0x1AEA, // 14545
    CMSG_PET_CANCEL_AURA                             = 0x00, // 
    CMSG_PET_CAST_SPELL                              = 0x00, // 
    CMSG_PET_LEARN_TALENT                            = 0x48E6, // 14545
    CMSG_PET_NAME_QUERY                              = 0xDA76, // 14545
    CMSG_PET_RENAME                                  = 0x00, // 
    CMSG_PET_SET_ACTION                              = 0x00, // 
    CMSG_PET_SPELL_AUTOCAST                          = 0x00, // 
    CMSG_PET_STOP_ATTACK                             = 0x00, // 
    CMSG_PING                                        = 0x1008, // 14545
    CMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x00, // 
    CMSG_PLAYED_TIME                                 = 0x5A56, // 14545
    CMSG_PLAYER_LOGIN                                = 0x0898, // 14545
    CMSG_PLAYER_LOGOUT                               = 0x1CEE, // 14545
    CMSG_PLAYER_VEHICLE_ENTER                        = 0x00, // 
    CMSG_PLAY_DANCE                                  = 0x5857, // 14545
    CMSG_PUSHQUESTTOPARTY                            = 0xA47, // 14545
    CMSG_QUERY_GUILD_REWARDS                         = 0x00, //
    CMSG_QUERY_GUILD_MAX_XP                          = 0x00, //
    CMSG_QUERY_GUILD_XP                              = 0x00, //
    CMSG_QUERY_TIME                                  = 0x18FE, // 14545
    CMSG_QUEST_QUERY                                 = 0xCE7F, // 14545
    CMSG_QUERY_QUESTS_COMPLETED                      = 0x98DF, // 14545
    CMSG_QUESTLOG_SWAP_QUEST                         = 0x00, //
    CMSG_QUESTGIVER_ACCEPT_QUEST                     = 0x8CD3, // 14545
    CMSG_QUESTGIVER_CANCEL                           = 0xC86A, // 14545
    CMSG_QUESTGIVER_CHOOSE_REWARD                    = 0x18F3, // 14545
    CMSG_QUESTGIVER_COMPLETE_QUEST                   = 0xCCE3, // 14545
    CMSG_QUESTGIVER_HELLO                            = 0x00, // 
    CMSG_QUESTGIVER_QUERY_QUEST                      = 0x8CE7, // 14545
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                 = 0x00, //
    CMSG_QUESTGIVER_REQUEST_REWARD                   = 0xD8E7, // 14545
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY            = 0xC8DB, // 14545
    CMSG_QUESTGIVER_STATUS_QUERY                     = 0x88C6, // 14545
    CMSG_QUESTLOG_REMOVE_QUEST                       = 0x8EFF, // 14545
    CMSG_QUEST_POI_QUERY                             = 0x00, // 
    CMSG_QUEST_CONFIRM_ACCEPT                        = 0xC63, // 14545
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                = 0xCCDB, // 14545
    CMSG_READ_ITEM                                   = 0x00, // 
    CMSG_REALM_SPLIT                                 = 0xDC66, // 14545
    CMSG_RECLAIM_CORPSE                              = 0x88DB, // 14545
    CMSG_REDIRECTION_AUTH_PROOF                      = 0x00, // 
    CMSG_REPAIR_ITEM                                 = 0xCF3, // 14545
    CMSG_REPOP_REQUEST                               = 0x8872, // 14545
    CMSG_REPORT_PVP_AFK                              = 0x00, // 
    CMSG_REPLACE_ACCOUNT_DATA                        = 0x00, // 
    CMSG_REQUEST_ACCOUNT_DATA                        = 0x00, // 
    CMSG_REQUEST_CATEGORY_COOLDOWNS                  = 0x00, // 
    CMSG_REQUEST_CEMETERY_LIST                       = 0x00, // 
    CMSG_REQUEST_PARTY_MEMBER_STATS                  = 0x987E, // 14545
    CMSG_REQUEST_PET_INFO                            = 0x9A47, // 14545
    CMSG_REQUEST_PLAYER_VEHICLE_EXIT                 = 0xCC6, // 14545
    CMSG_REQUEST_RATED_BG_INFO                       = 0x00, // 
    CMSG_REQUEST_RAID_INFO                           = 0x00, // 
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                   = 0xCAD6, // 14545
    CMSG_REQUEST_VEHICLE_PREV_SEAT                   = 0x1AE2, // 14545
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                 = 0x01, // temp to fix switch case value error
    CMSG_RESET_INSTANCES                             = 0x9EEA, // 14545
    CMSG_RESURRECT_RESPONSE                          = 0x00, // 
    CMSG_RETURN_TO_GRAVEYARD                         = 0x00, // 
    CMSG_SAVE_PLAYER                                 = 0x00, //
    CMSG_SEARCH_LFG_JOIN                             = 0x00, // 
    CMSG_SEARCH_LFG_LEAVE                            = 0x00, // 
    CMSG_SELF_RES                                    = 0xCCFE, // 14545
    CMSG_SELL_ITEM                                   = 0x5EE3, // 14545
    CMSG_SET_ACTIONBAR_TOGGLES                       = 0x584F, // 14545
    CMSG_SET_ACTION_BUTTON                           = 0x00, // 
    CMSG_SET_ACTIVE_MOVER                            = 0x00, // 
    CMSG_SET_ACTIVE_VOICE_CHANNEL                    = 0x00, // 
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                   = 0xC863, // 14545
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                   = 0x4CE7, // 14545
    CMSG_SET_CHANNEL_WATCH                           = 0x00, //
    CMSG_SET_CONTACT_NOTES                           = 0x1AF3, // 14545
    CMSG_SET_FACTION_CHEAT                           = 0x00, //
    CMSG_SET_GUILD_BANK_TEXT                         = 0x00, // 
    CMSG_SET_LFG_COMMENT                             = 0x00, // 
    CMSG_SET_PLAYER_DECLINED_NAMES                   = 0xC847, // 14545
    CMSG_SET_PRIMARY_TALENT_TREE                     = 0x185E, // 14545
    CMSG_SET_SAVED_INSTANCE_EXTEND                   = 0x8E62, // 14545
    CMSG_SET_SELECTION                               = 0x4C4E, // 14545
    CMSG_SET_SKILL_CHEAT                             = 0x00, //
    CMSG_SET_TAXI_BENCHMARK_MODE                     = 0x1EFF, // 14545
    CMSG_SET_TITLE                                   = 0x00, // 
    CMSG_SET_TRADE_GOLD                              = 0x00, //
    CMSG_SET_TRADE_ITEM                              = 0x00, // 
    CMSG_SETDEATHBINDPOINT                           = 0x00, //
    CMSG_SETSHEATHED                                 = 0xCA5F, // 14545
    CMSG_SHOWING_CLOAK                               = 0x8AE3, // 14545
    CMSG_SHOWING_HELM                                = 0xCEFA, // 14545
    CMSG_SERVERTIME                                  = 0x00, //
    CMSG_SOCKET_GEMS                                 = 0x00, // 
    CMSG_SPIRIT_HEALER_ACTIVATE                      = 0x5AEB, // 14545
    CMSG_SPLIT_ITEM                                  = 0x00, // 
    CMSG_STANDSTATECHANGE                            = 0x9EC6, // 14545
    CMSG_START_QUEST                                 = 0x00, // 
    CMSG_STOP_DANCE                                  = 0x00, // 
    CMSG_STORE_LOOT_IN_SLOT                          = 0x00, //
    CMSG_SUMMON_RESPONSE                             = 0xD84E, // 14545
    CMSG_SWAP_ITEM                                   = 0xDED6, // 14545
    CMSG_SWAP_INV_ITEM                               = 0x5CE7, // 14545
    CMSG_TELEPORT_TO_UNIT                            = 0x8C72, // 14545
    CMSG_TEXT_EMOTE                                  = 0x00, // 
    CMSG_TIME_SYNC_RESP                              = 0x00, // 
    CMSG_TAXICLEARALLNODES                           = 0x00, // 
    CMSG_TAXIENABLEALLNODES                          = 0x00, // 
    CMSG_TAXINODE_STATUS_QUERY                       = 0x98E3, // 14545
    CMSG_TAXIQUERYAVAILABLENODES                     = 0x00, //
    CMSG_TAXISHOWNODES                               = 0x00, // 
    CMSG_TOGGLE_PVP                                  = 0x8ECA, // 14545
    CMSG_TOTEM_DESTROYED                             = 0x00, // 
    SMSG_TRAINER_BUY_SUCCEEDED                       = 0xAF7, // 14545
    CMSG_TRAINER_LIST                                = 0xCC7F, // 14545
    CMSG_TRIGGER_CINEMATIC_CHEAT                     = 0x00, //
    CMSG_TURN_IN_PETITION                            = 0x9C67, // 14545
    CMSG_TUTORIAL_CLEAR                              = 0x00, // 
    CMSG_TUTORIAL_FLAG                               = 0x00, // 
    CMSG_TUTORIAL_RESET                              = 0x00, // 
    CMSG_UNACCEPT_TRADE                              = 0x00, // 
    CMSG_UNLEARN_SKILL                               = 0xAC3, // 14545
    CMSG_UNREGISTER_ALL_ADDON_PREFIXES               = 0x00, // 
    CMSG_UNUSED2                                     = 0x00, //
    CMSG_UPDATE_ACCOUNT_DATA                         = 0x4AFE, // 14545
    CMSG_USE_ITEM                                    = 0x00, // 
    CMSG_VOICE_SESSION_ENABLE                        = 0x00, // 
    CMSG_VIOLENCE_LEVEL                              = 0x00, // 
    CMSG_WARDEN_DATA                                 = 0x5847, // 14545
    CMSG_WHO                                         = 0x9AD7, // 14545
    CMSG_WHOIS                                       = 0xCCE6, // 14545
    CMSG_WORLD_LOGIN                                 = 0x00, // 
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x58F6, // 14545
    CMSG_WORLD_TELEPORT                              = 0x00, // 
    CMSG_WRAP_ITEM                                   = 0x00, //
    CMSG_ZONEUPDATE                                  = 0x00, // 
    MSG_AUCTION_HELLO                                = 0x00, // 
    MSG_CHANNEL_START                                = 0x00, // 
    MSG_CHANNEL_UPDATE                               = 0x00, // 
    MSG_CORPSE_QUERY                                 = 0x00, // 
    MSG_GM_BIND_OTHER                                = 0x00, //
    MSG_GM_SHOWLABEL                                 = 0x00, //
    MSG_GM_SUMMON                                    = 0x00, //
    MSG_GUILD_BANK_LOG_QUERY                         = 0x00, // 
    MSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0xDE77, // 14545
    MSG_GUILD_EVENT_LOG_QUERY                        = 0x00, // 
    MSG_GUILD_PERMISSIONS                            = 0x00, // 
    MSG_INSPECT_ARENA_TEAMS                          = 0x00, // 
    MSG_LIST_STABLED_PETS                            = 0x88CA, // 14545
    MSG_MINIMAP_PING                                 = 0x00, // 
    MSG_MOVE_FALL_LAND                               = 0x00, // 
    MSG_MOVE_HEARTBEAT                               = 0x00, // 
    MSG_MOVE_HOVER                                   = 0x00, //
    MSG_MOVE_JUMP                                    = 0xE4E, // 14545
    MSG_MOVE_KNOCK_BACK                              = 0x00, //
    MSG_MOVE_ROOT                                    = 0x00, //
    MSG_MOVE_SET_ALL_SPEED_CHEAT                     = 0x00, //
    MSG_MOVE_SET_FACING                              = 0x00, // 
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0x00, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT             = 0x00, //
    MSG_MOVE_SET_FLIGHT_SPEED                        = 0x00, //
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                  = 0x00, //
    MSG_MOVE_SET_PITCH                               = 0x00, // 
    MSG_MOVE_SET_PITCH_RATE                          = 0x00, //
    MSG_MOVE_SET_RAW_POSITION_ACK                    = 0x00, //
    MSG_MOVE_SET_RUN_BACK_SPEED                      = 0x00, //
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                = 0x00, //
    MSG_MOVE_SET_RUN_MODE                            = 0x00, //
    MSG_MOVE_SET_RUN_SPEED_CHEAT                     = 0x00, //
    MSG_MOVE_SET_RUN_SPEED                           = 0x00, //
    MSG_MOVE_SET_SWIM_BACK_SPEED                     = 0x00, //
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT               = 0x00, //
    MSG_MOVE_SET_SWIM_SPEED                          = 0x00, //
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                    = 0x00, //
    MSG_MOVE_SET_TURN_RATE                           = 0x00, //
    MSG_MOVE_SET_TURN_RATE_CHEAT                     = 0x00, //
    MSG_MOVE_SET_WALK_MODE                           = 0x00, //
    MSG_MOVE_SET_WALK_SPEED                          = 0x00, //
    MSG_MOVE_SET_WALK_SPEED_CHEAT                    = 0x00, //
    MSG_MOVE_START_ASCEND                            = 0x00, // 
    MSG_MOVE_START_DESCEND                           = 0x00, // 
    MSG_MOVE_STOP_ASCEND                             = 0x00, // 
    MSG_MOVE_START_BACKWARD                          = 0x00, // 
    MSG_MOVE_START_FORWARD                           = 0x00, // 
    MSG_MOVE_START_PITCH_UP                          = 0x00, //
    MSG_MOVE_START_PITCH_DOWN                        = 0x00, //
    MSG_MOVE_START_TURN_LEFT                         = 0x00, // 
    MSG_MOVE_START_TURN_RIGHT                        = 0x00, // 
    MSG_MOVE_START_STRAFE_LEFT                       = 0x00, // 
    MSG_MOVE_START_STRAFE_RIGHT                      = 0x00, // 
    MSG_MOVE_START_SWIM                              = 0x00, // 
    MSG_MOVE_STOP                                    = 0x00, // 
    MSG_MOVE_STOP_PITCH                              = 0x00, //
    MSG_MOVE_STOP_TURN                               = 0x00, // 
    MSG_MOVE_STOP_STRAFE                             = 0x00, // 
    MSG_MOVE_STOP_SWIM                               = 0x00, //
    MSG_MOVE_TOGGLE_LOGGING                          = 0x00, //
    MSG_MOVE_TIME_SKIPPED                            = 0x00, // 
    MSG_MOVE_TELEPORT                                = 0x00, //
    MSG_MOVE_TELEPORT_ACK                            = 0x00, //
    MSG_MOVE_TELEPORT_CHEAT                          = 0x00, //
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                  = 0x00, //
    MSG_MOVE_TOGGLE_FALL_LOGGING                     = 0x00, //
    MSG_MOVE_UNROOT                                  = 0x00, //
    MSG_MOVE_WORLDPORT_ACK                           = 0x00, // 
    MSG_NOTIFY_PARTY_SQUELCH                         = 0x00, // 
    MSG_PARTY_ASSIGNMENT                             = 0x00, // 
    MSG_PETITION_DECLINE                             = 0x98E7, // 14545
    MSG_PETITION_RENAME                              = 0x4857, // 14545
    MSG_PVP_LOG_DATA                                 = 0x00, // 
    MSG_QUERY_GUILD_BANK_TEXT                        = 0x00, // 
    MSG_QUERY_NEXT_MAIL_TIME                         = 0x00, // 
    MSG_QUEST_PUSH_RESULT                            = 0x1863, // 14545
    MSG_RAID_READY_CHECK                             = 0x584E, // 14545
    MSG_RAID_READY_CHECK_CONFIRM                     = 0x584E, // 14545
    MSG_RAID_READY_CHECK_FINISHED                    = 0x00, // 
    MSG_RAID_TARGET_UPDATE                           = 0x00, // 
    MSG_RANDOM_ROLL                                  = 0x4C57, // 14545
    MSG_SAVE_GUILD_EMBLEM                            = 0x00, // 
    MSG_SET_DUNGEON_DIFFICULTY                       = 0xC4F, // 14545
    MSG_SET_RAID_DIFFICULTY                          = 0x1A5A, // 14545
    MSG_TABARDVENDOR_ACTIVATE                        = 0x98EB, // 14545
    MSG_TALENT_WIPE_CONFIRM                          = 0x00, // 
    OBSOLETE_DROP_ITEM                               = 0x00, //
    SMSG_ACCOUNT_DATA_TIMES                          = 0x00, // 
    SMSG_ACHIEVEMENT_DELETED                         = 0x00, // 
    SMSG_ACHIEVEMENT_EARNED                          = 0x00, // 
    SMSG_ACTION_BUTTONS                              = 0x00, // 
    SMSG_ACTIVATETAXIREPLY                           = 0x8E4F, // 14545
    SMSG_ADDON_INFO                                  = 0x9863, // 14545
    SMSG_ADD_RUNE_POWER                              = 0x00, //
    SMSG_AI_REACTION                                 = 0x00, // 
    SMSG_ALL_ACHIEVEMENT_DATA                        = 0x00, // 
    SMSG_AREA_SPIRIT_HEALER_TIME                     = 0x00, //
    SMSG_AREA_TRIGGER_MESSAGE                        = 0x00, // 
    SMSG_ARENA_ERROR                                 = 0x00, // 
    SMSG_ARENA_OPPONENT_UPDATE                       = 0x00, // 
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED             = 0x4A4E, // 14545
    SMSG_ARENA_TEAM_COMMAND_RESULT                   = 0x00, // 
    SMSG_ARENA_TEAM_EVENT                            = 0x00, // 
    SMSG_ARENA_TEAM_INVITE                           = 0x00, // 
    SMSG_ARENA_TEAM_QUERY_RESPONSE                   = 0x00, // 
    SMSG_ARENA_TEAM_ROSTER                           = 0x00, // 
    SMSG_ARENA_TEAM_STATS                            = 0x00, // 
    SMSG_ATTACKERSTATEUPDATE                         = 0x00, // 
    SMSG_ATTACKSTART                                 = 0x00, // 
    SMSG_ATTACKSTOP                                  = 0x00, // 
    SMSG_ATTACKSWING_BADFACING                       = 0x00, // 
    SMSG_ATTACKSWING_CANT_ATTACK                     = 0x00, // 
    SMSG_ATTACKSWING_DEADTARGET                      = 0x00, // 
    SMSG_ATTACKSWING_NOTINRANGE                      = 0x00, // 
    SMSG_AUCTION_BIDDER_LIST_RESULT                  = 0x00, // 
    SMSG_AUCTION_BIDDER_NOTIFICATION                 = 0x00, // 
    SMSG_AUCTION_COMMAND_RESULT                      = 0x00, // 
    SMSG_AUCTION_LIST_PENDING_SALES                  = 0x00, // 
    SMSG_AUCTION_LIST_RESULT                         = 0x00, // 
    SMSG_AUCTION_OWNER_LIST_RESULT                   = 0x00, // 
    SMSG_AUCTION_OWNER_NOTIFICATION                  = 0x00, // 
    SMSG_AUCTION_REMOVED_NOTIFICATION                = 0x00, // 
    SMSG_AURA_UPDATE                                 = 0x00, // 
    SMSG_AURA_UPDATE_ALL                             = 0x00, // 
    SMSG_AURACASTLOG                                 = 0x00, //
    SMSG_AUTH_CHALLENGE                              = 0x1181, // 14545
    SMSG_AUTH_RESPONSE                               = 0x8867, // 14545
    SMSG_AVAILABLE_VOICE_CHANNEL                     = 0x00, // 
    SMSG_BARBER_SHOP_RESULT                          = 0x00, // 
    SMSG_BATTLEFIELD_LIST                            = 0x00, // 
    SMSG_BATTLEFIELD_MGR_EJECTED                     = 0x00, // 
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING               = 0x00, // 
    SMSG_BATTLEFIELD_MGR_ENTERED                     = 0x00, // 
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                = 0x00, // 
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                = 0x00, // 
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE      = 0x00, // 
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                = 0x00, // 
    SMSG_BATTLEFIELD_PORT_DENIED                     = 0x00, //
    SMSG_BATTLEFIELD_STATUS1                         = 0x00, // 
    SMSG_BATTLEFIELD_STATUS2                         = 0x00, // 
    SMSG_BATTLEFIELD_STATUS3                         = 0x00, // 
    SMSG_BATTLEFIELD_STATUS4                         = 0x00, // 
    SMSG_BATTLEGROUND_INFO_THROTTLED                 = 0x00, //
    SMSG_BATTLEGROUND_PLAYER_JOINED                  = 0x00, // 
    SMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x00, // 
    SMSG_BINDPOINTUPDATE                             = 0x00, // 
    SMSG_BINDZONEREPLY                               = 0x00, // 
    SMSG_BINDER_CONFIRM                              = 0x00, // 
    SMSG_BREAK_TARGET                                = 0x00, // 
    SMSG_BUY_BANK_SLOT_RESULT                        = 0x00, // 
    SMSG_BUY_ITEM                                    = 0x00, //
    SMSG_BUY_FAILED                                  = 0x00, //
    SMSG_CALENDAR_COMMAND_RESULT                     = 0x00, // 
    SMSG_CALENDAR_SEND_NUM_PENDING                   = 0x00, // 
    SMSG_CALENDAR_SEND_CALENDAR                      = 0x00, // 
    SMSG_CANCEL_AUTO_REPEAT                          = 0x00, // 
    SMSG_CANCEL_COMBAT                               = 0x00, // 
    SMSG_CAST_FAILED                                 = 0x00, // 
    SMSG_CHANNEL_LIST                                = 0x00, // 
    SMSG_CHANNEL_MEMBER_COUNT                        = 0x00, // 
    SMSG_CHANNEL_NOTIFY                              = 0x9C7F, // 14545
    SMSG_CHAR_CREATE                                 = 19547, // 14545
    SMSG_CHAR_DELETE                                 = 0x48CE, // 14545
    SMSG_CHAR_ENUM                                   = 0xA05C, // 14545
    SMSG_CHARACTER_LOGIN_FAILED                      = 0x00, // 
    SMSG_CHAR_RENAME                                 = 0x00, // 
    SMSG_CHAR_CUSTOMIZE                              = 0x00, // 
    SMSG_CHAR_FACTION_CHANGE                         = 0x00, // 
    SMSG_CHAT_PLAYER_AMBIGUOUS                       = 0x00, // 
    SMSG_CHAT_PLAYER_NOT_FOUND                       = 0x00, // 
    SMSG_CHAT_RESTRICTED                             = 0x00, // 
    SMSG_CHAT_WRONG_FACTION                          = 0xE66, // 14545
    SMSG_CHECK_FOR_BOTS                              = 0x00, //
    SMSG_CLEAR_COOLDOWN                              = 0x00, // 
    SMSG_CLEAR_TARGET                                = 0x00, // 
    SMSG_CLIENTCACHE_VERSION                         = 0x88F2, // 14545
    SMSG_CLIENT_CONTROL_UPDATE                       = 0x00, // 
    SMSG_COMBAT_LOG_MULTIPLE                         = 0x00, // 
    SMSG_COMMENTATOR_MAP_INFO                        = 0x00, // 
    SMSG_COMMENTATOR_PLAYER_INFO                     = 0x00, // 
    SMSG_COMMENTATOR_STATE_CHANGED                   = 0x00, // 
    SMSG_COMPLAIN_RESULT                             = 0x00, // 
    SMSG_COMPRESSED_MOVES                            = 0x00, // 
    SMSG_COMPRESSED_UPDATE_OBJECT                    = 0x1CC3, // 14545
    SMSG_CONTACT_LIST                                = 0x00, // 
    SMSG_CONVERT_RUNE                                = 0x00, // 
    SMSG_COOLDOWN_CHEAT                              = 0x00, // 
    SMSG_COOLDOWN_EVENT                              = 0x00, // 
    SMSG_CORPSE_NOT_IN_INSTANCE                      = 0x00, // 
    SMSG_CORPSE_RECLAIM_DELAY                        = 0x00, // 
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE          = 0x00, // 
    SMSG_CREATURE_QUERY_RESPONSE                     = 0xD847, // 14545
    SMSG_CRITERIA_DELETED                            = 0x00, // 
    SMSG_CRITERIA_UPDATE                             = 0x00, // 
    SMSG_CROSSED_INEBRIATION_THRESHOLD               = 0x00, // 
    SMSG_DAMAGE_CALC_LOG                             = 0x00, // 
    SMSG_DAMAGE_DONE_OBSOLETE                        = 0x00, //
    SMSG_DANCE_QUERY_RESPONSE                        = 0x00, // 
    SMSG_DB_REPLY                                    = 0x76EC, // 14545
    SMSG_DEATH_RELEASE_LOC                           = 0x00, // 
    SMSG_DEFENSE_MESSAGE                             = 0x00, // 
    SMSG_DESTROY_OBJECT                              = 0x00, // 
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                = 0x00, // 
    SMSG_DUEL_OUTOFBOUNDS                            = 0x00, // 
    SMSG_DUEL_INBOUNDS                               = 0x00, // 
    SMSG_DISMOUNT                                    = 0x00, // 
    SMSG_DISMOUNTRESULT                              = 0x00, // 
    SMSG_DISPEL_FAILED                               = 0x00, // 
    SMSG_DUEL_COMPLETE                               = 0x00, // 
    SMSG_DUEL_COUNTDOWN                              = 0x00, // 
    SMSG_DUEL_REQUESTED                              = 0x00, // 
    SMSG_DUEL_WINNER                                 = 0x00, // 
    SMSG_DURABILITY_DAMAGE_DEATH                     = 0x00, // 
    SMSG_ECHO_PARTY_SQUELCH                          = 0x00, // 
    SMSG_EMOTE                                       = 0xC67, // 14545
    SMSG_ENABLE_BARBER_SHOP                          = 0x00, // 
    SMSG_ENCHANTMENTLOG                              = 0x00, // 
    SMSG_ENVIRONMENTALDAMAGELOG                      = 0x00, // 
    SMSG_EQUIPMENT_SET_LIST                          = 0x18DF, // 14545
    SMSG_EQUIPMENT_SET_SAVED                         = 0x00, // 
    SMSG_EQUIPMENT_SET_USE_RESULT                    = 0x00, // 
    SMSG_EXPECTED_SPAM_RECORDS                       = 0x00, // 
    SMSG_EXPLORATION_EXPERIENCE                      = 0x00, // 
    SMSG_FEATURE_SYSTEM_STATUS                       = 0x00, // 
    SMSG_FISH_ESCAPED                                = 0x9C66, // 14545
    SMSG_FISH_NOT_HOOKED                             = 0x18C3, // 14545
    SMSG_FORCEACTIONSHOW                             = 0x00, // 
    SMSG_FORCED_DEATH_UPDATE                         = 0x00, // 
    SMSG_FORCE_DISPLAY_UPDATE                        = 0x00, // 
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE              = 0x00, //
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                   = 0x00, //
    SMSG_FORCE_MOVE_ROOT                             = 0x00, // 
    SMSG_FORCE_MOVE_UNROOT                           = 0x00, // 
    SMSG_FORCE_PITCH_RATE_CHANGE                     = 0x00, //
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                 = 0x00, // 
    SMSG_FORCE_RUN_SPEED_CHANGE                      = 0x00, // 
    SMSG_FORCE_SEND_QUEUED_PACKETS                   = 0x00, // 
    SMSG_FORCE_TURN_RATE_CHANGE                      = 0x00, //
    SMSG_FORCE_SWIM_SPEED_CHANGE                     = 0x00, //
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE                = 0x00, //
    SMSG_FORCE_WALK_SPEED_CHANGE                     = 0x00, //
    SMSG_FRIEND_STATUS                               = 0x00, // 
    SMSG_GAMEOBJECT_CUSTOM_ANIM                      = 0x00, //
    SMSG_GAMEOBJECT_DESPAWN_ANIM                     = 0x00, // 
    SMSG_GAMEOBJECT_PAGETEXT                         = 0x00, // 
    SMSG_GAMEOBJECT_QUERY_RESPONSE                   = 0xCCF7, // 14545
    SMSG_GAMEOBJECT_RESET_STATE                      = 0x00, // 
    SMSG_GAMESPEED_SET                               = 0x00, // 
    SMSG_GAMETIME_SET                                = 0x00, // 
    SMSG_GAMETIME_UPDATE                             = 0x00, // 
    SMSG_GMRESPONSE_STATUS_UPDATE                    = 0x00, // 
    SMSG_GMRESPONSE_RECEIVED                         = 0x00, // 
    SMSG_GMTICKET_DELETETICKET                       = 0x00, // 
    SMSG_GMTICKET_GETTICKET                          = 0x00, // 
    SMSG_GM_MESSAGECHAT                              = 0x00, // 
    SMSG_GMTICKET_CREATE                             = 0x00, // 
    SMSG_GMTICKET_SYSTEMSTATUS                       = 0x9C7E, // 14545
    SMSG_GMTICKET_UPDATETEXT                         = 0x00, // 
    SMSG_GODMODE                                     = 0xDEEE, // 14545
    SMSG_GOSSIP_COMPLETE                             = 0x00, // 
    SMSG_GOSSIP_MESSAGE                              = 0xCCEB, // 14545
    SMSG_GOSSIP_POI                                  = 0x00, // 
    SMSG_GROUP_CANCEL                                = 0x00, // 
    SMSG_GROUP_DECLINE                               = 0x00, // 
    SMSG_GROUP_DESTROYED                             = 0x00, // 
    SMSG_GROUP_INVITE                                = 0x00, // 
    SMSG_GROUP_JOINED_BATTLEGROUND                   = 0x00, // 
    SMSG_GROUP_LIST                                  = 0x00, // 
    SMSG_GROUP_SET_LEADER                            = 0x00, // 
    SMSG_GROUP_UNINVITE                              = 0x00, // 
    SMSG_GUILD_BANK_LIST                             = 0x5EFB, // 14545
    SMSG_GUILD_COMMAND_RESULT                        = 0x00, // 
    SMSG_GUILD_DECLINE                               = 0x00, // 
    SMSG_GUILD_EVENT                                 = 0x8AC2, // 14545
    SMSG_GUILD_INFO                                  = 0x00, // 
    SMSG_GUILD_INVITE                                = 0x00, // 
    SMSG_GUILD_MAX_DAILY_XP                          = 0x00, //
    SMSG_GUILD_NEWS_UPDATE                           = 0x00, // 
    SMSG_GUILD_QUERY_RESPONSE                        = 0xCA66, // 14545
    SMSG_GUILD_RANK                                  = 0xA6EC, // 14545
    SMSG_GUILD_RANKS_UPDATE                          = 0x00, //
    SMSG_GUILD_REWARDS_LIST                          = 0x00, // 
    SMSG_GUILD_ROSTER                                = 0x00, // 
    SMSG_GUILD_TRADESKILL_UPDATE                     = 0x00, // 
    SMSG_GUILD_UPDATE_ROSTER                         = 0x00, //
    SMSG_GUILD_XP_UPDATE                             = 0x00, //
    SMSG_HIGHEST_THREAT_UPDATE                       = 0x00, // 
    SMSG_INITIALIZE_FACTIONS                         = 0x00, // 
    SMSG_INITIAL_SPELLS                              = 0x00, // 
    SMSG_INIT_CURRENCY                               = 0x227E, // 14545
    SMSG_INIT_WORLD_STATES                           = 0x9EDA, // 14545
    SMSG_INSPECT                                     = 0x00, // 
    SMSG_INSPECT_HONOR_STATS                         = 0x00, // 
    SMSG_INSPECT_TALENT                              = 0x00, // 
    SMSG_INSTANCE_DIFFICULTY                         = 0x00, // 
    SMSG_INSTANCE_LOCK_WARNING_QUERY                 = 0x00, // 
    SMSG_INSTANCE_RESET                              = 0x00, // 
    SMSG_INSTANCE_RESET_FAILED                       = 0x00, // 
    SMSG_INSTANCE_SAVE_CREATED                       = 0x00, // 
    SMSG_INVALID_PROMOTION_CODE                      = 0x00, // 
    SMSG_INVALIDATE_DANCE                            = 0x00, // 
    SMSG_INVALIDATE_PLAYER                           = 0x00, // 
    SMSG_INVENTORY_CHANGE_FAILURE                    = 0x00, // 
    SMSG_ITEM_COOLDOWN                               = 0x00, // 
    SMSG_ITEM_ENCHANT_TIME_UPDATE                    = 0x00, // 
    SMSG_ITEM_NAME_QUERY_RESPONSE                    = 0x00, // 
    SMSG_ITEM_PUSH_RESULT                            = 0x00, // 
    SMSG_ITEM_QUERY_MULTIPLE_RESPONSE                = 0x00, //
    SMSG_ITEM_QUERY_SINGLE_RESPONSE                  = 0x00, // 
    SMSG_ITEM_REFUND_INFO_RESPONSE                   = 0x00, // 
    SMSG_ITEM_REFUND_RESULT                          = 0x00, // 
    SMSG_ITEM_TEXT_QUERY_RESPONSE                    = 0x00, // 
    SMSG_ITEM_TIME_UPDATE                            = 0x00, // 
    SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x00, // 
    SMSG_LEARNED_DANCE_MOVES                         = 0x00, // 
    SMSG_LEARNED_SPELL                               = 0x00, // 
    SMSG_LEVELUP_INFO                                = 0x00, // 
    SMSG_LFG_DISABLED                                = 0x00, // 
    SMSG_LFG_JOIN_RESULT                             = 0x00, // 
    SMSG_LFG_OFFER_CONTINUE                          = 0x00, // 
    SMSG_LFG_OPEN_FROM_GOSSIP                        = 0x00, // 
    SMSG_LFG_PARTY_INFO                              = 0x00, // 
    SMSG_LFG_PLAYER_INFO                             = 0x00, // 
    SMSG_LFG_PLAYER_REWARD                           = 0x00, // 
    SMSG_LFG_PROPOSAL_UPDATE                         = 0x00, // 
    SMSG_LFG_QUEUE_STATUS                            = 0x00, // 
    SMSG_LFG_ROLE_CHECK_UPDATE                       = 0x00, // 
    SMSG_LFG_ROLE_CHOSEN                             = 0x00, // 
    SMSG_LFG_TELEPORT_DENIED                         = 0x00, // 
    SMSG_LFG_UPDATE_SEARCH                           = 0x00, // 
    SMSG_LFG_UPDATE_PARTY                            = 0x00, // 
    SMSG_LFG_UPDATE_PLAYER                           = 0x00, // 
    SMSG_LIST_INVENTORY                              = 0x264C, // 14545
    SMSG_LOGIN_SETTIMESPEED                          = 0x00, // 
    SMSG_LOGIN_VERIFY_WORLD                          = 0xC86E, // 14545
    SMSG_LOGOUT_CANCEL_ACK                           = 0x00, // 
    SMSG_LOGOUT_COMPLETE                             = 0xCC6B, // 14545
    SMSG_LOGOUT_RESPONSE                             = 0x886A, // 14545
    SMSG_LOG_XPGAIN                                  = 0x00, // 
    SMSG_LOOT_ALL_PASSED                             = 0x00, // 
    SMSG_LOOT_CLEAR_MONEY                            = 0x00, // 
    SMSG_LOOT_ITEM_NOTIFY                            = 0x00, // 
    SMSG_LOOT_LIST                                   = 0x00, // 
    SMSG_LOOT_MASTER_LIST                            = 0x00, // 
    SMSG_LOOT_MONEY_NOTIFY                           = 0x00, // 
    SMSG_LOOT_RELEASE_RESPONSE                       = 0x00, // 
    SMSG_LOOT_REMOVED                                = 0x00, // 
    SMSG_LOOT_RESPONSE                               = 0x00, // 
    SMSG_LOOT_ROLL                                   = 0x00, // 
    SMSG_LOOT_ROLL_WON                               = 0x00, // 
    SMSG_LOOT_SLOT_CHANGED                           = 0x00, // 
    SMSG_LOOT_START_ROLL                             = 0x00, // 
    SMSG_MAIL_LIST_RESULT                            = 0x00, // 
    SMSG_MEETINGSTONE_COMPLETE                       = 0x00, // 
    SMSG_MEETINGSTONE_IN_PROGRESS                    = 0x00, // 
    SMSG_MEETINGSTONE_MEMBER_ADDED                   = 0x00, // 
    SMSG_MEETINGSTONE_SETQUEUE                       = 0x00, // 
    SMSG_MESSAGECHAT                                 = 0x5E52, // 14545
    SMSG_MIRRORIMAGE_DATA                            = 0x00, // 
    SMSG_MODIFY_COOLDOWN                             = 0x00, // 
    SMSG_MONSTER_MOVE                                = 0x4C53, // 14545
    SMSG_MONSTER_MOVE_TRANSPORT                      = 0x88FB, // 14545
    SMSG_MOTD                                        = 0xCA4B, // 14545
    SMSG_MOUNTSPECIAL_ANIM                           = 0x00, // 
    SMSG_MOUNTRESULT                                 = 0x00, // 
    SMSG_MOVE_FEATHER_FALL                           = 0x00, // 
    SMSG_MOVE_NORMAL_FALL                            = 0x00, // 
    SMSG_MOVE_SET_CAN_FLY                            = 0x00, // 
    SMSG_MOVE_SET_HOVER                              = 0x00, // 
    SMSG_MOVE_UNSET_CAN_FLY                          = 0x00, // 
    SMSG_MOVE_UNSET_HOVER                            = 0x00, // 
    SMSG_MOVE_WATER_WALK                             = 0x00, // 
    SMSG_MOVE_LAND_WALK                              = 0x00, // 
    CMSG_MOVE_HOVER_ACK                              = 0x00, //
    SMSG_MOVE_KNOCK_BACK                             = 0x00, //
    SMSG_MOVE_SET_WALK_IN_AIR                        = 0x00, //
    SMSG_MOVE_UNSET_WALK_IN_AIR                      = 0x00, //
    SMSG_MULTIPLE_PACKETS                            = 0x00, // 
    SMSG_NAME_QUERY_RESPONSE                         = 0x9CE6, // 14545
    SMSG_NEW_TAXI_PATH                               = 0xC8FF, // Might be 0x98CF
    SMSG_NEW_WORLD                                   = 0x00, // 
    SMSG_NOTIFICATION                                = 0x00, // 
    SMSG_NOTIFY_DANCE                                = 0x00, // 
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                  = 0x00, // 
    SMSG_NPC_TEXT_UPDATE                             = 0x4C72, // 14545
    SMSG_NPC_WONT_TALK                               = 0x00, //
    SMSG_OFFER_PETITION_ERROR                        = 0x00, // 
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA        = 0x00, // 
    SMSG_OPEN_CONTAINER                              = 0x00, //
    SMSG_PAGE_TEXT_QUERY_RESPONSE                    = 0x18D2, // 14545
    SMSG_PARTYKILLLOG                                = 0x00, // 
    SMSG_PARTY_MEMBER_STATS                          = 0x00, // 
    SMSG_PARTY_MEMBER_STATS_FULL                     = 0x00, // 
    SMSG_PARTY_COMMAND_RESULT                        = 0x00, // 
    SMSG_PAUSE_MIRROR_TIMER                          = 0x00, // 
    SMSG_PERIODICAURALOG                             = 0x00, // 
    SMSG_PETGODMODE                                  = 0x00, // 
    SMSG_PETITION_QUERY_RESPONSE                     = 0x00, // 
    SMSG_PET_ACTION_FEEDBACK                         = 0x00, // 
    SMSG_PET_ACTION_SOUND                            = 0x00, // 
    SMSG_PET_CAST_FAILED                             = 0x00, // 
    SMSG_PET_DISMISS_SOUND                           = 0x00, // 
    SMSG_PET_GUIDS                                   = 0x00, // 
    SMSG_PET_LEARNED_SPELL                           = 0xDC5E, // 14545
    SMSG_PET_MODE                                    = 0x00, // 
    SMSG_PET_NAME_QUERY_RESPONSE                     = 0x00, // 
    SMSG_PET_NAME_INVALID                            = 0x00, // 
    SMSG_PET_REMOVED_SPELL                           = 0x18F6, // 14545
    SMSG_PET_SPELLS                                  = 0x00, // 
    SMSG_PET_TAME_FAILURE                            = 0x00, // 
    SMSG_PET_UPDATE_COMBO_POINTS                     = 0x00, // 
    SMSG_PETITION_SHOWLIST                           = 0x00, // 
    SMSG_PETITION_SHOW_SIGNATURES                    = 0x00, // 
    SMSG_PETITION_SIGN_RESULTS                       = 0x00, // 
    SMSG_PLAYER_MOVE                                 = 0x00, // 
    SMSG_PLAYED_TIME                                 = 0x00, // 
    SMSG_PLAYERBINDERROR                             = 0x5A4F, // 14545
    SMSG_PLAYERBOUND                                 = 0x00, // 
    SMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x00, // 
    SMSG_BATTLEGROUND_PLAYER_LEFT                    = 0x00, //
    SMSG_PLAYER_SKINNED                              = 0x00, // 
    SMSG_PLAYER_VEHICLE_DATA                         = 0x00, // 
    SMSG_PLAY_DANCE                                  = 0x00, // 
    SMSG_PLAY_MUSIC                                  = 0x00, // 
    SMSG_PLAY_OBJECT_SOUND                           = 0x00, // 
    SMSG_PLAY_SOUND                                  = 0x00, // 
    SMSG_PLAY_SPELL_VISUAL                           = 0x00, // 
    SMSG_PLAY_SPELL_IMPACT                           = 0x00, // 
    SMSG_PLAY_TIME_WARNING                           = 0x00, // 
    SMSG_PONG                                        = 0x0380, // 14545
    SMSG_POWER_UPDATE                                = 0x00, // 
    SMSG_PRE_RESURRECT                               = 0x00, // 
    SMSG_PROCRESIST                                  = 0x00, // 
    SMSG_PROPOSE_LEVEL_GRANT                         = 0x00, // 
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                = 0x00, //
    SMSG_PVP_CREDIT                                  = 0x00, // 
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE             = 0x00, // 
    SMSG_QUERY_TIME_RESPONSE                         = 0x00, // 
    SMSG_QUESTGIVER_OFFER_REWARD                     = 0x00, // 
    SMSG_QUESTGIVER_QUEST_COMPLETE                   = 0x00, // 
    SMSG_QUESTGIVER_QUEST_DETAILS                    = 0xCE5F, // 14545
    SMSG_QUESTGIVER_QUEST_FAILED                     = 0xD8FF, // 14545
    SMSG_QUESTGIVER_QUEST_LIST                       = 0xDEF6, // 14545
    SMSG_QUESTGIVER_REQUEST_ITEMS                    = 0x9CEE, // 14545
    SMSG_QUESTGIVER_STATUS                           = 0xC846, // 14545
    SMSG_QUESTGIVER_STATUS_MULTIPLE                  = 0xDCFF, // 14545
    SMSG_QUESTLOG_FULL                               = 0x4EDE, // 14545
    SMSG_QUESTUPDATE_ADD_KILL                        = 0x00, // 
    SMSG_QUESTUPDATE_ADD_PVP_KILL                    = 0x00, // 
    SMSG_QUESTUPDATE_COMPLETE                        = 0x9CD6, // 14545
    SMSG_QUESTUPDATE_FAILED                          = 0x9EF6, // 14545
    SMSG_QUESTUPDATE_FAILEDTIMER                     = 0x00, // 
    SMSG_QUEST_CONFIRM_ACCEPT                        = 0x00, // 
    SMSG_QUEST_FORCE_REMOVED                         = 0x00, // 
    SMSG_QUEST_POI_QUERY_RESPONSE                    = 0x00, // 
    SMSG_QUEST_QUERY_RESPONSE                        = 0x9E56, // 14545
    SMSG_QUESTGIVER_QUEST_INVALID                    = 0x00, //
    SMSG_QUESTUPDATE_ADD_ITEM_OBSOLETE               = 0x00, // 
    SMSG_RAID_GROUP_ONLY                             = 0x00, //
    SMSG_RAID_INSTANCE_INFO                          = 0x00, // 
    SMSG_RAID_INSTANCE_MESSAGE                       = 0x00, // 
    SMSG_READ_ITEM_FAILED                            = 0x00, // 
    SMSG_READ_ITEM_OK                                = 0x00, // 
    SMSG_REALM_SPLIT                                 = 0x1AF2, // 14545
    SMSG_REAL_GROUP_UPDATE                           = 0x00, // 
    SMSG_RECEIVED_MAIL                               = 0x00, // 
    SMSG_REDIRECT_CLIENT                             = 0x0180, // 14545
    SMSG_REFER_A_FRIEND_FAILURE                      = 0x00, // 
    SMSG_REMOVED_SPELL                               = 0x00, // 
    SMSG_REPORT_PVP_AFK_RESULT                       = 0x00, // 
    SMSG_REQUEST_CEMETERY_LIST_RESPONSE              = 0x00, // 
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                = 0x00, // 
    SMSG_RESET_FAILED_NOTIFY                         = 0x00, //
    SMSG_RESISTLOG                                   = 0x00, //
    SMSG_RESURRECT_REQUEST                           = 0x00, // 
    SMSG_RESYNC_RUNES                                = 0x00, //
    SMSG_RWHOIS                                      = 0x00, // 
    SMSG_SELL_ITEM                                   = 0x00, //
    SMSG_SEND_MAIL_RESULT                            = 0x00, // 
    SMSG_SEND_UNLEARN_SPELLS                         = 0x00, // 
    SMSG_SERVERTIME                                  = 0x00, // 
    SMSG_SERVER_FIRST_ACHIEVEMENT                    = 0x00, // 
    SMSG_SERVER_MESSAGE                              = 0x00, // 
    SMSG_SET_FACTION_ATWAR                           = 0x00, // 
    SMSG_SET_FACTION_STANDING                        = 0x00, // 
    SMSG_SET_FACTION_VISIBLE                         = 0x00, // 
    SMSG_SET_FLAT_SPELL_MODIFIER                     = 0x00, // 
    SMSG_SET_FORCED_REACTIONS                        = 0x00, // 
    SMSG_SET_PCT_SPELL_MODIFIER                      = 0x00, // 
    SMSG_SET_PHASE_SHIFT                             = 0x204C, // 14545
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT            = 0x00, // 
    SMSG_SET_PROFICIENCY                             = 0x00, // 
    SMSG_SET_PROJECTILE_POSITION                     = 0x00, // 
    SMSG_SHOWTAXINODES                               = 0x8CFB, // 14545
    SMSG_SHOW_BANK                                   = 0x00, // 
    SMSG_SPELLBREAKLOG                               = 0x00, // 
    SMSG_SPELLDAMAGESHIELD                           = 0x00, // 
    SMSG_SPELLENERGIZELOG                            = 0x00, // 
    SMSG_SPELLHEALLOG                                = 0x00, // 
    SMSG_SPELLINSTAKILLLOG                           = 0x00, // 
    SMSG_SPELLLOGEXECUTE                             = 0x00, // 
    SMSG_SPELLLOGMISS                                = 0x00, // 
    SMSG_SPELLNONMELEEDAMAGELOG                      = 0x00, // 
    SMSG_SPELLORDAMAGE_IMMUNE                        = 0x00, // 
    SMSG_SPELL_COOLDOWN                              = 0x00, // 
    SMSG_SPELL_DELAYED                               = 0x00, // 
    SMSG_SPELLDISPELLOG                              = 0x00, // 
    SMSG_SPELL_FAILED_OTHER                          = 0x00, // 
    SMSG_SPELL_FAILURE                               = 0x00, // 
    SMSG_SPELL_GO                                    = 0x0A53, // 14545
    SMSG_SPELL_START                                 = 0xCE43, // 14545
    SMSG_SPELLSTEALLOG                               = 0x00, // 
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                  = 0x00, // 
    SMSG_SPIRIT_HEALER_CONFIRM                       = 0x00, // 
    SMSG_SPLINE_MOVE_WATER_WALK                      = 0x00, //
    SMSG_SPLINE_MOVE_LAND_WALK                       = 0x00, //
    SMSG_SPLINE_MOVE_ROOT                            = 0x00, // 
    SMSG_SPLINE_MOVE_UNROOT                          = 0x00, //
    SMSG_STABLE_RESULT                               = 0x00, // 
    SMSG_STANDSTATE_UPDATE                           = 0x00, // 
    SMSG_START_MIRROR_TIMER                          = 0x00, // 
    SMSG_STOP_DANCE                                  = 0x00, // 
    SMSG_STOP_MIRROR_TIMER                           = 0x00, // 
    SMSG_SUMMON_REQUEST                              = 0x00, // 
    SMSG_SUPERCEDED_SPELL                            = 0x00, // 
    SMSG_TALENTS_INFO                                = 0x00, // 
    SMSG_TAXINODE_STATUS                             = 0x8CFB, // 14545
    SMSG_TOGGLE_XP_GAIN                              = 0x8A5B, // 14545
    SMSG_TEXT_EMOTE                                  = 0x00, // 
    SMSG_THREAT_CLEAR                                = 0x00, // 
    SMSG_THREAT_REMOVE                               = 0x00, // 
    SMSG_THREAT_UPDATE                               = 0x00, // 
    SMSG_TIME_SYNC_REQ                               = 0x00, // 
    SMSG_TITLE_EARNED                                = 0x00, // 
    SMSG_TOTEM_CREATED                               = 0x00, // 
    SMSG_TRADE_STATUS                                = 0x00, // 
    SMSG_TRADE_STATUS_EXTENDED                       = 0x00, // 
    SMSG_TRAINER_LIST                                = 0xC84E, // 14545
    SMSG_TRAINER_BUY_RESULT                          = 0x00, // 
    SMSG_TRANSFER_ABORTED                            = 0x00, // 
    SMSG_TRANSFER_PENDING                            = 0x00, // 
    SMSG_TRIGGER_CINEMATIC                           = 0x00, // 
    SMSG_TRIGGER_MOVIE                               = 0x00, // 
    SMSG_TURN_IN_PETITION_RESULTS                    = 0x00, // 
    SMSG_TUTORIAL_FLAGS                              = 0x1A46, // 14545
    SMSG_UNIT_SPELLCAST_START                        = 0x00, // 
    SMSG_UPDATE_ACCOUNT_DATA                         = 0x00, // 
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                = 0x5E53, // 14545
    SMSG_UPDATE_COMBO_POINTS                         = 0x00, // 
    SMSG_UPDATE_CURRENCY                             = 0x00, // 
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                  = 0x00, // 
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT              = 0x00, // 
    SMSG_UPDATE_INSTANCE_OWNERSHIP                   = 0x00, // 
    SMSG_UPDATE_LAST_INSTANCE                        = 0x00, // 
    SMSG_UPDATE_LFG_LIST                             = 0x00, // 
    SMSG_UPDATE_OBJECT                               = 0x1EE7, // 14545
    SMSG_UPDATE_WORLD_STATE                          = 0x00, // 
    SMSG_USERLIST_ADD                                = 0x00, // 
    SMSG_USERLIST_REMOVE                             = 0x00, // 
    SMSG_USERLIST_UPDATE                             = 0x00, // 
    SMSG_VOICE_CHAT_STATUS                           = 0x00, // 
    SMSG_VOICE_PARENTAL_CONTROLS                     = 0x00, // 
    SMSG_VOICE_SESSION_LEAVE                         = 0x00, // 
    SMSG_VOICE_SESSION_ROSTER_UPDATE                 = 0x00, // 
    SMSG_VOICE_SET_TALKER_MUTED                      = 0x00, // 
    SMSG_WEATHER                                     = 0x00, // 
    SMSG_WARDEN_DATA                                 = 0x00, // 
    SMSG_WHO                                         = 0x00, // 
    SMSG_WHOIS                                       = 0x00, // 
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x00, // 
    SMSG_ZONE_UNDER_ATTACK                           = 0x00, // 

    SMSG_VERIFY_CONNECTIVITY                         = 20311, // 14545
    CMSG_VERIFY_CONNECTIVITY_RESPONSE                = 19538, //1280462679, // 14545 special opcode, client sends as uint32

    SMSG_BATTLEFIELD_STATUS                          = 0x00, // 
    SMSG_QUESTUPDATE_ADD_ITEM                        = 0x00, // 
    SMSG_OVERRIDE_LIGHT                              = 0x00, // 
    CMSG_RANDOMIZE_CHAR_NAME                         = 35481, // 14545 byte unk, byte race
    SMSG_RANDOMIZE_CHAR_NAME                         = 61660, // 14545 byte unk(0x80), string name
    
    CMSG_MOVE_SET_COLLISION_HGT                      = 0, //
    SMSG_MOVE_SET_COLLISION_HGT                      = 0, //
};

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;

typedef void(WorldSession::*pOpcodeHandler)(WorldPacket& recvPacket);

struct OpcodeHandler
{
    OpcodeHandler() {}
    OpcodeHandler(const char* _name, SessionStatus _status, PacketProcessing _processing, pOpcodeHandler _handler)
        : name(_name), status(_status), packetProcessing(_processing), handler(_handler) {}

    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    pOpcodeHandler handler;
};

extern OpcodeHandler* opcodeTable[NUM_OPCODE_HANDLERS];
void InitOpcodes();

/// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(Opcodes id)
{
    if (id < NUM_OPCODE_HANDLERS)
    {
        OpcodeHandler* handler = opcodeTable[uint32(id)];
        return handler ? handler->name : "UNKNOWN OPCODE";
    }
    else
        return "UNKNOWN OPCODE";
}
#endif
/// @}
