#!/usr/bin/env python

from __future__ import division

import sys

import mpq

archive = mpq.Archive(sys.argv[1])

print "Name:              %s" % sys.argv[1]
print "Version:           %s" % archive.filename
print "Offset:            %s" % archive.offset
print "Packed size:       %s" % archive.packed_size
print "Unpacked size:     %s" % archive.unpacked_size
print "Compression ratio: %s" % (archive.packed_size/archive.unpacked_size)
