
DROP TABLE IF EXISTS `QuestV2CliTask`;
CREATE TABLE `QuestV2CliTask` (
  `Unk1` INT (10) NOT NULL,
  `Name` VARCHAR (255),
  `Description` VARCHAR (4098),
  `Unk2` INT (10) NOT NULL,
  `Unk3` SMALLINT (8) UNSIGNED NOT NULL,
  `Unk4` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk5` SMALLINT (10) UNSIGNED NOT NULL,
  `QuestID0` SMALLINT (10) UNSIGNED NOT NULL,
  `QuestID1` SMALLINT (10) UNSIGNED NOT NULL,
  `QuestID2` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk6` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk7` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk8` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk9` SMALLINT (10) UNSIGNED NOT NULL,
  `Unk10` TINYINT (10) UNSIGNED NOT NULL,
  `Unk11` TINYINT (10) UNSIGNED NOT NULL,
  `Unk12` TINYINT (10) UNSIGNED NOT NULL,
  `Unk13` TINYINT (10) UNSIGNED NOT NULL,
  `Unk14` TINYINT (10) UNSIGNED NOT NULL,
  `Unk15` TINYINT (10) UNSIGNED NOT NULL,
  `Unk16` TINYINT (10) UNSIGNED NOT NULL,
  `RequiredLevel` TINYINT (10) UNSIGNED NOT NULL,
  `Unk18` TINYINT (10) UNSIGNED NOT NULL,
  `ID` INT (10) UNSIGNED NOT NULL,
  `Unk19` INT (10) NOT NULL,
  `QuestInfoID` INT (10) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `quest_poi_blob`;
CREATE TABLE `quest_poi_blob`(
    `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `MapID` SMALLINT(6) NOT NULL DEFAULT 0,
    `UiMapID` INT(11) NOT NULL DEFAULT 0,
    `NumPoints` TINYINT(3) NOT NULL DEFAULT 0,
    `QuestID` INT(10) NOT NULL DEFAULT 0,
    `ObjectiveIndex` INT(10) NOT NULL DEFAULT 0,
    `PlayerConditionID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `VerifiedBuild` INT(11) DEFAULT 0,
    PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `quest_poi_point`;
CREATE TABLE `quest_poi_point`(
    `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `X` INT(10) NOT NULL DEFAULT 0,
    `Y` INT(10) NOT NULL DEFAULT 0,
    `QuestPoiBlobID` INT(11) NOT NULL DEFAULT 0,
    `VerifiedBuild` SMALLINT(6) NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `quest_v2_cli_task`;
CREATE TABLE `quest_v2_cli_task` (
  `FiltRaces` BIGINT(20) NOT NULL DEFAULT 0,
  `QuestTitle` TEXT(65535) NULL DEFAULT NULL,
  `BulletText` TEXT(65535) NULL DEFAULT NULL,
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `UniqueBitFlag` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  `ConditionID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltActiveQuest` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltClasses` SMALLINT(6) NOT NULL DEFAULT 0,
  `FiltCompletedQuestLogic` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMaxFactionID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMaxFactionValue` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMaxLevel` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMinFactionID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMinFactionValue` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMinLevel` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMinSkillID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltMinSkillValue` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltNonActiveQuest` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `BreadCrumbID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `StartItem` INT(11) NOT NULL DEFAULT 0,
  `WorldStateExpressionID` SMALLINT(6) NOT NULL DEFAULT 0,
  `QuestInfoID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `ContentTuningID` INT(11) NOT NULL DEFAULT 0,
  `FiltCompletedQuest1` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltCompletedQuest2` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `FiltCompletedQuest3` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `VerifiedBuild` SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `quest_v2_cli_task_locale` (
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `locale` VARCHAR(4) NOT NULL,
  `QuestTitle_lang` TEXT(65535) NULL DEFAULT NULL,
  `BulletText_lang` TEXT(65535) NULL DEFAULT NULL,
  `VerifiedBuild` SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `locale`)
);
