DROP TABLE IF EXISTS `garr_mission`;
CREATE TABLE `garr_mission` (
  `Duration` INT (10) UNSIGNED NOT NULL,
  `OfferTime` INT (10) UNSIGNED NOT NULL,
  `Name` TEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `Location` TEXT NOT NULL,
  `Map1X` FLOAT NOT NULL,
  `Map1Y` FLOAT NOT NULL,
  `Map2X` FLOAT NOT NULL,
  `Map2Y` FLOAT NOT NULL,
  `RequiredItemLevel` SMALLINT (5) UNSIGNED NOT NULL,
  `LocPrefixID` SMALLINT (5) UNSIGNED NOT NULL,
  `CurrencyID` SMALLINT (5) UNSIGNED NOT NULL,
  `RequiredLevel` TINYINT (3) UNSIGNED NOT NULL,
  `GarrMechanicTypeRecID` TINYINT (3) UNSIGNED NOT NULL,
  `RequiredFollowersCount` TINYINT (3) UNSIGNED NOT NULL,
  `Category` TINYINT (3) UNSIGNED NOT NULL,
  `MissionType` TINYINT (3) UNSIGNED NOT NULL,
  `LostChance` TINYINT (3) UNSIGNED NOT NULL,
  `unk1` TINYINT (3) UNSIGNED NOT NULL,
  `ID` INT (10) UNSIGNED NOT NULL,
  `TravelTime` INT (10) UNSIGNED NOT NULL,
  `SubCategory2` INT (10) UNSIGNED NOT NULL,
  `SubCategory1` INT (10) UNSIGNED NOT NULL,
  `CurrencyCost` INT (10) UNSIGNED NOT NULL,
  `Flags` INT (10) UNSIGNED NOT NULL,
  `RewardFollowerExperience` INT (10) UNSIGNED NOT NULL,
  `unk2` INT (10) UNSIGNED NOT NULL,
  `unk3` INT (10) UNSIGNED NOT NULL,
  `unk4` INT (10) UNSIGNED NOT NULL,
  `VerifiedBuild` SMALLINT (6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `garr_mission_locale`;
CREATE TABLE `garr_mission_locale` (
  `ID` INT (10) UNSIGNED NOT NULL,
  `locale` VARCHAR (4) NOT NULL,
  `Name_lang` TEXT NOT NULL,
  `Description_lang` TEXT NOT NULL,
  `Location_lang` TEXT NOT NULL,
  `VerifiedBuild` SMALLINT (6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
);
