// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_extensions/field_options.proto

#ifndef PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED
#define PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include "google/protobuf/descriptor.pb.h"
#include "Define.h" // for TC_PROTO_API
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {

// Internal implementation detail -- do not call these.
void TC_PROTO_API protobuf_AddDesc_global_5fextensions_2ffield_5foptions_2eproto();
void protobuf_AssignDesc_global_5fextensions_2ffield_5foptions_2eproto();
void protobuf_ShutdownFile_global_5fextensions_2ffield_5foptions_2eproto();


enum LogOption {
  HIDDEN = 1,
  HEX = 2
};
TC_PROTO_API bool LogOption_IsValid(int value);
const LogOption LogOption_MIN = HIDDEN;
const LogOption LogOption_MAX = HEX;
const int LogOption_ARRAYSIZE = LogOption_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* LogOption_descriptor();
inline const ::std::string& LogOption_Name(LogOption value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogOption_descriptor(), value);
}
inline bool LogOption_Parse(
    const ::std::string& name, LogOption* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogOption>(
    LogOption_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

static const int kLogFieldNumber = 50000;
TC_PROTO_API extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::bgs::protocol::LogOption, ::bgs::protocol::LogOption_IsValid>, 14, false >
  log;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bgs::protocol::LogOption> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::LogOption>() {
  return ::bgs::protocol::LogOption_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED
