UPDATE `creature_addon` SET `emote`=010 WHERE `emote`=094; -- STATE_DANCE
UPDATE `creature_addon` SET `emote`=027 WHERE `emote`=044; -- STATE_READYUNARMED
UPDATE `creature_addon` SET `emote`=029 WHERE `emote`=025; -- STATE_POINT(DNR)
UPDATE `creature_addon` SET `emote`=064 WHERE `emote`=462; -- STATE_STUN
UPDATE `creature_addon` SET `emote`=068 WHERE `emote`=016; -- STATE_KNEEL
UPDATE `creature_addon` SET `emote`=069 WHERE `emote`=432; -- STATE_USESTANDING
UPDATE `creature_addon` SET `emote`=193 WHERE `emote`=050; -- STATE_SPELLPRECAST
UPDATE `creature_addon` SET `emote`=214 WHERE `emote`=213; -- STATE_READYRIFLE
UPDATE `creature_addon` SET `emote`=233 WHERE `emote`=467; -- STATE_WORK_MINING
UPDATE `creature_addon` SET `emote`=234 WHERE `emote`=466; -- STATE_WORK_CHOPWOOD
UPDATE `creature_addon` SET `emote`=253 WHERE `emote`=021; -- STATE_APPLAUD
UPDATE `creature_addon` SET `emote`=333 WHERE `emote`=045; -- STATE_READY1H
UPDATE `creature_addon` SET `emote`=376 WHERE `emote`=048; -- STATE_READYBOW
UPDATE `creature_addon` SET `emote`=379 WHERE `emote`=380; -- STATE_FISHING
UPDATE `creature_addon` SET `emote`=392 WHERE `emote`=011; -- STATE_LAUGH
UPDATE `creature_addon` SET `emote`=400 WHERE `emote`=401; -- STATE_DANCESPECIAL
UPDATE `creature_addon` SET `emote`=416 WHERE `emote`=402; -- STATE_CUSTOM_SPELL_01
UPDATE `creature_addon` SET `emote`=417 WHERE `emote`=403; -- STATE_CUSTOM_SPELL_02
UPDATE `creature_addon` SET `emote`=418 WHERE `emote`=007; -- STATE_EAT
UPDATE `creature_addon` SET `emote`=419 WHERE `emote`=405; -- STATE_CUSTOM_SPELL_04
UPDATE `creature_addon` SET `emote`=420 WHERE `emote`=404; -- STATE_CUSTOM_SPELL_03
UPDATE `creature_addon` SET `emote`=421 WHERE `emote`=406; -- STATE_CUSTOM_SPELL_05
UPDATE `creature_addon` SET `emote`=428 WHERE `emote`=381; -- STATE_LOOT
UPDATE `creature_addon` SET `emote`=451 WHERE `emote`=477; -- STATE_SPECIALUNARMED
UPDATE `creature_template_addon` SET `emote`=010 WHERE `emote`=094; -- STATE_DANCE
UPDATE `creature_template_addon` SET `emote`=027 WHERE `emote`=044; -- STATE_READYUNARMED
UPDATE `creature_template_addon` SET `emote`=029 WHERE `emote`=025; -- STATE_POINT(DNR)
UPDATE `creature_template_addon` SET `emote`=064 WHERE `emote`=462; -- STATE_STUN
UPDATE `creature_template_addon` SET `emote`=068 WHERE `emote`=016; -- STATE_KNEEL
UPDATE `creature_template_addon` SET `emote`=069 WHERE `emote`=432; -- STATE_USESTANDING
UPDATE `creature_template_addon` SET `emote`=193 WHERE `emote`=050; -- STATE_SPELLPRECAST
UPDATE `creature_template_addon` SET `emote`=214 WHERE `emote`=213; -- STATE_READYRIFLE
UPDATE `creature_template_addon` SET `emote`=233 WHERE `emote`=467; -- STATE_WORK_MINING
UPDATE `creature_template_addon` SET `emote`=234 WHERE `emote`=466; -- STATE_WORK_CHOPWOOD
UPDATE `creature_template_addon` SET `emote`=253 WHERE `emote`=021; -- STATE_APPLAUD
UPDATE `creature_template_addon` SET `emote`=333 WHERE `emote`=045; -- STATE_READY1H
UPDATE `creature_template_addon` SET `emote`=376 WHERE `emote`=048; -- STATE_READYBOW
UPDATE `creature_template_addon` SET `emote`=379 WHERE `emote`=380; -- STATE_FISHING
UPDATE `creature_template_addon` SET `emote`=392 WHERE `emote`=011; -- STATE_LAUGH
UPDATE `creature_template_addon` SET `emote`=400 WHERE `emote`=401; -- STATE_DANCESPECIAL
UPDATE `creature_template_addon` SET `emote`=416 WHERE `emote`=402; -- STATE_CUSTOM_SPELL_01
UPDATE `creature_template_addon` SET `emote`=417 WHERE `emote`=403; -- STATE_CUSTOM_SPELL_02
UPDATE `creature_template_addon` SET `emote`=418 WHERE `emote`=007; -- STATE_EAT
UPDATE `creature_template_addon` SET `emote`=419 WHERE `emote`=405; -- STATE_CUSTOM_SPELL_04
UPDATE `creature_template_addon` SET `emote`=420 WHERE `emote`=404; -- STATE_CUSTOM_SPELL_03
UPDATE `creature_template_addon` SET `emote`=421 WHERE `emote`=406; -- STATE_CUSTOM_SPELL_05
UPDATE `creature_template_addon` SET `emote`=428 WHERE `emote`=381; -- STATE_LOOT
UPDATE `creature_template_addon` SET `emote`=451 WHERE `emote`=477; -- STATE_SPECIALUNARMED
