-- 
DELETE FROM `trainer_locale` WHERE `locale` = 'deDE';
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`) VALUES
(1, 'deDE', "Hallo, $gKrieger!:Kriegerin! Bereit für etwas Training?", 0),
(2, 'deDE', "Hallo, $gKrieger!:Kriegerin! Bereit für etwas Training?", 0),
(3, 'deDE', "Hallo, Paladin! Bereit für etwas Training?", 0),
(4, 'deDE', "Hallo, Paladin! Bereit für etwas Training?", 0),
(5, 'deDE', "Hallo, Paladin! Bereit für etwas Training?", 0),
(6, 'deDE', "Hallo, Paladin! Bereit für etwas Training?", 0),
(7, 'deDE', "Hallo, $gJäger!:Jägerin! Bereit für etwas Training?", 0),
(8, 'deDE', "Hallo, $gJäger!:Jägerin! Bereit für etwas Training?", 0),
(9, 'deDE', "Hallo, $gSchurke!:Schurkin! Bereit für etwas Training?", 0),
(10, 'deDE', "Hallo, $gSchurke!:Schurkin! Bereit für etwas Training?", 0),
(11, 'deDE', "Hallo, $gPriester!:Priesterin! Bereit für etwas Training?", 0),
(12, 'deDE', "Hallo, $gPriester!:Priesterin! Bereit für etwas Training?", 0),
(13, 'deDE', "Seid gegrüßt Todesritter, bereit für etwas Training?", 0),
(14, 'deDE', "Hallo, $gSchamane!:Schamanin! Bereit für etwas Training?", 0),
(15, 'deDE', "Hallo, $gSchamane!:Schamanin! Bereit für etwas Training?", 0),
(16, 'deDE', "Hallo, $gMagier!:Magierin!; Bereit für etwas Training?", 0),
(17, 'deDE', "Hallo, $gMagier!:Magierin!; Bereit für etwas Training?", 0),
(18, 'deDE', "Willkommen!", 0),
(19, 'deDE', "Willkommen!", 0),
(20, 'deDE', "Willkommen!", 0),
(21, 'deDE', "Willkommen!", 0),
(22, 'deDE', "Willkommen!", 0),
(23, 'deDE', "Willkommen!", 0),
(24, 'deDE', "Willkommen!", 0),
(25, 'deDE', "Willkommen!", 0),
(26, 'deDE', "Willkommen!", 0),
(27, 'deDE', "Willkommen!", 0),
(28, 'deDE', "Willkommen!", 0),
(29, 'deDE', "Willkommen!", 0),
(30, 'deDE', "Willkommen!", 0),
(31, 'deDE', "Hallo, $gHexenmeister!:Hexenmeisterin!; Bereit für etwas Training?", 0),
(32, 'deDE', "Hallo, $gHexenmeister!:Hexenmeisterin!; Bereit für etwas Training?", 0),
(33, 'deDE', "Hallo, $gDruide!:Drudidin!; Bereit für etwas Training?", 0),
(34, 'deDE', "Hallo, $gDruide!:Drudidin!; Bereit für etwas Training?", 0),
(35, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(36, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(37, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(38, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(39, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(40, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(41, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(42, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(43, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(44, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(45, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(46, 'deDE', "Hallo! Kann ich Euch etwas beibringen?", 0),
(47, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(48, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(49, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(50, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(51, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(52, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(53, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(54, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(55, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(56, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(57, 'deDE', "Hallo!  Bereit für etwas Training?", 0),
(58, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(59, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(60, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(61, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(62, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(63, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(64, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(65, 'deDE', "Mit Alchemie könnt Ihr gefundene Kräuter in Heilmittel und andere Arten von Tränken verwandeln.", 0),
(66, 'deDE', "Mit Alchemie könnt Ihr gefundene Kräuter in Heilmittel und andere Arten von Tränken verwandeln.", 0),
(67, 'deDE', "Mit Alchemie könnt Ihr gefundene Kräuter in Heilmittel und andere Arten von Tränken verwandeln.", 0),
(68, 'deDE', "Mit Alchemie könnt Ihr gefundene Kräuter in Heilmittel und andere Arten von Tränken verwandeln.", 0),
(69, 'deDE', "Die Suche nach Kräutern erfordert sowohl Wissen als auch Instinkt.", 0),
(70, 'deDE', "Die Suche nach Kräutern erfordert sowohl Wissen als auch Instinkt.", 0),
(71, 'deDE', "Die Suche nach Kräutern erfordert sowohl Wissen als auch Instinkt.", 0),
(72, 'deDE', "Grüße! Kann ich Euch beibringen, wie man gefundene Stoffe in Stoffrüstung umwandelt?", 0),
(73, 'deDE', "Grüße! Kann ich Euch beibringen, wie man gefundene Stoffe in Stoffrüstung umwandelt?", 0),
(74, 'deDE', "Grüße! Kann ich Euch beibringen, wie man gefundene Stoffe in Stoffrüstung umwandelt?", 0),
(75, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0),
(76, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0),
(77, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0),
(78, 'deDE', "Ihr habt nicht gelebt, bis Ihr tief in die Erde gegraben habt.", 0),
(79, 'deDE', "Ihr habt nicht gelebt, bis Ihr tief in die Erde gegraben habt.", 0),
(80, 'deDE', "Ihr habt nicht gelebt, bis Ihr tief in die Erde gegraben habt.", 0),
(81, 'deDE', "Lasst mich Euch zeigen, wie Ihr diese Wunden verbinden könnt....", 0),
(82, 'deDE', "Lasst mich Euch zeigen, wie Ihr diese Wunden verbinden könnt....", 0),
(83, 'deDE', "Lasst mich Euch zeigen, wie Ihr diese Wunden verbinden könnt....", 0),
(84, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(85, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(86, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(87, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(88, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(89, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(90, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(91, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(92, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(93, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0),
(94, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(95, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(96, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(97, 'deDE', "Ich kann Euch beibringen, wie man mit einer Angelrute Fische fängt.", 0),
(98, 'deDE', "Ich kann Euch beibringen, wie man mit einer Angelrute Fische fängt.", 0),
(99, 'deDE', "Ich kann Euch beibringen, wie man mit einer Angelrute Fische fängt.", 0),
(100, 'deDE', "Es erfordert eine ruhige Hand, um das Leder von einem getöteten Tier zu entfernen.", 0),
(101, 'deDE', "Es erfordert eine ruhige Hand, um das Leder von einem getöteten Tier zu entfernen.", 0),
(102, 'deDE', "Es erfordert eine ruhige Hand, um das Leder von einem getöteten Tier zu entfernen.", 0),
(103, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(104, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(105, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(106, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(107, 'deDE', "Grüße! Kann ich Euch beibringen, wie man Tierhäute in Rüstung verwandelt?", 0),
(108, 'deDE', "Grüße! Kann ich Euch beibringen, wie man gefundene Stoffe in Stoffrüstung umwandelt?", 0),
(109, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(110, 'deDE', "Ihr habt nicht gelebt, bis Ihr tief in die Erde gegraben habt.", 0),
(111, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(112, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(113, 'deDE', "Grüße!  Kann ich Euch beibringen, wie man Edelsteine ​​schneidet und Schmuck herstellt?", 0),
(114, 'deDE', "Verzauberkunst ist die Kunst, bestehende Gegenstände durch Magie zu verbessern.", 0),
(115, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(116, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(117, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0),
(118, 'deDE', "Das Ingenieurwesen ist sehr einfach, sobald Ihr die Grundlagen verstanden habt.", 0),
(119, 'deDE', "Möchtet Ihr die Feinheiten der Inschriftenkunde erlernen?", 0),
(120, 'deDE', "Möchtet Ihr die Feinheiten der Inschriftenkunde erlernen?", 0),
(121, 'deDE', "Möchtet Ihr die Feinheiten der Inschriftenkunde erlernen?", 0),
(122, 'deDE', "Mit Alchemie könnt Ihr gefundene Kräuter in Heilmittel und andere Arten von Tränken verwandeln.", 0),
(123, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(124, 'deDE', "Möchtet Ihr lernen, wie Ihr das Erz, das Ihr findet, in Waffen und Metallrüstung umwandelt?", 0),
(125, 'deDE', "null", 0),
(126, 'deDE', "Kann ich Euch beibringen, wie man Fleisch von Tieren zu einem Festmahl macht?", 0);
