// -*- C++ -*-
//
// $Id: SOCK_CODgram.inl 80826 2008-03-04 14:51:23Z wotte $
ACE_BEGIN_VERSIONED_NAMESPACE_DECL
ACE_INLINE
ACE_SOCK_CODgram::ACE_SOCK_CODgram (void)
{
  ACE_TRACE ("ACE_SOCK_CODgram::ACE_SOCK_CODgram");
}
ACE_INLINE
ACE_SOCK_CODgram::~ACE_SOCK_CODgram (void)
{
  ACE_TRACE ("ACE_SOCK_CODgram::~ACE_SOCK_CODgram");
}
ACE_END_VERSIONED_NAMESPACE_DECL
