
// -*- C++ -*-
// $Id: Version.h 82705 2008-09-15 11:08:20Z sma $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 6
#define ACE_BETA_VERSION 6
#define ACE_VERSION "5.6.6"
