#include "../bloodmaul_slag_mines.h"

enum Spells
{
    SPELL_MAGMA_BARRAGE             = 150004, // + SPELL_AURA_PERIODIC_TRIGGER_SPELL | SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_MAGMA_BARRAGE_MISSILE     = 150007, // +-> + SPELL_EFFECT_TRIGGER_MISSILE
    SPELL_MAGMA_BARRAGE_SPAWN       = 167465, //     +-> SPELL_EFFECT_CREATE_AREATRIGGER[2847]
    SPELL_MAGMA_BARRAGE_AOE_TARGET  = 150006, // +->(+) SPELL_EFFECT_DUMMY
    SPELL_MAGMA_BARRAGE_AOE_MISSILE = 150306, //     +-> + SPELL_EFFECT_TRIGGER_MISSILE
  //SPELL_MAGMA_BARRAGE_SPAWN       = 167465, //         +-> SPELL_EFFECT_CREATE_AREATRIGGER[2847]
    // No Idea how it is applied, probably through the Area Trigger
    SPELL_MAGMA_BARRAGE_DAMAGE      = 150011, // SPELL_AURA_PERIODIC_DAMAGE

    SPELL_THROW_EARTH               = 150076, // + SPELL_EFFECT_DUMMY | SPELL_EFFECT_TRIGGER_MISSILE
    SPELL_SUMMON_EARTH_GUARDIAN     = 150061, // +->(+) SPELL_EFFECT_SUMMON[74570]
    SPELL_ROUGH_SMASH               = 149941, //     +-> SPELL_EFFECT_SCHOOL_DAMAGE | SPELL_AURA_MOD_STUN
    SPELL_SHATTER_EARTH             = 150324, //     +-> + SPELL_EFFECT_TRIGGER_SPELL | SPELL_EFFECT_TRIGGER_SPELL | SPELL_EFFECT_TRIGGER_SPELL
    SPELL_SHATTER_EARTH_DUMMY_A     = 150296, //         +->(+) SPELL_EFFECT_DUMMY
    SPELL_SHATTER_EARTH_MISSILE_A   = 150292, //             +-> + SPELL_EFFECT_TRIGGER_MISSILE
  //SPELL_SHATTER_EARTH_SUMMON      = 150325, //                 +-> SPELL_EFFECT_SUMMON[74766]
    SPELL_SHATTER_EARTH_DUMMY_B     = 150322, //         +->(+) SPELL_EFFECT_DUMMY
    SPELL_SHATTER_EARTH_MISSILE_B   = 150294, //             +-> + SPELL_EFFECT_TRIGGER_MISSILE
  //SPELL_SHATTER_EARTH_SUMMON      = 150325, //                 +-> SPELL_EFFECT_SUMMON[74766]
    SPELL_SHATTER_EARTH_DUMMY_C     = 150323, //         +->(+) SPELL_EFFECT_DUMMY
    SPELL_SHATTER_EARTH_MISSILE_C   = 150295, //             +-> + SPELL_EFFECT_TRIGGER_MISSILE
    SPELL_SHATTER_EARTH_SUMMON      = 150325, //                 +->(+)SPELL_EFFECT_SUMMON[74766]
    SPELL_SHATTER_EARTH_AURA        = 149945, //                     +-> + SPELL_AURA_PERIODIC_TRIGGER_SPELL
    SPELL_SHATTER_EARTH_DAMAGE      = 150344, //                         +-> SPELL_EFFECT_KNOCK_BACK | SPELL_EFFECT_SCHOOL_DAMAGE
    SPELL_SHATTER_EARTH_NE          = 149959, //                         +-> SPELL_EFFECT_CREATE_AREATRIGGER[1388]
    SPELL_SHATTER_EARTH_NW          = 149968, //                         +-> SPELL_EFFECT_CREATE_AREATRIGGER[1388]
    SPELL_SHATTER_EARTH_SW          = 149970, //                         +-> SPELL_EFFECT_CREATE_AREATRIGGER[1388]
    SPELL_SHATTER_EARTH_SE          = 149969, //                         +-> SPELL_EFFECT_CREATE_AREATRIGGER[1388]

    SPELL_THROW_FIRE                = 150078, // + SPELL_EFFECT_DUMMY | SPELL_EFFECT_TRIGGER_MISSILE
    SPELL_SUMMON_FLAME_GUARDIAN     = 150062, // +-> SPELL_EFFECT_SUMMON[74571]

    SPELL_CAMERA_SHAKE              = 143583, // SPELL_EFFECT_DUMMY
    SPELL_EXPLOSIVE_DEATH           = 150218, // + SPELL_EFFECT_DUMMY
    SPELL_SUICIDE                   = 7,      // +-> SPELL_EFFECT_INSTAKILL
};

enum Events
{
    EVENT_MAGMA_BARRAGE = 1,
    EVENT_THROW_EARTH,
    EVENT_THROW_FIRE,

    EVENT_EXPLODE
};

enum Timer
{
    TIME_MAGMA_BARRAGE_INIT     = 0 * IN_MILLISECONDS,
    TIME_MAGMA_BARRAGE          = 0 * IN_MILLISECONDS,

    TIME_THROW_EARTH            = 0 * IN_MILLISECONDS,

    TIME_THROW_FIRE             = 0 * IN_MILLISECONDS,

    TIME_EXPLODE                = 0 * IN_MILLISECONDS
};

enum Phases
{
    PHASE_FORGEMASTER_ALIVE = 1,
    PHASE_FORGEMASTER_DEAD,
};
