ALTER TABLE `lag_reports`
ROW_FORMAT=DEFAULT,
CHANGE `report_id` `report_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `player` `player` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `lag_type` `lag_type` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `map` `map` SMALLINT(5) UNSIGNED DEFAULT '0' NOT NULL;