ALTER TABLE `gameobject_template_addon`
    ADD COLUMN `AIAnimKitID` INT(10) UNSIGNED DEFAULT 0 NOT NULL AFTER `WorldEffectID`,
    ADD COLUMN `MovementID` INT(10) UNSIGNED DEFAULT 0 NOT NULL AFTER `AIAnimKitID`,
    ADD COLUMN `MeleeID` INT(10) UNSIGNED DEFAULT 0 NOT NULL AFTER `MovementID`; 
