name: Ubuntu build

on: 
  push:
    branches: [ master ]
    paths-ignore:
      - 'sql/**'

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  REPO_DIR : ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/bin/builddir
  BOOST_PLATFORM_VERSION: "18.04"
  BOOST_VERSION: "1.69.0"
  BOOST_INSTALL_DIR: "${{github.workspace}}/bin"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       include:
          - os: ubuntu-18.04
            COMPILER_CC: gcc
            COMPILER_PP: g++
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{env.REPO_DIR}}

      - name: Create Build Environment
        run: |
          sudo apt-get install libicu60
          echo "BOOST_ROOT=${{env.BOOST_INSTALL_DIR}}/boost/boost-${{env.BOOST_VERSION}}-linux-${{env.BOOST_PLATFORM_VERSION}}-gcc-x64" >> $GITHUB_ENV
          echo "GITHUB_SHORT_REV=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ARCHIVE_FILENAME=${{ github.event.repository.name }}-$(git rev-parse --short HEAD).zip" >> $GITHUB_ENV
          echo "CC=${{matrix.COMPILER_CC}}" >> $GITHUB_ENV
          echo "CXX=${{matrix.COMPILER_PP}}" >> $GITHUB_ENV
          cmake -E make_directory ${{ env.BUILD_DIR }}          
      
      # install dependencies
      - name: Cache Windows boost
        uses: actions/cache@v2
        id: cache-boost
        with:
          path: "${{env.BOOST_INSTALL_DIR}}/boost"
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/ubuntu.yml') }}

      - if: steps.cache-boost.outputs.cache-hit != 'true'
        name: Install boost
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: ${{env.BOOST_VERSION}}
          # OPTIONAL: Specify a platform version on ubuntu
          platform_version: ${{env.BOOST_PLATFORM_VERSION}}
          # OPTIONAL: Specify a custon install location
          boost_install_dir: ${{env.BOOST_INSTALL_DIR}}
          # NOTE: If a boost version matching all requirements cannot be found,
          # this build step will fail

      - name: Configure
        run: |
          cmake -DTOOLS=ON -DBoost_ARCHITECTURE=-x64 -B ${{env.BUILD_DIR}} -S ${{env.REPO_DIR}}

      - name: Build
        env:
          MAKEFLAGS: "-j8"
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}
